#pragma once
class AppPlatform{
	public:
		AppPlatform(void);
		void onAppFocusGained(void);
		void onAppFocusLost(void);
		void onAppResumed(void);
		void onLowMemory(void);
		void ~Listener();
		void ~Listener();
		void _fireAppSuspended(void);
		void _tick(void);
		void addListener(AppPlatform::Listener *,float);
		void buyGame(void);
		void checkLicense(void);
		void clearSessionIDAndRefreshToken(void);
		void createUserInput(int);
		void createUserInput(void);
		void finish(void);
		void getDateString(int);
		void getKeyFromKeyCode(int,int,int);
		void getLoginInformation(void);
		void getPixelsPerMillimeter(void);
		void getPlatformStringVar(int);
		void getPreloadingHTMLLength(void);
		void getScreenHeight(void);
		void getScreenWidth(void);
		void getUserInput(void);
		void getUserInputStatus(void);
		void hasBuyButtonWhenInvalidLicense(void);
		void hasIDEProfiler(void);
		void hideKeyboard(void);
		void isKeyboardVisible(void);
		void isNetworkEnabled(bool);
		void isPowerVR(void);
		void loadImage(ImageData &,std::string const&,bool);
		void loadTGA(ImageData &,std::string const&,bool);
		void loadTexture(std::string const&,bool);
		void openLoginWindow(void);
		void playSound(std::string const&,float,float);
		void readAssetFile(std::string const&);
		void removeListener(AppPlatform::Listener *);
		void saveScreenshot(std::string const&,int,int);
		void setLoginInformation(LoginInformation const&);
		void showDialog(int);
		void showKeyboard(std::string const&,int,bool);
		void statsTrackData(std::string const&,std::string const&);
		void supportsTouchscreen(void);
		void supportsVibration(void);
		void updateStatsUserData(std::string const&,std::string const&);
		void updateTextBoxText(std::string const&);
		void uploadPlatformDependentData(int,void *);
		void vibrate(int);
		void ~AppPlatform();
		void ~AppPlatform();
};
