#pragma once
class LevelChunk{
	public:
		LevelChunk(Level *,int,int);
		LevelChunk(Level *,uchar *,int,int);
		void addEntity(Entity *);
		void addTileEntity(TileEntity *);
		void clearUpdateMap(void);
		void countEntities(void);
		void deleteBlockData(void);
		void getBlocksAndData(uchar *,int,int,int,int,int,int,int);
		void getBrightness(LightLayer const&,int,int,int);
		void getData(int,int,int);
		void getEntities(Entity *,AABB const&,std::vector<Entity *,std::allocator<Entity *>> &);
		void getEntitiesOfClass(int,AABB const&,std::vector<Entity *,std::allocator<Entity *>> &);
		void getEntitiesOfType(int,AABB const&,std::vector<Entity *,std::allocator<Entity *>> &);
		void getHeightmap(int,int);
		void getRandom(long);
		void getRawBrightness(int,int,int,int);
		void getTile(int,int,int);
		void getTileEntity(int,int,int);
		void getTileEntityMap(void);
		void hasTileEntityAt(TileEntity *);
		void hasTileEntityAt(int,int,int);
		void init(void);
		void isAt(int,int);
		void isEmpty(void);
		void isSkyLit(int,int,int);
		void lightGap(int,int,int);
		void lightGaps(int,int);
		void lightLava(void);
		void load(void);
		void markUnsaved(void);
		void recalcBlockLights(void);
		void recalcHeight(int,int,int);
		void recalcHeightmap(void);
		void recalcHeightmapOnly(void);
		void removeEntity(Entity *);
		void removeEntity(Entity *,int);
		void removeTileEntity(int,int,int);
		void setBlocks(uchar *,int);
		void setBlocksAndData(uchar *,int,int,int,int,int,int,int);
		void setBrightness(LightLayer const&,int,int,int,int);
		void setData(int,int,int,int);
		void setTile(int,int,int,int);
		void setTileAndData(int,int,int,int,int);
		void setTileEntity(int,int,int,TileEntity *);
		void setTileRaw(int,int,int,int);
		void shouldSave(bool);
		void skyBrightnessChanged(void);
		void unload(void);
		void ~LevelChunk();
		void ~LevelChunk();
};
