#pragma once
class Minecraft{
	public:
		Minecraft(void);
		void _levelGenerated(void);
		void _reloadInput(void);
		void audioEngineOff(void);
		void audioEngineOn(void);
		void cancelLocateMultiplayer(void);
		void checkGlError(char const*);
		void connectToMCOServer(std::string const&,std::string const&,ushort);
		void gameLostFocus(void);
		void generateLevel(std::string const&,Level *);
		void getCreator(void);
		void getLevelSource(void);
		void getLicenseId(void);
		void getProgressMessage(void);
		void getProgressStageStatus(void);
		void getProgressStatusId(void);
		void getTextureAtlas(TextureAtlasId);
		void grabMouse(void);
		void handleBuildAction(BuildActionIntention *);
		void handleMouseClick(int);
		void handleMouseDown(int,bool);
		void hostMultiplayer(int);
		void init(void);
		void isCreativeMode(void);
		void isKindleFire(int);
		void isLevelGenerated(void);
		void isOnline(void);
		void isOnlineClient(void);
		void joinMultiplayer(PingedCompatibleServer const&,bool);
		void leaveGame(bool,bool);
		void locateMultiplayer(void);
		void lockForControl(void);
		void onAppResumed(void);
		void onAppSuspended(void);
		void onMojangConnectorStatus(MojangConnectionStatus);
		void onUpdatedClient(int,int,int,int);
		void optionUpdated(Options::Option const*,bool);
		void optionUpdated(Options::Option const*,float);
		void optionUpdated(Options::Option const*,int);
		void pauseGame(bool);
		void prepareLevel(std::string const&);
		void prepareLevel_tspawn(void *);
		void releaseMouse(void);
		void reloadOptions(void);
		void resetPlayer(Player *);
		void respawnPlayer(int);
		void respawnPlayer(void);
		void selectLevel(std::string const&,std::string const&,LevelSettings const&);
		void setIsCreativeMode(bool);
		void setLeaveGame(void);
		void setLevel(Level *,std::string const&,LocalPlayer *);
		void setScreen(Screen *);
		void setSize(int,int);
		void setTextboxText(std::string const&);
		void supportNonTouchScreen(void);
		void teardown(void);
		void tick(int,int);
		void tickInput(void);
		void transformResolution(int *,int *);
		void unlockControl(void);
		void update(void);
		void updateStatusUserAttributes(void);
		void useTouchscreen(void);
		void ~Minecraft();
		void ~Minecraft();
};
