#pragma once
class Item{
	public:
		Item(std::string const&,short);
		void getTierItem(void);
		void _textMatch(std::string const&,std::string const&,bool);
		void addBlockItems(void);
		void addCreativeItem(Block *,short);
		void addCreativeItem(Item*,short);
		void addCreativeItem(ItemInstance const&);
		void addCreativeItem(short,short);
		void appendFormattedHovertext(ItemInstance const&,Player const&,std::string &,bool);
		void buildDescriptionName(ItemInstance const&);
		void buildEffectDescriptionName(ItemInstance const&);
		void canBeDepleted(void);
		void canDestroyInCreative(void);
		void canDestroySpecial(Block const*);
		void destroySpeedBonus(ItemInstance const*);
		void dispense(BlockSource &,Container &,int,Vec3 const&,signed char);
		void getAnimationFrameFor(Mob &);
		void getAttackDamage(void);
		void getColor(ItemInstance const&);
		void getDestroySpeed(ItemInstance *,Block *);
		void getEnchantSlot(void);
		void getEnchantValue(void);
		void getIcon(int,int,bool);
		void getIconYOffset(void);
		void getInteractText(void);
		void getLevelDataForAuxValue(int);
		void getMaxDamage(void);
		void getMaxStackSize(ItemInstance const*);
		void getTextureItem(std::string const&);
		void getTextureUVCoordinateSet(std::string const&,int);
		void hurtEnemy(ItemInstance *,Mob *,Mob *);
		void init(Json::Value &);
		void initCreativeItems(void);
		void initItems(void);
		void interactEnemy(ItemInstance *,Mob *,Player *);
		void inventoryTick(ItemInstance &,Level &,Entity &,int,bool);
		void isArmor(void);
		void isComplex(void);
		void isDye(void);
		void isEmissive(int);
		void isFoil(ItemInstance const*);
		void isHandEquipped(void);
		void isLiquidClipItem(int);
		void isMirroredArt(void);
		void isStackedByData(void);
		void isThrowable(void);
		void isValidRepairItem(ItemInstance const&,ItemInstance const&);
		void lookupByName(std::string const&,bool);
		void mineBlock(ItemInstance *,BlockID,int,int,int,Mob *);
		void onCraftedBy(ItemInstance &,Level &,Player &);
		void readUserData(ItemInstance *,IDataInput &);
		void releaseUsing(ItemInstance *,Player *,int);
		void requiresInteract(void);
		void setCategory(CreativeItemCategory);
		void setHandEquipped(void);
		void setIcon(TextureUVCoordinateSet const&);
		void setIcon(std::string const&,int);
		void setMaxDamage(int);
		void setMaxStackSize(uchar);
		void setMaxUseDuration(int);
		void setStackedByData(bool);
		void setTextureAtlas(std::shared_ptr<TextureAtlas>);
		void setUseAnimation(UseAnimation);
		void teardownItems(void);
		void use(ItemInstance &,Player &);
		void useOn(ItemInstance *,Player *,int,int,int,signed char,float,float,float);
		void useTimeDepleted(ItemInstance *,Level *,Player *);
		void writeUserData(ItemInstance const*,IDataOutput &,bool);
		void ~Item();
		void ~Item();
};
