#pragma once
class LevelData{
	public:
		LevelData(CompoundTag const&);
		LevelData(LevelData&&);
		LevelData(LevelSettings const&,std::string const&,GeneratorType,BlockPos const*,bool,bool);
		LevelData(void);
		void clearLoadedPlayerTag(void);
		void createTag(void);
		void getCurrentTick(void);
		void getGameType(void);
		void getGenerator(void);
		void getGlobalPermissions(void);
		void getLastPlayed(void);
		void getLevelName(void);
		void getLightningLevel(void);
		void getLightningTime(void);
		void getLoadedPlayerTag(void);
		void getNetworkVersion(void);
		void getRainLevel(void);
		void getRainTime(void);
		void getSeed(void);
		void getSpawn(void);
		void getSpawnMobs(void);
		void getStopTime(void);
		void getStorageVersion(void);
		void getTagData(CompoundTag const&);
		void getTime(void);
		void getWorldCenter(void);
		void getWorldStartCount(void);
		void hasBeenLoadedInCreative(void);
		void incrementTick(void);
		void isEduLevel(void);
		void isLightning(void);
		void isRaining(void);
		void operator=(LevelData&&);
		void recordStartUp(void);
		void setCurrentTick(Tick &);
		void setGameType(GameType);
		void setGenerator(GeneratorType);
		void setGlobalPermissions(GlobalPermissionsLevel);
		void setHasBeenLoadedInCreative(void);
		void setIsEduLevel(bool);
		void setLevelName(std::string const&);
		void setLightningLevel(float);
		void setLightningTime(int);
		void setNetworkVersion(int);
		void setRainLevel(float);
		void setRainTime(int);
		void setSeed(uint);
		void setSpawn(BlockPos const&);
		void setSpawnMobs(bool);
		void setStopTime(int);
		void setStorageVersion(StorageVersion);
		void setTagData(CompoundTag &);
		void setTime(int);
		void v1_read(RakNet::BitStream &,StorageVersion);
		void ~LevelData();
};
