#pragma once
class Screen{
	public:
		void _buttonClicked(Button &);
		void _controllerDirectionChanged(int,StickDirection);
		void _controllerDirectionHeld(int,StickDirection);
		void _getCursorMoveThrottle(void);
		void _guiElementClicked(GuiElement &);
		void _handlePointerAction(int,int,bool);
		void _init(int,int);
		void _pointerPressed(int,int);
		void _pointerReleased(int,int);
		void _processControllerDirection(int);
		void _renderSlot(int,int,int,float);
		void _tabNext(void);
		void _tabPrev(void);
		void _updateTabButtonSelection(void);
		void checkForPointerEvent(void);
		void closeOnPlayerHurt(void);
		void confirmResult(bool,int);
		void controllerEvent(void);
		void getHeight(void);
		void getScreenName(void);
		void getWidth(void);
		void handleBackEvent(bool);
		void handleButtonPress(short);
		void handleButtonRelease(short);
		void handleCaretLocation(int);
		void handleCommandEvent(VoiceCommand const&);
		void handleDictationEvent(void);
		void handleDirection(DirectionId,float,float);
		void handleGazeGestureInput(short,float,float,float);
		void handleHoloInputModeChanged(HoloUIInputMode);
		void handleInputModeChanged(InputMode);
		void handleLicenseChanged(void);
		void handlePointerLocation(short,short);
		void handlePointerPressed(bool);
		void handleScrollWheel(float);
		void handleTextChar(std::string const&,bool);
		void init(void);
		void onFocusGained(void);
		void onFocusLost(void);
		void onInternetUpdate(void);
		void onMojangConnectorStatus(MojangConnectionStatus);
		void onSetKeyboardHeight(float);
		void onTextBoxUpdated(int);
		void render(ScreenContext &);
		void render(int,int,float);
		void renderBackground(int);
		void renderDirtBackground(void);
		void renderGameBehind(void);
		void renderMenuBackground(float);
		void renderOnSelectItemNameText(int,Font *,int);
		void renderProgressBar(float);
		void renderSlotText(ItemInstance const*,float,float,bool,bool,bool,bool);
		void renderToolBar(float,float,bool);
		void setAssociatedBlockPos(BlockPos const&);
		void setButtonIndex(int);
		void setSize(int,int);
		void setTextboxText(std::string const&);
		void setupPositions(void);
		void supppressedBySubWindow(void);
		void terminate(void);
		void tick(int,int);
		void tick(void);
		void toGUICoordinate(int,int,int &,int &);
		void updateEvents(void);
		void ~Screen();
		void ~Screen();
};
