#pragma once
namespace UIControl{
	class ControlResolutionInfo{
		public:
		void function<void ();
		void ControlResolutionInfo(void);
		UIControl(void);
		void _getComponentIndex(ushort);
		void _hasComponent(ushort);
		void function<void ();
		void function<void ();
		void _resolveControlNames(std::shared_ptr<UIControl> const&);
		void _resolvePostCreate(void);
		void addChild(std::shared_ptr<UIControl> &);
		void areAllAncestorsVisible(void);
		void broadcastEvent(VisualTree &,ScreenInputContext &,AnimationController &,UIComponent *,ScreenEvent);
		void containsPoint(glm::detail::tvec2<float> const&);
		void createPropertyBag(Json::Value const&);
		void getAllowClipping(void);
		void getChildren(void);
		void getClipOffset(void);
		void getClipsChildren(void);
		void getComponent<CarouselTextComponent>(void);
		void getComponent<CustomRenderComponent>(void);
		void getComponent<InputComponent>(void);
		void getComponent<LayoutComponent>(void);
		void getEnabled(void);
		void getFocus(void);
		void getHover(void);
		void getLayer(void);
		void getName(void);
		void getParent(void);
		void getPosition(void);
		void getPropertyBag(void);
		void getRenderOnlyWhenTopmost(void);
		void getSelected(void);
		void getSize(void);
		void getVisible(void);
		void getZOrder(void);
		void notifyChildAdded(void);
		void notifyChildRemoved(void);
		void removeParentByName(std::string const&);
		void setAllowClipping(bool);
		void setClipOffset(Vec2 const&);
		void setClipsChildren(bool);
		void setComponent<AnimationComponent>(std::unique_ptr<AnimationComponent,std::default_delete<AnimationComponent>>);
		void setComponent<ButtonComponent>(std::unique_ptr<ButtonComponent,std::default_delete<ButtonComponent>>);
		void setComponent<CarouselTextComponent>(std::unique_ptr<CarouselTextComponent,std::default_delete<CarouselTextComponent>>);
		void setComponent<CustomRenderComponent>(std::unique_ptr<CustomRenderComponent,std::default_delete<CustomRenderComponent>>);
		void setComponent<DataBindingComponent>(std::unique_ptr<DataBindingComponent,std::default_delete<DataBindingComponent>>);
		void setComponent<FactoryComponent>(std::unique_ptr<FactoryComponent,std::default_delete<FactoryComponent>>);
		void setComponent<GridComponent>(std::unique_ptr<GridComponent,std::default_delete<GridComponent>>);
		void setComponent<GridItemComponent>(std::unique_ptr<GridItemComponent,std::default_delete<GridItemComponent>>);
		void setComponent<InputComponent>(std::unique_ptr<InputComponent,std::default_delete<InputComponent>>);
		void setComponent<LayoutComponent>(std::unique_ptr<LayoutComponent,std::default_delete<LayoutComponent>>);
		void setComponent<ScreenComponent>(std::unique_ptr<ScreenComponent,std::default_delete<ScreenComponent>>);
		void setComponent<ScrollbarComponent>(std::unique_ptr<ScrollbarComponent,std::default_delete<ScrollbarComponent>>);
		void setComponent<SoundComponent>(std::unique_ptr<SoundComponent,std::default_delete<SoundComponent>>);
		void setComponent<SpriteComponent>(std::unique_ptr<SpriteComponent,std::default_delete<SpriteComponent>>);
		void setComponent<TabComponent>(std::unique_ptr<TabComponent,std::default_delete<TabComponent>>);
		void setComponent<TextComponent>(std::unique_ptr<TextComponent,std::default_delete<TextComponent>>);
		void setComponent<TextEditComponent>(std::unique_ptr<TextEditComponent,std::default_delete<TextEditComponent>>);
		void setComponent<ToggleComponent>(std::unique_ptr<ToggleComponent,std::default_delete<ToggleComponent>>);
		void setComponent<ToggleManagerComponent>(std::unique_ptr<ToggleManagerComponent,std::default_delete<ToggleManagerComponent>>);
		void setEnabled(bool);
		void setFocus(bool);
		void setHover(bool);
		void setLayer(int);
		void setName(std::string const&);
		void setPosition(glm::detail::tvec2<float> const&);
		void setPropertyBag(PropertyBag const&);
		void setRenderOnlyWhenTopmost(bool);
		void setSelected(bool);
		void setSize(glm::detail::tvec2<float> const&);
		void setVisible(bool);
		void setZOrder(int);
		void updateChildrenSize(void);
		void ~UIControl();
		void ~UIControl();
	}
};
