#pragma once
class UIControlFactory{
	public:
		UIControlFactory(UIDefRepository const&,Json::Value &,NameRegistry &,UISoundPlayer const&,Font *);
		void _addAnimToComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _createButton(UIResolvedDef const&);
		void _createCarouselLabel(UIResolvedDef const&);
		void _createCustom(UIResolvedDef const&);
		void _createEditBox(UIResolvedDef const&);
		void _createFactory(UIResolvedDef const&);
		void _createFromResolvedDef(UIResolvedDef const&);
		void _createGrid(UIResolvedDef const&);
		void _createGridItem(UIResolvedDef const&);
		void _createImage(UIResolvedDef const&);
		void _createInputPanel(UIResolvedDef const&);
		void _createLabel(UIResolvedDef const&);
		void _createPanel(UIResolvedDef const&);
		void _createScreen(UIResolvedDef const&);
		void _createScrollbar(UIResolvedDef const&);
		void _createScrollbarBox(UIResolvedDef const&);
		void _createTab(UIResolvedDef const&);
		void _createToggle(UIResolvedDef const&);
		void _populateAnimations(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateCarouselTextComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateControl(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateCustomRenderComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateDebugRendererComponent(UIResolvedDef const&,std::shared_ptr<UIControl>);
		void _populateFactoryComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateGridComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateGridItemComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateLayoutComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateScreenComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateScrollbarBoxComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateSoundComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateSpriteComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateTextComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _postCreate(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _postCreateGrid(std::shared_ptr<UIControl> &);
		void _resolveAnimatedProperty<Color>(UIResolvedDef const&,std::shared_ptr<UIControl> &,std::string const&);
		void _resolveAnimatedProperty<float>(UIResolvedDef const&,std::shared_ptr<UIControl> &,std::string const&);
		void tvec2<float>>(UIResolvedDef const&,std::shared_ptr<UIControl> &,std::string const&);
		void LayoutOffset>(UIResolvedDef const&,std::shared_ptr<UIControl> &,std::string const&);
		void addAnimRefToControl(std::shared_ptr<UIControl> &,std::string const&);
		void createControlTree(std::shared_ptr<UIControl> const&,std::shared_ptr<UIControl>&);
		void createControlTree(std::string const&);
		void ~UIControlFactory();
};
