#pragma once
class FillingContainer{
	public:
		void _addResource(ItemInstance const&);
		void _fixBackwardCompabilityItem(ItemInstance &);
		void _getEmptySlotsCount(int,int);
		void _getFreeSlot(void);
		void _getSlot(int);
		void _getSlot(int,int);
		void _getSlotWithRemainingSpace(ItemInstance const&);
		void _isCreative(void);
		void _linkEmptySlot(int);
		void _release(int);
		void add(ItemInstance &,bool);
		void canAdd(ItemInstance const&);
		void clearInventory(int);
		void clearSlot(int);
		void contains(ItemInstance &);
		void doDrop(ItemInstance &,bool);
		void dropAll(bool);
		void dropAll(int,int,bool);
		void dropSlot(int,bool,bool,bool);
		void getContainerSize(void);
		void getEmptySlotsCount(void);
		void getItem(int);
		void getLinked(int);
		void getLinkedSlot(int);
		void getLinkedSlots(void);
		void getLinkedSlotsCount(void);
		void getMaxStackSize(void);
		void getName(void);
		void getSlotWithItem(ItemInstance const&,bool,bool);
		void hasResource(int);
		void linkSlot(int,int);
		void load(ListTag const&);
		void removeItem(int,int);
		void removeResource(ItemInstance const&);
		void removeResource(ItemInstance const&,bool);
		void removeResource(int);
		void replace(std::vector<ItemInstance,std::allocator<ItemInstance>>,int);
		void replaceSlot(int,ItemInstance &);
		void save(void);
		void setItem(int,ItemInstance *);
		void startOpen(Player &);
		void stopOpen(Player &);
		void swapSlots(int,int);
		void unlinkSlot(int);
		void ~FillingContainer();
		void ~FillingContainer();
};
