#pragma once
class Gui{
	public:
		Gui(MinecraftClient &);
		void _buildFeedbackCircle(void);
		void _buildInnerFeedbackCircle(int,float);
		void _buildOuterFeedbackCircle(int,float,float);
		void _cubeSmoothStep(float,float,float);
		void _renderEduGui(void);
		void _renderPortalOverlay(float,int,int);
		void _renderPumpkin(int,int);
		void _renderSlot(int,int,int,float);
		void _renderVignette(float,int,int);
		void _tickItemDrop(void);
		void _touchEnabledOrHolographic(void);
		void _updateHudPositions(void);
		void addMessage(std::string const&,std::string const&,int,bool);
		void clearMessages(void);
		void displayChatMessage(std::string const&,std::string const&);
		void displayClientMessage(std::string const&);
		void displayLocalizableMessage(std::string const&,std::vector<std::string,std::allocator<std::string>> const&);
		void displaySystemMessage(std::string const&);
		void drawRectangleArea(Tessellator &,RectangleArea const*,int,int,float);
		void drawRectangleArea(Tessellator &,RectangleArea const*,int,int,float,float);
		void flashSlot(int);
		void floorAlignToScreenPixel(float);
		void forceMuteChat(void);
		void getGuiScale(void);
		void getInvGuiScale(void);
		void getMessageList(void);
		void getNumSlots(void);
		void getSlotIdAt(int,int);
		void getSlotPos(int,int &,int &);
		void handleClick(void);
		void inventoryUpdated(void);
		void isInside(int,int);
		void isMuteChat(void);
		void itemCountItoa(char *,int);
		void onAppSuspended(void);
		void onConfigChanged(Config const&);
		void onLevelGenerated(void);
		void onMobEffectsChanged(MobEffectsLayout const&);
		void postError(int);
		void render(float,bool,int,int);
		void renderBubbles(void);
		void renderCursor(float,float);
		void renderExperience(void);
		void renderHearts(void);
		void renderHunger(void);
		void renderOnSelectItemNameText(int,Font *,int);
		void renderProgressIndicator(int,int,float);
		void renderSleepAnimation(int,int);
		void renderSlotText(ItemInstance const*,float,float,bool,bool,bool,bool);
		void renderToolBar(float,float,bool);
		void setGuiScale(float);
		void setIsChatting(bool);
		void setNowPlaying(std::string const&);
		void setShowProgress(bool);
		void setTouchToolbarArea(RectangleArea const&);
		void showPopupNotice(std::string const&,std::string const&);
		void showTipMessage(std::string const&);
		void tick(void);
		void toggleMuteChat(void);
		void updatePointerLocation(short,short);
		void wasToolbarClicked(void);
		void ~Gui();
		void ~Gui();
};
