#pragma once
class ScrollingPane{
	public:
		ScrollingPane(int,IntRectangle const&,IntRectangle const&,int,int,float,IntRectangle const&);
		void UpdateHighlightItem(float,float);
		void _getAdditionalScrollBarWidth(void);
		void _handleMouseInput(float,bool);
		void _onSelect(int);
		void addDeltaPos(float,float,float,int);
		void addFlag(int);
		void adjustContentSize(void);
		void beginTracking(float,float,int);
		void calculateAndSetCurrentMouseScrollT(void);
		void contentOffset(void);
		void didEndDecelerating(void);
		void didEndDragging(void);
		void getAdditionalScrollBarWidth(MinecraftClient *);
		void getAdditionalScrollBarWidth(void);
		void getColumns(void);
		void getContentOffset(void);
		void getGridItemFor_slow(int,ScrollingPane::GridItem &);
		void getItemForPos(float,float,bool);
		void getNumItems(void);
		void getRows(void);
		void getScrollT(void);
		void getSelectedItemId(void);
		void getVerticleScrollBar(void);
		void handleMouseInput(float);
		void handleUserInput(bool);
		void hideScrollIndicators(void);
		void onHoldItem(void);
		void onNavigate(int);
		void onSelect(int,bool);
		void queryHoldTime(int *,int *);
		void recalculateRows(int);
		void refreshItems(void);
		void refreshPane(void);
		void render(int,int,float,MinecraftClient *);
		void renderBatch(std::vector<ScrollingPane::GridItem,std::allocator<ScrollingPane::GridItem>> &,float,float,float);
		void renderItem(ScrollingPane::GridItem &,float);
		void resetHoldTime(void);
		void scrollDownBy(float);
		void scrollUpBy(float);
		void setContentOffset(Vec3);
		void setContentOffset(float,float);
		void setContentOffsetWithAnimation(Vec3,bool);
		void setNumItems(int);
		void setRenderSelected(bool);
		void setScrollT(float);
		void setSelected(int,bool);
		void shouldRenderSelected(void);
		void shouldUseMouseScrollbarLayout(MinecraftClient *);
		void snapContentOffsetToBounds(bool);
		void startDecelerationAnimation(bool);
		void stepThroughDecelerationAnimation(bool);
		void stopDecelerationAnimation(void);
		void thereAreMoreItemsToDisplay(int,int,int);
		void thereAreMoreItemsToDisplay(void);
		void tick(void);
		void touchesBegan(float,float,int);
		void touchesCancelled(float,float,int);
		void touchesEnded(float,float,int);
		void touchesMoved(float,float,int);
		void translate(float,float);
		void updateHorizontalScrollIndicator(void);
		void updateScrollBarScale(int,int,int,int);
		void updateScrollBoxSize(float);
		void updateScrollFade(ScrollBar &);
		void updateVerticalScrollIndicator(void);
		void willBeginDecelerating(void);
		void willBeginDragging(void);
		void ~ScrollingPane();
		void ~ScrollingPane();
};
