#pragma once
class AABB{
	public:
		AABB(Vec3 const&,Vec3 const&);
		AABB(Vec3 const&,Vec3 const&);
		AABB(Vec3 const&,float);
		AABB(Vec3 const&,float);
		AABB(float,float,float,float,float,float);
		AABB(float,float,float,float,float,float);
		AABB(void);
		AABB(void);
		void _clipAxisCollide(AABB const&,float,int,bool);
		void axisInside(AABB const&,Vec3);
		void axisInside(AABB const&,Vec3);
		void centerAt(Vec3 const&);
		void centerAt(Vec3 const&);
		void clip(Vec3 const&,Vec3 const&);
		void clip(Vec3 const&,Vec3 const&);
		void clipCollide(AABB const&,Vec3 const&,bool);
		void clipCollide(AABB const&,Vec3 const&,bool);
		void clipXCollide(AABB const&,float,bool);
		void clipXCollide(AABB const&,float,bool);
		void clipYCollide(AABB const&,float,bool);
		void clipYCollide(AABB const&,float,bool);
		void clipZCollide(AABB const&,float,bool);
		void clipZCollide(AABB const&,float,bool);
		void cloneMove(Vec3 const&);
		void cloneMove(Vec3 const&);
		void contains(Vec3 const&);
		void contains(Vec3 const&);
		void expand(Vec3 const&);
		void expand(Vec3 const&);
		void expanded(Vec3 const&);
		void expanded(Vec3 const&);
		void flooredCeiledCopy(void);
		void flooredCeiledCopy(void);
		void flooredCopy(float,float);
		void flooredCopy(float,float);
		void fromPoints(Vec3 const&,Vec3 const&);
		void fromPoints(Vec3 const&,Vec3 const&);
		void getBounds(void);
		void getBounds(void);
		void getCenter(void);
		void getCenter(void);
		void getSize(void);
		void getSmallestAxisOut(AABB const&);
		void grow(Vec3 const&);
		void grow(Vec3 const&);
		void intersectSegment(Vec3 const&,Vec3 const&,Vec3&,Vec3&);
		void intersectSegment(Vec3 const&,Vec3 const&,Vec3&,Vec3&);
		void intersects(AABB const&);
		void intersects(AABB const&);
		void intersects(Vec3 const&,Vec3 const&);
		void intersects(Vec3 const&,Vec3 const&);
		void intersectsInner(AABB const&);
		void isEmpty(void);
		void isEmpty(void);
		void isNan(void);
		void merge(AABB const&);
		void merge(AABB const&);
		void move(Vec3 const&);
		void move(Vec3 const&);
		void move(float,float,float);
		void move(float,float,float);
		void resize(Vec3 const&);
		void resize(Vec3 const&);
		void set(AABB const&);
		void set(AABB const&);
		void set(Vec3 const&,Vec3 const&);
		void set(Vec3 const&,Vec3 const&);
		void set(float,float,float,float,float,float);
		void set(float,float,float,float,float,float);
		void shrink(Vec3 const&);
		void shrink(Vec3 const&);
		void toString(void);
		void translated(Vec3 const&);
		void translated(Vec3 const&);
};
