#pragma once
class AbstractScreen{
	public:
		void _handleDirtyVisualTree(bool);
		void _handleDirtyVisualTree(bool);
		void absorbsInput(void);
		void applyInput(float);
		void applyInput(float);
		void drawRectangleArea(Tessellator &,RectangleArea const&,int,int,float,float);
		void drawRectangleArea(Tessellator &,RectangleArea const&,int,int,float,float);
		void getEyeRenderingMode(void);
		void getEyeRenderingMode(void);
		void getFocusedControl(void);
		void getFocusedControl(void);
		void getNumberOfRenderPasses(void);
		void getNumberOfRenderPasses(void);
		void getRenderingAABB(void);
		void getRenderingAABB(void);
		void getSendTelemetry(void);
		void getSendTelemetry(void);
		void getTelemetryProperty(std::string &,std::string &);
		void getTelemetryProperty(std::string &,std::string &);
		void ignoreAsTop(void);
		void ignoreAsTop(void);
		void isModal(void);
		void isModal(void);
		void isPauseScreen(void);
		void isPauseScreen(void);
		void isShowingMenu(void);
		void isShowingMenu(void);
		void isWorldViewer(void);
		void isWorldViewer(void);
		void lowFreqRendering(void);
		void lowFreqRendering(void);
		void onGameEventNotification(ui::GameEventNotification);
		void onGameEventNotification(ui::GameEventNotification);
		void renderOnlyWhenTopMost(void);
		void renderOnlyWhenTopMost(void);
		void screenDrawsLast(void);
		void screenDrawsLast(void);
		void screenIsNotFlushable(void);
		void screenIsNotFlushable(void);
		void setupAndRender(UIScreenContext &);
		void setupAndRender(UIScreenContext &);
		void shouldStealMouse(void);
		void shouldStealMouse(void);
		void ~AbstractScreen();
		void ~AbstractScreen();
		void ~AbstractScreen();
		void ~AbstractScreen();
};
