#pragma once
class Animal{
	public:
		Animal(BlockSource &);
		Animal(BlockSource &);
		void _clientLoveCheck(void);
		void _getWalkTargetValue(BlockPos const&);
		void _getWalkTargetValue(BlockPos const&);
		void _randomHeartPos(void);
		void _randomHeartPos(void);
		void addAdditionalSaveData(CompoundTag &);
		void addAdditionalSaveData(CompoundTag &);
		void aiStep(void);
		void aiStep(void);
		void canAddRider(Entity &);
		void canAddRider(Entity &);
		void canInteractWith(Player &);
		void canInteractWith(Player &);
		void canMate(Animal const&);
		void canMate(Animal const&);
		void getAmbientSoundInterval(void);
		void getAmbientSoundInterval(void);
		void getExperienceReward(void);
		void getExperienceReward(void);
		void getInteractText(Player &);
		void getInteractText(Player &);
		void getLoveCause(void);
		void getLoveCause(void);
		void hurt(EntityDamageSource const&,int);
		void hurt(EntityDamageSource const&,int);
		void interactWithPlayer(Player &);
		void interactWithPlayer(Player &);
		void isFood(ItemInstance const&);
		void isFood(ItemInstance const&);
		void isInLove(void);
		void isInLove(void);
		void isLeashableType(void);
		void isLeashableType(void);
		void postProcessOffspring(Animal&,Animal&);
		void postProcessOffspring(Animal&,Animal&);
		void readAdditionalSaveData(CompoundTag const&);
		void readAdditionalSaveData(CompoundTag const&);
		void resetLove(void);
		void resetLove(void);
		void setInLove(Player const*);
		void setInLove(Player const*);
		void ~Animal();
		void ~Animal();
};
