#pragma once
class Arrow{
	public:
		Arrow(BlockSource &);
		Arrow(BlockSource &);
		Arrow(BlockSource &,Vec3 const&);
		Arrow(BlockSource &,Vec3 const&);
		Arrow(Mob &,Mob &,float,float,ItemInstance const*);
		Arrow(Mob &,Mob &,float,float,ItemInstance const*);
		Arrow(Mob &,float,ItemInstance const*);
		Arrow(Mob &,float,ItemInstance const*);
		void _defineEntityData(void);
		void _defineEntityData(void);
		void _init(Mob const*,ItemInstance const*);
		void _init(Mob const*,ItemInstance const*);
		void _readItemEnchants(ItemInstance const&);
		void addAdditionalSaveData(CompoundTag &);
		void addAdditionalSaveData(CompoundTag &);
		void addMobEffect(MobEffectInstance);
		void addMobEffect(MobEffectInstance);
		void applyHit(HitResult &);
		void applyHit(HitResult &);
		void applyParticleColor(Particle *);
		void applyParticleColor(Particle *);
		void getAuxValue(void);
		void getAuxValue(void);
		void getBaseDamage(void);
		void getBaseDamage(void);
		void getEffectCount(void);
		void getEffects(void);
		void getEnchantFlame(void);
		void getEnchantInfinity(void);
		void getEnchantPower(void);
		void getEnchantPunch(void);
		void getEntityTypeId(void);
		void getEntityTypeId(void);
		void getPickupItem(void);
		void getPickupItem(void);
		void getShadowHeightOffs(void);
		void getShadowHeightOffs(void);
		void getShadowRadius(void);
		void getShadowRadius(void);
		void getShakeTime(void);
		void getShakeTime(void);
		void getSourceUniqueID(void);
		void getSourceUniqueID(void);
		void isCritical(void);
		void lerpMotion(Vec3 const&);
		void lerpMotion(Vec3 const&);
		void normalTick(void);
		void normalTick(void);
		void playerTouch(Player &);
		void playerTouch(Player &);
		void readAdditionalSaveData(CompoundTag const&);
		void readAdditionalSaveData(CompoundTag const&);
		void setAuxValue(int);
		void setAuxValue(int);
		void setBaseDamage(float);
		void setBaseDamage(float);
		void setCritical(bool);
		void setCritical(bool);
		void setEnchantFlame(int);
		void setEnchantInfinity(int);
		void setEnchantPower(int);
		void setEnchantPunch(int);
		void setEnchantPunch(int);
		void shoot(Vec3 const&,float,float,Vec3 const&);
		void shoot(Vec3 const&,float,float,Vec3 const&);
		void ~Arrow();
		void ~Arrow();
		void ~Arrow();
		void ~Arrow();
};
