#pragma once
class AttributeInstance{
	public:
		AttributeInstance(AttributeInstance const&);
		AttributeInstance(AttributeInstance const&);
		AttributeInstance(BaseAttributeMap *,Attribute const*);
		AttributeInstance(BaseAttributeMap *,Attribute const*);
		AttributeInstance(void);
		AttributeInstance(void);
		void _calculateValue(AttributeBuff const&);
		void _calculateValue(AttributeBuff const&);
		void _calculateValue(void);
		void _calculateValue(void);
		void _getAppliedModifiers(int);
		void _sanitizeValue(float);
		void _setDirty(void);
		void addBuff(AttributeBuff const&);
		void addBuff(AttributeBuff const&);
		void addBuff(std::shared_ptr<AttributeBuff>);
		void addModifier(AttributeModifier const&);
		void addModifier(AttributeModifier const&);
		void addModifier(std::shared_ptr<AttributeModifier>);
		void addModifier(std::shared_ptr<AttributeModifier>);
		void addModifiers(std::vector<std::shared_ptr<AttributeModifier>,std::allocator<std::shared_ptr<AttributeModifier>>> *);
		void getAttribute(void);
		void getAttribute(void);
		void getBuffs(void);
		void getBuffs(void);
		void getCurrentValue(void);
		void getCurrentValue(void);
		void getDefaultValue(int);
		void getDefaultValue(int);
		void getHandle(void);
		void getHandle(void);
		void getListeners(void);
		void getListeners(void);
		void getMaxValue(void);
		void getMaxValue(void);
		void getMinValue(void);
		void getMinValue(void);
		void getModifier(mce::UUID const&);
		void getModifiers(int);
		void getModifiers(int);
		void getModifiers(std::string const&);
		void getModifiers(std::string const&);
		void getModifiers(void);
		void getModifiers(void);
		void hasModifier(AttributeModifier const&);
		void hasModifier(std::shared_ptr<AttributeModifier>);
		void hasModifier(std::shared_ptr<AttributeModifier>);
		void hasTemporalBuffs(void);
		void hasTemporalBuffs(void);
		void notify(long long);
		void notify(long long);
		void registerListener(AttributeInstance const&);
		void registerListener(AttributeInstance const&);
		void removeBuff(AttributeBuff const&);
		void removeBuff(std::shared_ptr<AttributeBuff>);
		void removeBuff(std::shared_ptr<AttributeBuff>);
		void removeBuffs(void);
		void removeBuffs(void);
		void removeModifier(AttributeModifier const&);
		void removeModifier(AttributeModifier const&);
		void removeModifier(mce::UUID const&);
		void removeModifier(mce::UUID const&);
		void removeModifier(std::shared_ptr<AttributeModifier>);
		void removeModifier(std::shared_ptr<AttributeModifier>);
		void removeModifiers(std::string const&);
		void removeModifiers(void);
		void resetToDefaultValue(int);
		void resetToDefaultValue(int);
		void resetToMaxValue(void);
		void resetToMaxValue(void);
		void resetToMinValue(void);
		void resetToMinValue(void);
		void serializationSetRange(float,float,float);
		void serializationSetRange(float,float,float);
		void serializationSetValue(float,int);
		void serializationSetValue(float,int);
		void setDefaultValue(float,int);
		void setDefaultValue(float,int);
		void setDelegate(std::shared_ptr<AttributeInstanceDelegate>);
		void setDelegate(std::shared_ptr<AttributeInstanceDelegate>);
		void setMaxValue(float);
		void setMaxValue(float);
		void setMinValue(float);
		void setRange(float,float,float);
		void setRange(float,float,float);
		void tick(void);
		void tick(void);
		void ~AttributeInstance();
		void ~AttributeInstance();
		void ~AttributeInstance();
		void ~AttributeInstance();
		void ~AttributeInstance();
};
