#pragma once
class BackgroundWorker{
	public:
		BackgroundWorker(std::string const&,bool);
		BackgroundWorker(std::string const&,bool);
		void Job(BackgroundWorker::Job&&);
		void Job(BackgroundWorker::Job&&);
		void function<bool ();
		void function<bool ();
		void Job(void);
		void clear(void);
		void clear(void);
		void explicitMove(BackgroundWorker::Job&);
		void getCallback(void);
		void getFuture(void);
		void operator bool(void);
		void operator<(BackgroundWorker::Job const&);
		void operator=(BackgroundWorker::Job&&);
		void operator=(BackgroundWorker::Job&&);
		void run(void);
		void ~Job();
		void ~Job();
		void _processCallbacks(void);
		void _processNextCallback(void);
		void _processNextCallback(void);
		void _processNextCoroutine(void);
		void _queue(BackgroundWorker::Job &);
		void _queue(BackgroundWorker::Job &);
		void _resetData(void);
		void _resetData(void);
		void _start(void);
		void _tryPop(void);
		void _tryPop(void);
		void _tryPopLocal(BackgroundWorker::Job &,bool);
		void _tryPopReal(BackgroundWorker::Job &);
		void _tryPopReal(BackgroundWorker::Job &);
		void _tryStealWork(BackgroundWorker::Job &);
		void _tryStealWork(BackgroundWorker::Job &);
		void _workerThread(void);
		void flush(void);
		void flush(void);
		void getAverageJobsPerFrame(void);
		void getName(void);
		void getName(void);
		void isIdle(void);
		void isPaused(void);
		void notifyCoworkers(std::vector<BackgroundWorker*,std::allocator<BackgroundWorker*>> const&);
		void notifyCoworkers(std::vector<BackgroundWorker*,std::allocator<BackgroundWorker*>> const&);
		void pause(void);
		void pause(void);
		void processNext(void);
		void processNext(void);
		void function<bool ();
		void function<bool ();
		void resume(void);
		void resume(void);
		void stop(void);
		void stop(void);
		void sync(void);
		void sync(void);
		void ~BackgroundWorker();
};
