#pragma once
class ButtonBlock{
	public:
		ButtonBlock(std::string const&,int,bool);
		ButtonBlock(std::string const&,int,bool);
		void _buttonDepressed(BlockSource &,FullBlock,Vec3 const&);
		void _buttonDepressed(BlockSource &,FullBlock,Vec3 const&);
		void _buttonPressed(BlockSource &,FullBlock,Vec3 const&);
		void _buttonPressed(BlockSource &,FullBlock,Vec3 const&);
		void _checkCanSurvive(BlockSource &,BlockPos const&);
		void _checkPressed(BlockSource &,BlockPos const&);
		void _checkPressed(BlockSource &,BlockPos const&);
		void _getShape(AABB &,uchar,bool);
		void _getShape(AABB &,uchar,bool);
		void asItemInstance(BlockSource &,BlockPos const&,int);
		void asItemInstance(BlockSource &,BlockPos const&,int);
		void canAttachTo(BlockSource &,BlockPos const&,signed char);
		void canAttachTo(BlockSource &,BlockPos const&,signed char);
		void entityInside(BlockSource &,BlockPos const&,Entity &);
		void entityInside(BlockSource &,BlockPos const&,Entity &);
		void getCollisionShape(AABB &,BlockSource &,BlockPos const&,Entity *);
		void getCollisionShape(AABB &,BlockSource &,BlockPos const&,Entity *);
		void getPlacementDataValue(Mob &,BlockPos const&,signed char,Vec3 const&,int);
		void getPlacementDataValue(Mob &,BlockPos const&,signed char,Vec3 const&,int);
		void getResource(Random &,int,int);
		void getResource(Random &,int,int);
		void getResourceCount(Random &,int,int);
		void getResourceCount(Random &,int,int);
		void getSpawnResourcesAuxValue(uchar);
		void getSpawnResourcesAuxValue(uchar);
		void getTickDelay(void);
		void getVariant(int);
		void getVariant(int);
		void getVisualShape(uchar,AABB &,bool);
		void getVisualShape(uchar,AABB &,bool);
		void isAttachedTo(BlockSource &,BlockPos const&,BlockPos&);
		void isAttachedTo(BlockSource &,BlockPos const&,BlockPos&);
		void isButtonPressed(int);
		void isInteractiveBlock(void);
		void isInteractiveBlock(void);
		void isRedstoneBlock(void);
		void isRedstoneBlock(void);
		void mayPlace(BlockSource &,BlockPos const&);
		void mayPlace(BlockSource &,BlockPos const&);
		void mayPlace(BlockSource &,BlockPos const&,signed char);
		void mayPlace(BlockSource &,BlockPos const&,signed char);
		void neighborChanged(BlockSource &,BlockPos const&,BlockPos const&);
		void neighborChanged(BlockSource &,BlockPos const&,BlockPos const&);
		void onLoaded(BlockSource &,BlockPos const&);
		void onLoaded(BlockSource &,BlockPos const&);
		void onPlace(BlockSource &,BlockPos const&);
		void onPlace(BlockSource &,BlockPos const&);
		void onRedstoneUpdate(BlockSource &,BlockPos const&,int,bool);
		void onRedstoneUpdate(BlockSource &,BlockPos const&,int,bool);
		void tick(BlockSource &,BlockPos const&,Random &);
		void tick(BlockSource &,BlockPos const&,Random &);
		void use(Player &,BlockPos const&);
		void use(Player &,BlockPos const&);
		void ~ButtonBlock();
		void ~ButtonBlock();
};
