#pragma once
class CauldronBlockEntity{
	public:
		CauldronBlockEntity(BlockPos const&);
		CauldronBlockEntity(BlockPos const&);
		void getColor(void);
		void getColor(void);
		void getContainerSize(void);
		void getContainerSize(void);
		void getCustomColor(void);
		void getCustomColor(void);
		void getCustomName(void);
		void getItem(int);
		void getItem(int);
		void getMaxStackSize(void);
		void getMaxStackSize(void);
		void getMixDyeColor(void);
		void getMixDyeColor(void);
		void getName(void);
		void getName(void);
		void getPotionColor(void);
		void getPotionColor(void);
		void getUpdatePacket(BlockSource &);
		void getUpdatePacket(BlockSource &);
		void isFinished(void);
		void isFinished(void);
		void isSlotEmpty(int);
		void load(CompoundTag const&);
		void load(CompoundTag const&);
		void mixDyes(void);
		void mixDyes(void);
		void onChanged(BlockSource &);
		void onChanged(BlockSource &);
		void onUpdatePacket(CompoundTag &);
		void onUpdatePacket(CompoundTag &);
		void removeItem(int,int);
		void removeItem(int,int);
		void save(CompoundTag &);
		void save(CompoundTag &);
		void setCustomColor(Color const&);
		void setCustomColor(Color const&);
		void setCustomName(std::string &);
		void setItem(int,ItemInstance *);
		void setItem(int,ItemInstance *);
		void startOpen(Player &);
		void startOpen(Player &);
		void stopOpen(Player &);
		void stopOpen(Player &);
		void tick(BlockSource &);
		void tick(BlockSource &);
		void ~CauldronBlockEntity();
		void ~CauldronBlockEntity();
		void ~CauldronBlockEntity();
		void ~CauldronBlockEntity();
};
