#pragma once
class ChestBlock{
	public:
		ChestBlock(std::string const&,int,ChestBlock::ChestType);
		ChestBlock(std::string const&,int,ChestBlock::ChestType);
		void canBeSilkTouched(void);
		void canBeSilkTouched(void);
		void detachesOnPistonMove(BlockSource &,BlockPos const&);
		void detachesOnPistonMove(BlockSource &,BlockPos const&);
		void getComparatorSignal(BlockSource &,BlockPos const&,signed char,int);
		void getComparatorSignal(BlockSource &,BlockPos const&,signed char,int);
		void getMappedFace(signed char,int);
		void getMappedFace(signed char,int);
		void getPlacementDataValue(Mob &,BlockPos const&,signed char,Vec3 const&,int);
		void getPlacementDataValue(Mob &,BlockPos const&,signed char,Vec3 const&,int);
		void getSecondPart(BlockSource &,BlockPos const&,BlockPos&);
		void getSecondPart(BlockSource &,BlockPos const&,BlockPos&);
		void hasComparatorSignal(void);
		void hasComparatorSignal(void);
		void init(void);
		void init(void);
		void isContainerBlock(void);
		void isContainerBlock(void);
		void isRedstoneBlock(void);
		void isRedstoneBlock(void);
		void onLoaded(BlockSource &,BlockPos const&);
		void onLoaded(BlockSource &,BlockPos const&);
		void onMove(BlockSource &,BlockPos const&,BlockPos const&);
		void onMove(BlockSource &,BlockPos const&,BlockPos const&);
		void onPlace(BlockSource &,BlockPos const&);
		void onPlace(BlockSource &,BlockPos const&);
		void onRemove(BlockSource &,BlockPos const&);
		void onRemove(BlockSource &,BlockPos const&);
		void updateSignalStrength(BlockSource &,BlockPos const&,int);
		void updateSignalStrength(BlockSource &,BlockPos const&,int);
		void use(Player &,BlockPos const&);
		void use(Player &,BlockPos const&);
		void ~ChestBlock();
		void ~ChestBlock();
};
