#pragma once
class Creeper{
	public:
		Creeper(BlockSource &);
		Creeper(BlockSource &);
		void _explodeCreeper(void);
		void _getDeathSound(void);
		void _getDeathSound(void);
		void _getHurtSound(void);
		void _getHurtSound(void);
		void _getOldSwell(void);
		void _getSwell(void);
		void _ignite(void);
		void _isIgnited(void);
		void _isIgnited(void);
		void _setOldSwell(int);
		void _setPowered(bool);
		void _setSwell(int);
		void _setSwellDir(int);
		void _setSwellDir(int);
		void addAdditionalSaveData(CompoundTag &);
		void addAdditionalSaveData(CompoundTag &);
		void calcExplosionPos(void);
		void calcExplosionPos(void);
		void die(EntityDamageSource const&);
		void die(EntityDamageSource const&);
		void getDeathLoot(void);
		void getDeathLoot(void);
		void getEntityTypeId(void);
		void getEntityTypeId(void);
		void getSwellDir(void);
		void getSwellDir(void);
		void getSwelling(float);
		void getSwelling(float);
		void handleEntityEvent(EntityEvent,int);
		void handleEntityEvent(EntityEvent,int);
		void interactWithPlayer(Player &);
		void interactWithPlayer(Player &);
		void isPowered(void);
		void isPowered(void);
		void normalTick(void);
		void normalTick(void);
		void onLightningHit(void);
		void onLightningHit(void);
		void readAdditionalSaveData(CompoundTag const&);
		void readAdditionalSaveData(CompoundTag const&);
		void registerAttributes(void);
		void registerAttributes(void);
		void useNewAi(void);
		void useNewAi(void);
		void ~Creeper();
		void ~Creeper();
};
