#pragma once
namespace EnchantingScreen{
	class ButtonNode{
		public:
		void ButtonNode(Button &);
		void Traverse(StickDirection);
		void linkHorizontal(EnchantingScreen::ButtonNode&,EnchantingScreen::ButtonNode&);
		void linkVertical(EnchantingScreen::ButtonNode&,EnchantingScreen::ButtonNode&);
		EnchantingScreen(MinecraftClient &,Player &,BlockPos const&);
		EnchantingScreen(MinecraftClient &,Player &,BlockPos const&);
		void _buttonClicked(Button &);
		void _buttonClicked(Button &);
		void _controllerDirectionChanged(int,StickDirection);
		void _controllerDirectionChanged(int,StickDirection);
		void _controllerDirectionHeld(int,StickDirection);
		void _controllerDirectionHeld(int,StickDirection);
		void _displayEnchantResults(Tessellator &);
		void _displayEnchantResults(Tessellator &);
		void _drawBorder(int,int,int,int,int,Color const&);
		void _drawSlotItemAt(Tessellator &,ItemInstance const*,Button const&);
		void _drawSlotItemAt(Tessellator &,ItemInstance const*,Button const&);
		void _entityCheck(void);
		void _entityCheck(void);
		void _getLapisCount(void);
		void _getLapisCount(void);
		void _getTableEntity(void);
		void _handleAddItem(ItemInstance const&,int);
		void _handleAddItem(ItemInstance const&,int);
		void _handleBulkItemMovementRequest(Touch::InventoryPane &);
		void _handleBulkItemMovementRequest(Touch::InventoryPane &);
		void _handleRenderPane(Touch::InventoryPane &,Tessellator &,int,int,float);
		void _isLapis(ItemInstance const&);
		void _moveOver(ItemInstance const&,int);
		void _moveOver(ItemInstance const&,int);
		void _renderBook(Tessellator &,int,int,float,bool);
		void _renderBook(Tessellator &,int,int,float,bool);
		void _renderEnchantButton(void);
		void _renderEnchantButton(void);
		void _renderPlayerLevel(int);
		void _renderPlayerLevel(int);
		void _renderSelectionBox(Tessellator &);
		void _renderSelectionBox(Tessellator &);
		void _selectInDirection(StickDirection);
		void _selectingEnchantOption(void);
		void _sendSlotPacket(int,ItemInstance const&);
		void _sendSlotPacket(int,ItemInstance const&);
		void _setupInventoryPane(void);
		void _setupInventoryPane(void);
		void _takeAndClearSlot(int);
		void _takeAndClearSlot(int);
		void _tickBook(void);
		void _tickBook(void);
		void _updateItems(void);
		void _updateItems(void);
		void addItem(Touch::InventoryPane &,int);
		void addItem(Touch::InventoryPane &,int);
		void getItems(Touch::InventoryPane const&);
		void getItems(Touch::InventoryPane const&);
		void getScreenName(void);
		void getScreenName(void);
		void handleBackEvent(bool);
		void handleBackEvent(bool);
		void handleButtonPress(short);
		void handleButtonPress(short);
		void handleButtonRelease(short);
		void handleButtonRelease(short);
		void init(void);
		void init(void);
		void isAllowed(int);
		void isAllowed(int);
		void render(int,int,float);
		void render(int,int,float);
		void setupPositions(void);
		void setupPositions(void);
		void tick(void);
		void tick(void);
		void ~EnchantingScreen();
		void ~EnchantingScreen();
		void ~EnchantingScreen();
		void ~EnchantingScreen();
	}
};
