#pragma once
class EntityRenderDispatcher{
	public:
		EntityRenderDispatcher(MinecraftClient &);
		EntityRenderDispatcher(MinecraftClient &);
		void createInstance(MinecraftClient &);
		void createInstance(MinecraftClient &);
		void destroyInstance(void);
		void destroyInstance(void);
		void getCameraEntity(void);
		void getCameraEntity(void);
		void getCameraRot(void);
		void getCameraRot(void);
		void getCrosshairPickEntity(void);
		void getFont(void);
		void getFont(void);
		void getInstance(void);
		void getInstance(void);
		void getItemInHandRenderer(void);
		void getItemInHandRenderer(void);
		void getMinecraftClient(void);
		void getMinecraftClient(void);
		void getOffset(void);
		void getOffset(void);
		void getRenderer(Entity &);
		void getRenderer(Entity &);
		void getRenderer(EntityRendererId);
		void getRenderer(EntityRendererId);
		void onActiveResourcePackChanged(void);
		void onActiveResourcePackChanged(void);
		void onAppSuspended(void);
		void onAppSuspended(void);
		void prepare(Level *,Font *,Entity *,Entity *,Options *,float);
		void prepare(Level *,Font *,Entity *,Entity *,Options *,float);
		void render(Entity &,Vec3 const&,float,float);
		void render(Entity &,Vec3 const&,float,float);
		void render(Entity &,float);
		void render(Entity &,float);
		void renderDebug(Entity &);
		void setCameraTargetPos(Vec3 const&);
		void setCameraTargetPos(Vec3 const&);
		void setLevel(Level *);
		void setLevel(Level *);
		void updateEntityRenderers(void);
		void updateEntityRenderers(void);
		void ~EntityRenderDispatcher();
		void ~EntityRenderDispatcher();
		void ~EntityRenderDispatcher();
		void ~EntityRenderDispatcher();
};
