#pragma once
class FurnaceBlockEntity{
	public:
		FurnaceBlockEntity(BlockPos const&);
		FurnaceBlockEntity(BlockPos const&);
		void _getPositionOfNeighbor(int);
		void burn(void);
		void burn(void);
		void canBurn(void);
		void canBurn(void);
		void canPullOutItem(int,int,ItemInstance *);
		void canPullOutItem(int,int,ItemInstance *);
		void canPushInItem(int,int,ItemInstance *);
		void canPushInItem(int,int,ItemInstance *);
		void checkForSmeltEverythingAchievement(BlockSource &);
		void checkForSmeltEverythingAchievement(BlockSource &);
		void getBurnDuration(ItemInstance const*);
		void getBurnDuration(ItemInstance const*);
		void getBurnProgress(int);
		void getBurnProgress(int);
		void getContainerSize(void);
		void getContainerSize(void);
		void getItem(int);
		void getItem(int);
		void getLastFuelSource(void);
		void getLastFuelSource(void);
		void getLitDuration(void);
		void getLitDuration(void);
		void getLitProgress(int);
		void getLitProgress(int);
		void getLitTime(void);
		void getLitTime(void);
		void getMaxStackSize(void);
		void getMaxStackSize(void);
		void getName(void);
		void getName(void);
		void getTickCount(void);
		void getTickCount(void);
		void isFinished(void);
		void isFinished(void);
		void isFuel(ItemInstance const*);
		void isFuel(ItemInstance const*);
		void isIngredient(ItemInstance const*);
		void isLit(void);
		void isSlotDirty(int);
		void isSlotDirty(int);
		void isSlotEmpty(int);
		void isSlotEmpty(int);
		void load(CompoundTag const&);
		void load(CompoundTag const&);
		void onMove(void);
		void onMove(void);
		void onNeighborChanged(BlockSource &,BlockPos const&);
		void onNeighborChanged(BlockSource &,BlockPos const&);
		void removeItem(int,int);
		void removeItem(int,int);
		void resetBurnProgress(void);
		void resetSlotsDirty(void);
		void resetSlotsDirty(void);
		void save(CompoundTag &);
		void save(CompoundTag &);
		void setItem(int,ItemInstance *);
		void setItem(int,ItemInstance *);
		void setLitDuration(int);
		void setLitDuration(int);
		void setLitTime(int);
		void setLitTime(int);
		void setTickCount(int);
		void setTickCount(int);
		void startOpen(Player &);
		void startOpen(Player &);
		void stopOpen(Player &);
		void stopOpen(Player &);
		void tick(BlockSource &);
		void tick(BlockSource &);
		void ~FurnaceBlockEntity();
		void ~FurnaceBlockEntity();
		void ~FurnaceBlockEntity();
		void ~FurnaceBlockEntity();
};
