#pragma once
class GameRenderer{
	public:
		GameRenderer(MinecraftClient *);
		GameRenderer(MinecraftClient *);
		void _adjustVRRotationActual(bool);
		void _adjustVRRotationActual(bool);
		void _checkAndDrawInputUI(void);
		void _checkAndDrawInputUI(void);
		void _computeRealityAugmentationMatrix(Matrix &);
		void _computeRealityAugmentationMatrix(Matrix &);
		void _computeViewForSleeping(void);
		void _computeViewForSleeping(void);
		void _prepHoloTransforms(float,bool);
		void _prepHoloTransforms(float,bool);
		void _tickLightTexture(Dimension const&,float);
		void _tickLightTexture(Dimension const&,float);
		void adjustVRRotationSmoothTurningMode(float);
		void adjustVRRotationSmoothTurningMode(float);
		void captureHeadsetDirForSleeping(void);
		void captureHeadsetDirForSleeping(void);
		void cleanupRenderGraph(void);
		void clearRenderTarget(RenderGraphContext &,MinecraftClient &);
		void clearRenderTarget(RenderGraphContext &,MinecraftClient &);
		void computeTransitionScreenMat(void);
		void computeTransitionScreenMat(void);
		void createRenderGraph(void);
		void createRenderGraph(void);
		void getHoloLevelWidthHeight(float &,float &);
		void getHoloLevelWidthHeight(float &,float &);
		void getHoloUIWidthHeight(float &,float &);
		void getIncompleteScreenContext(void);
		void getIncompleteScreenContext(void);
		void recenterHoloUI(void);
		void recenterHoloUI(void);
		void render(float);
		void render(float);
		void renderCursor(float,float);
		void renderDebugScreen(RectangleArea &);
		void renderDebugScreen(RectangleArea &);
		void renderInsideCubes(float);
		void renderInsideCubes(float);
		void setInsideCubePlane(Vec4 &,Vec3 &);
		void setInsideCubePlane(Vec4 &,Vec3 &);
		void setLevel(Level *,Dimension *);
		void setLevel(Level *,Dimension *);
		void tick(void);
		void tick(void);
		void updatePointerLocation(short,short);
		void updatePointerLocation(short,short);
		void wasViewInsideSolidBlockLastRender(void);
		void wasViewInsideSolidBlockLastRender(void);
		void ~GameRenderer();
		void ~GameRenderer();
		void ~GameRenderer();
		void ~GameRenderer();
};
