#pragma once
class GuiData{
	public:
		GuiData(MinecraftClient &,NetworkStatistics const*);
		GuiData(MinecraftClient &,NetworkStatistics const*);
		void _insertGuiMessage(GuiMessage &);
		void _splitAddChatMessage(std::vector<GuiMessage,std::allocator<GuiMessage>> &,GuiMessage&);
		void _splitAddChatMessage(std::vector<GuiMessage,std::allocator<GuiMessage>> &,GuiMessage&);
		void _tickItemDrop(void);
		void _tickItemDrop(void);
		void _tickMessages(void);
		void _touchEnabledOrHolographic(void);
		void addMessage(std::string const&,std::string const&,int,bool);
		void addMessage(std::string const&,std::string const&,int,bool);
		void calcNewAlpha(float,float);
		void calcNewAlpha(float,float);
		void clearMessages(void);
		void clearMessages(void);
		void cubeSmoothStep(float,float,float);
		void cubeSmoothStep(float,float,float);
		void displayChatMessage(std::string const&,std::string const&);
		void displayChatMessage(std::string const&,std::string const&);
		void displayClientMessage(std::string const&);
		void displayClientMessage(std::string const&);
		void displayLocalizableMessage(std::string const&,std::vector<std::string,std::allocator<std::string>> const&);
		void displayLocalizableMessage(std::string const&,std::vector<std::string,std::allocator<std::string>> const&);
		void displaySystemMessage(std::string const&);
		void displaySystemMessage(std::string const&);
		void flashSlot(int);
		void flashSlot(int);
		void floorAlignToScreenPixel(float);
		void floorAlignToScreenPixel(float);
		void forceMuteChat(void);
		void forceMuteChat(void);
		void getAtlasTex(void);
		void getCrosshairMat(void);
		void getCurrentDropSlot(void);
		void getCurrentDropSlot(void);
		void getCurrentDropTicks(void);
		void getCurrentDropTicks(void);
		void getCursorMat(void);
		void getCursorMat(void);
		void getFlashSlotId(void);
		void getFlashSlotId(void);
		void getFlashSlotStartTime(void);
		void getFlashSlotStartTime(void);
		void getGuiScale(void);
		void getGuiScale(void);
		void getGuiTex(void);
		void getGuiTex(void);
		void getIconTex(void);
		void getIconTex(void);
		void getInvFillMat(void);
		void getInvFillMat(void);
		void getInvGuiScale(void);
		void getInvGuiScale(void);
		void getItemNameOverlayTime(void);
		void getItemNameOverlayTime(void);
		void getLastPopupSubtitleText(void);
		void getLastPopupSubtitleText(void);
		void getLastPopupText(void);
		void getLastPopupText(void);
		void getLastSelectedSlot(void);
		void getMessageList(void);
		void getMessageList(void);
		void getNewChatMessages(void);
		void getNewChatMessages(void);
		void getNewPopupNotice(std::string &,std::string &);
		void getNewPopupNotice(std::string &,std::string &);
		void getNumSlots(void);
		void getNumSlots(void);
		void getPointerX(void);
		void getPointerX(void);
		void getPointerY(void);
		void getPointerY(void);
		void getRcFeedbackInner(void);
		void getRcFeedbackInner(void);
		void getRcFeedbackOuter(void);
		void getRcFeedbackOuter(void);
		void getScreenHeight(void);
		void getScreenHeight(void);
		void getScreenWidth(void);
		void getScreenWidth(void);
		void getShowProgress(void);
		void getShowProgress(void);
		void getSlotIdAt(int,int);
		void getSlotPos(int,int &,int &);
		void getSlotPos(int,int &,int &);
		void getTipMessage(std::string &);
		void getTipMessage(std::string &);
		void getToolbarWasRendered(void);
		void getVignette(void);
		void getVignette(void);
		void handleClick(void);
		void handleClick(void);
		void isMuteChat(void);
		void isMuteChat(void);
		void isTouchEnabledOrHolographic(void);
		void isTouchEnabledOrHolographic(void);
		void itemCountItoa(char *,int);
		void itemCountItoa(char *,int);
		void onAppSuspended(void);
		void onAppSuspended(void);
		void onConfigChanged(Config const&);
		void onConfigChanged(Config const&);
		void onLevelGenerated(void);
		void onLevelGenerated(void);
		void postError(int);
		void postError(int);
		void renderSlotText(ItemInstance const*,float,float,bool,bool,bool,bool);
		void renderSlotText(ItemInstance const*,float,float,bool,bool,bool,bool);
		void setGuiScale(float);
		void setGuiScale(float);
		void setIsChatting(bool);
		void setIsChatting(bool);
		void setLastSelectedSlot(int);
		void setLastSelectedSlot(int);
		void setNowPlaying(std::string const&);
		void setShowProgress(bool);
		void setShowProgress(bool);
		void setToolbarWasRendered(bool);
		void setToolbarWasRendered(bool);
		void setTouchToolbarArea(RectangleArea const&);
		void setTouchToolbarArea(RectangleArea const&);
		void showPopupNotice(std::string const&,std::string const&);
		void showPopupNotice(std::string const&,std::string const&);
		void showTipMessage(std::string const&);
		void showTipMessage(std::string const&);
		void tick(void);
		void tick(void);
		void toggleMuteChat(void);
		void toggleMuteChat(void);
		void updatePointerLocation(short,short);
		void updatePointerLocation(short,short);
		void wasToolbarClicked(void);
		void wasToolbarClicked(void);
		void ~GuiData();
		void ~GuiData();
		void ~GuiData();
		void ~GuiData();
};
