#pragma once
namespace HolographicPlatform{
	class HoloFrameOfReferenceSetupData{
		public:
		void operator=(HolographicPlatform::HoloFrameOfReferenceSetupData const&);
		void operator=(HolographicPlatform::HoloFrameOfReferenceSetupData const&);
		HolographicPlatform(void);
		void _computeSpaceHash(TransformSpace,TransformSpace);
		void _getTransform(TransformSpace,TransformSpace);
		void _insertIntoMap(TransformSpace,TransformSpace,Matrix &);
		void _insertIntoMap(TransformSpace,TransformSpace,Matrix &);
		void _insertTransformBridgeIntoMap(TransformSpace,TransformSpace,TransformSpace);
		void _makeTransform(TransformSpace,TransformSpace);
		void _makeTransform(TransformSpace,TransformSpace);
		void _prepPlatformSpecificTransforms(void);
		void _prepPlatformSpecificTransforms(void);
		void addToHMDPositionSpring(Vec3 const&);
		void addToHMDPositionSpring(Vec3 const&);
		void allowThirdPersonView(void);
		void allowThirdPersonView(void);
		void allowVRFrameExperience(void);
		void allowVRFrameExperience(void);
		void createRenderGraph(mce::RenderGraph &,MinecraftClient &);
		void createRenderGraph(mce::RenderGraph &,MinecraftClient &);
		void defaultLSRPlane(HolographicPlatform::MCLocation);
		void defaultLSRPlane(HolographicPlatform::MCLocation);
		void delayForNextFingerPress(int);
		void delayForNextFingerPress(int);
		void deviceHasPositionalTracking(void);
		void deviceHasPositionalTracking(void);
		void deviceNeedsToBeRemovedForXblSignin(void);
		void deviceNeedsToBeRemovedForXblSignin(void);
		void drawCubemapInMono(void);
		void drawCubemapInMono(void);
		void drawHolographicBordersForUI(void);
		void drawHolographicBordersForUI(void);
		void forceControllerUsage(void);
		void forceControllerUsage(void);
		void getAmbientBoost(void);
		void getAmbientBoost(void);
		void getDefaultHalfHoloScreenWidth(void);
		void getDefaultHalfHoloScreenWidth(void);
		void getDefaultIngameUIDistance(void);
		void getDefaultIngameUIDistance(void);
		void getGazeCastResultPS(Vec3 &,Vec3 &,Vec3 &);
		void getGazeCastResultPS(Vec3 &,Vec3 &,Vec3 &);
		void getItemInHandOffset(Vec3 &);
		void getItemInHandOffset(Vec3 &);
		void getLastLSRPlanePosAndNormPS(Vec3 &,Vec3 &);
		void getLastLSRPlanePosAndNormPS(Vec3 &,Vec3 &);
		void getLivingRoomLevelTextureWidthHeight(uint &,uint &,float &);
		void getLivingRoomLevelTextureWidthHeight(uint &,uint &,float &);
		void getPreferredLivingRoomLevelAspectRation(void);
		void getPreferredLivingRoomLevelAspectRation(void);
		void getPreferredUIAspectRatio(void);
		void getPreferredUIAspectRatio(void);
		void getSRCastDistance(void);
		void getSRCastDistance(void);
		void getStereoEnabled(void);
		void getStereoEnabled(void);
		void getTransform(TransformSpace,TransformSpace,TransformSpace);
		void getTransform(TransformSpace,TransformSpace,TransformSpace);
		void getTransformTranslation(TransformSpace,TransformSpace,TransformSpace);
		void getTransformTranslation(TransformSpace,TransformSpace,TransformSpace);
		void getTransformXDir(TransformSpace,TransformSpace,TransformSpace);
		void getTransformXDir(TransformSpace,TransformSpace,TransformSpace);
		void getTransformYDir(TransformSpace,TransformSpace,TransformSpace);
		void getTransformZDir(TransformSpace,TransformSpace,TransformSpace);
		void getTransformZDir(TransformSpace,TransformSpace,TransformSpace);
		void getUIClipGrowPixels(void);
		void getUIClipGrowPixels(void);
		void getUIRenderMode(void);
		void getUIRenderMode(void);
		void getUIScreenWidthHeightScale(uint &,uint &,float &);
		void getUIScreenWidthHeightScale(uint &,uint &,float &);
		void getVRHUDRenderMode(void);
		void getVRHUDRenderMode(void);
		void getVRLayeringActive(void);
		void getVRLowFrequencyHUD(void);
		void getVRLowFrequencyHUD(void);
		void getViewableScreenSize(float);
		void getViewableScreenSize(float);
		void getWorkerFramerate(void);
		void getWorkerFramerate(void);
		void holographicMode(void);
		void holographicMode(void);
		void init(Options &);
		void init(Options &);
		void isFeatureEnabled(uint);
		void isFeatureEnabled(uint);
		void isGazeDevicePresent(void);
		void isGazeDevicePresent(void);
		void isGestureDevicePresent(void);
		void isGestureDevicePresent(void);
		void isLocated(void);
		void isLocated(void);
		void isPrimaryHandHeld(void);
		void isPrimaryHandHeld(void);
		void isSecondaryHandHeld(void);
		void isSecondaryHandHeld(void);
		void isVRMode(void);
		void isVRMode(void);
		void numRequiredControllers(void);
		void numRequiredControllers(void);
		void onAppFocusGained(void);
		void onAppFocusGained(void);
		void onAppFocusLost(void);
		void onAppFocusLost(void);
		void onAppResumed(void);
		void onAppResumed(void);
		void onAppSuspended(void);
		void onAppSuspended(void);
		void onHMDFocusGained(void);
		void onHMDFocusGained(void);
		void onHMDFocusLost(void);
		void onHMDFocusLost(void);
		void present(void);
		void present(void);
		void removeFromHMDPositionSpring(Vec3 const&);
		void removeFromHMDPositionSpring(Vec3 const&);
		void renderSRData(float,float);
		void renderSRData(float,float);
		void resetBaseFrameOfReference(float,bool);
		void resetBaseFrameOfReference(float,bool);
		void resetEnvironmentScan(void);
		void resetEnvironmentScan(void);
		void resetScreenLocationOffset(void);
		void resetScreenLocationOffset(void);
		void separateEyePasses(void);
		void separateEyePasses(void);
		void setHeadlockedUITransform(Matrix const&);
		void setHeadlockedUITransform(Matrix const&);
		void setHoloviewerLocation(Matrix const&);
		void setHoloviewerLocation(Matrix const&);
		void setHoloviewerLocation(Vec3 const&,Vec3 const*,float,bool);
		void setHoloviewerLocation(Vec3 const&,Vec3 const*,float,bool);
		void setNewFrameOfReferenceFrameData(HolographicPlatform::HoloFrameOfReferenceSetupData const&);
		void setNewFrameOfReferenceFrameData(HolographicPlatform::HoloFrameOfReferenceSetupData const&);
		void setRealityAnchorLocation(Matrix const&);
		void setRealityAnchorLocation(Matrix const&);
		void setScreenLocation(Matrix const&);
		void setScreenLocation(Matrix const&);
		void setScreenLocation(Vec3 const&,Vec3 const*,float);
		void setScreenLocation(Vec3 const&,Vec3 const*,float);
		void setScreenLocationOffset(Vec3 const&);
		void setScreenLocationOffset(Vec3 const&);
		void setStereoEnabled(bool);
		void setStereoEnabled(bool);
		void setUIClipRect(RectangleArea const&);
		void setUIClipRect(RectangleArea const&);
		void function<void ();
		void function<void ();
		void setVRLayeringActive(bool);
		void setVRLayeringActive(bool);
		void startEnvironmentScanning(void);
		void startEnvironmentScanning(void);
		void stopEnvironmentScanning(void);
		void stopEnvironmentScanning(void);
		void update(MinecraftClient &);
		void update(MinecraftClient &);
		void updateLSRPlane(HolographicPlatform::MCLocation,Vec3 const&);
		void updateLSRPlane(HolographicPlatform::MCLocation,Vec3 const&);
		void useAlternateTouchInput(void);
		void useAlternateTouchInput(void);
		void useSinglePassStereo(void);
		void useSinglePassStereo(void);
		void ~HolographicPlatform();
		void ~HolographicPlatform();
		void ~HolographicPlatform();
		void ~HolographicPlatform();
	}
};
