#pragma once
class HopperBlockEntity{
	public:
		HopperBlockEntity(BlockPos const&);
		HopperBlockEntity(BlockPos const&);
		void _initItems(void);
		void checkForSmeltEverythingAchievement(BlockSource &);
		void checkForSmeltEverythingAchievement(BlockSource &);
		void getAttachedFurnace(BlockSource &);
		void getAttachedFurnace(BlockSource &);
		void getContainerSize(void);
		void getContainerSize(void);
		void getItem(int);
		void getItem(int);
		void getLevelPos(void);
		void getMaxStackSize(void);
		void getMaxStackSize(void);
		void getName(void);
		void getName(void);
		void isAttachedToChestAndFurnace(BlockSource &);
		void isAttachedToChestAndFurnace(BlockSource &);
		void isAttachedToContainerType(BlockSource &,ContainerType);
		void isSourceOfContainerType(BlockSource &,ContainerType);
		void load(CompoundTag const&);
		void load(CompoundTag const&);
		void onMove(void);
		void onMove(void);
		void onNeighborChanged(BlockSource &,BlockPos const&);
		void onNeighborChanged(BlockSource &,BlockPos const&);
		void removeItem(int,int);
		void removeItem(int,int);
		void save(CompoundTag &);
		void save(CompoundTag &);
		void setItem(int,ItemInstance *);
		void setItem(int,ItemInstance *);
		void startOpen(Player &);
		void startOpen(Player &);
		void stopOpen(Player &);
		void stopOpen(Player &);
		void tick(BlockSource &);
		void tick(BlockSource &);
		void ~HopperBlockEntity();
		void ~HopperBlockEntity();
		void ~HopperBlockEntity();
		void ~HopperBlockEntity();
};
