#pragma once
class InGamePlayScreen{
	public:
		InGamePlayScreen(MinecraftClient &);
		InGamePlayScreen(MinecraftClient &);
		InGamePlayScreen(MinecraftClient &);
		void _applyInput_DirectRoll(InputMode const&,float,float,float);
		void _applyInput_DirectRoll(InputMode const&,float,float,float);
		void _applyInput_Standard(InputMode const&,float,float,float);
		void _applyInput_Standard(InputMode const&,float,float,float);
		void _applyInput_StepSound(void);
		void _applyInput_StepSound(void);
		void _applyInput_Stutter(InputMode const&,float,float,float);
		void _applyInput_Stutter(InputMode const&,float,float,float);
		void _applyInput_StutterDirectRoll(InputMode const&,float,float,float);
		void _applyInput_StutterDirectRoll(InputMode const&,float,float,float);
		void _applyInput_StutterRoll(InputMode const&,float,float,float);
		void _applyInput_StutterRoll(InputMode const&,float,float,float);
		void _getPickRange(void);
		void _getPickRange(void);
		void _getThirdPersonSetting(void);
		void _getThirdPersonSetting(void);
		void _init(int,int);
		void _init(int,int);
		void _isHoloViewer(void);
		void _isHoloViewer(void);
		void _isVRTransitioning(void);
		void _localPlayerTurned(float);
		void _localPlayerTurned(float);
		void _pick(float);
		void _pick(float);
		void _postLevelRender(ScreenContext &);
		void _postLevelRender(ScreenContext &);
		void _preLevelRender(ScreenContext &);
		void _preLevelRender(ScreenContext &);
		void _prepareCuller(FrustumData &,FrustumData &);
		void _prepareCuller(FrustumData &,FrustumData &);
		void _renderFirstPerson3DObjects(LevelRenderer &,float);
		void _renderFirstPerson3DObjects(LevelRenderer &,float);
		void _renderItemInHand(Player &,bool,float);
		void _renderItemInHand(Player &,bool,float);
		void _renderLevel(float);
		void _renderLevel(float);
		void _renderLevelPrep(float);
		void _renderLevelPrep(float);
		void _renderTransparentFirstPerson3DObjects(LevelRenderer &,float);
		void _renderTransparentFirstPerson3DObjects(LevelRenderer &,float);
		void _renderedFramedItems(Vec3,LevelRenderer &,Entity &,float);
		void _renderedFramedItems(Vec3,LevelRenderer &,Entity &,float);
		void _saveMatrices(void);
		void _saveMatrices(void);
		void _setCorrectViewProj(mce::WorldConstantsHolographic &);
		void _setCorrectViewProj(mce::WorldConstantsHolographic &);
		void _setHoloMode(void);
		void _setHoloMode(void);
		void _shouldClipLiquids(void);
		void _shouldClipLiquids(void);
		void _shouldPushHUD(void);
		void _shouldPushHUD(void);
		void _shouldRenderFirstPersonObjects(LevelRenderer &);
		void _shouldRenderFirstPersonObjects(LevelRenderer &);
		void _updateFreeformPickDirection(float,Vec3 &,Vec3 &);
		void _updateFreeformPickDirection(float,Vec3 &,Vec3 &);
		void _updateInGameCursor(void);
		void _updateInGameCursor(void);
		void applyInput(float);
		void applyInput(float);
		void getScreenName(void);
		void getScreenName(void);
		void getSendTelemetry(void);
		void getSendTelemetry(void);
		void handleDirection(DirectionId,float,float);
		void handleDirection(DirectionId,float,float);
		void isModal(void);
		void isModal(void);
		void isShowingMenu(void);
		void isShowingMenu(void);
		void onFocusGained(void);
		void onFocusGained(void);
		void render(ScreenContext &);
		void render(ScreenContext &);
		void renderGameBehind(void);
		void renderGameBehind(void);
		void renderOnlyWhenTopMost(void);
		void renderOnlyWhenTopMost(void);
		void shouldStealMouse(void);
		void shouldStealMouse(void);
		void tick(int,int);
		void tick(int,int);
		void ~InGamePlayScreen();
		void ~InGamePlayScreen();
		void ~InGamePlayScreen();
		void ~InGamePlayScreen();
};
