#pragma once
class InputComponent{
	public:
		InputComponent(std::shared_ptr<UIControl> &);
		InputComponent(std::shared_ptr<UIControl> &);
		InputComponent(std::shared_ptr<UIControl> &);
		void _computePressType(short,ButtonState);
		void _computePressType(short,ButtonState);
		void _getContentPanelHover(glm::detail::tvec2<float> const&);
		void _getContentPanelHover(glm::detail::tvec2<float> const&);
		void _isWithinInputScope(InputComponent::ScreenButtonMapping const&,glm::detail::tvec2<float> const&,std::shared_ptr<UIControl> &,bool);
		void _sendScreenEvent(ScreenInputContext &,std::shared_ptr<UIControl> &,InputComponent::ScreenButtonMapping const&,ButtonState,glm::detail::tvec2<float> const&,VisualTree &,AnimationController &);
		void _sendScreenEvent(ScreenInputContext &,std::shared_ptr<UIControl> &,InputComponent::ScreenButtonMapping const&,ButtonState,glm::detail::tvec2<float> const&,VisualTree &,AnimationController &);
		void _shouldHandleControllerDirection(std::shared_ptr<UIControl> &,DirectionId,glm::detail::tvec2<float> const&);
		void _shouldHandleControllerDirection(std::shared_ptr<UIControl> &,DirectionId,glm::detail::tvec2<float> const&);
		void _shouldHandleMapping(std::shared_ptr<UIControl> &,InputComponent::ScreenButtonMapping const&,InputComponent::PressType,short,ButtonState,glm::detail::tvec2<float> const&,InputMode);
		void _shouldHandleMapping(std::shared_ptr<UIControl> &,InputComponent::ScreenButtonMapping const&,InputComponent::PressType,short,ButtonState,glm::detail::tvec2<float> const&,InputMode);
		void _shouldHandlePressedMapping(std::shared_ptr<UIControl> &,InputComponent::ScreenButtonMapping const&,short,ButtonState,glm::detail::tvec2<float> const&,InputMode);
		void addButtonMapping(short,short,ButtonMappingType,ScreenEventScope,bool,bool,bool,bool);
		void addButtonMapping(short,short,ButtonMappingType,ScreenEventScope,bool,bool,bool,bool);
		void addHoverButtonMapping(short,ScreenEventScope);
		void addHoverButtonMapping(short,ScreenEventScope);
		void addRemappingMapping(ScreenEventScope);
		void addRemappingMapping(ScreenEventScope);
		void clone(std::shared_ptr<UIControl> &);
		void clone(std::shared_ptr<UIControl> &);
		void getAlwaysHandlePointer(void);
		void getAlwaysListensToInput(void);
		void getAlwaysListensToInput(void);
		void getModal(void);
		void getModal(void);
		void handleButtonEvent(VisualTree &,AnimationController &,ScreenInputContext &,short,ButtonState,glm::detail::tvec2<float> const&,InputMode);
		void handleButtonEvent(VisualTree &,AnimationController &,ScreenInputContext &,short,ButtonState,glm::detail::tvec2<float> const&,InputMode);
		void handleControllerDirection(VisualTree &,AnimationController &,ScreenInputContext &,DirectionId,glm::detail::tvec2<float> const&,bool);
		void handleControllerDirection(VisualTree &,AnimationController &,ScreenInputContext &,DirectionId,glm::detail::tvec2<float> const&,bool);
		void handleFocusLocation(VisualTree &,AnimationController &,ScreenInputContext &,glm::detail::tvec2<float> const&,bool);
		void handleFocusLocation(VisualTree &,AnimationController &,ScreenInputContext &,glm::detail::tvec2<float> const&,bool);
		void handleHoloInputModeChange(VisualTree &,AnimationController &,ScreenInputContext &,HoloUIInputMode);
		void handleHoloInputModeChange(VisualTree &,AnimationController &,ScreenInputContext &,HoloUIInputMode);
		void handleInputModeChange(VisualTree &,AnimationController &,ScreenInputContext &,InputMode);
		void handleInputModeChange(VisualTree &,AnimationController &,ScreenInputContext &,InputMode);
		void handlePointerLocation(VisualTree &,AnimationController &,ScreenInputContext &,glm::detail::tvec2<float> const&,glm::detail::tvec2<float> const&,bool);
		void handlePointerLocation(VisualTree &,AnimationController &,ScreenInputContext &,glm::detail::tvec2<float> const&,glm::detail::tvec2<float> const&,bool);
		void handleScrollDirection(VisualTree &,AnimationController &,ScreenInputContext &,glm::detail::tvec2<float> const&,glm::detail::tvec2<float> const&,bool);
		void isWithinClipRegion(glm::detail::tvec2<float> const&);
		void isWithinClipRegion(glm::detail::tvec2<float> const&);
		void setAlwaysHandlePointer(bool);
		void setAlwaysHandlePointer(bool);
		void setAlwaysListensToInput(bool);
		void setAlwaysListensToInput(bool);
		void setModal(bool);
		void setModal(bool);
		void ~InputComponent();
		void ~InputComponent();
		void ~InputComponent();
		void ~InputComponent();
};
