#pragma once
class ItemFrameBlockEntity{
	public:
		ItemFrameBlockEntity(BlockPos);
		ItemFrameBlockEntity(BlockPos);
		ItemFrameBlockEntity(BlockPos,BlockEntityType);
		void _checkMapRemoval(BlockSource &,ItemInstance &);
		void dropFramedItem(BlockSource &,bool);
		void dropFramedItem(BlockSource &,bool);
		void getClockFrame(void);
		void getClockFrame(void);
		void getCompassFrame(void);
		void getCompassFrame(void);
		void getFramedItem(void);
		void getFramedItem(void);
		void getRotation(void);
		void getRotation(void);
		void getShadowRadius(BlockSource &);
		void getShadowRadius(BlockSource &);
		void getUpdatePacket(BlockSource &);
		void getUpdatePacket(BlockSource &);
		void load(CompoundTag const&);
		void load(CompoundTag const&);
		void onChanged(BlockSource &);
		void onChanged(BlockSource &);
		void onUpdatePacket(CompoundTag &);
		void onUpdatePacket(CompoundTag &);
		void rotateFramedItem(void);
		void rotateFramedItem(void);
		void save(CompoundTag &);
		void save(CompoundTag &);
		void setItem(BlockSource &,ItemInstance &);
		void setItem(BlockSource &,ItemInstance &);
		void spawnItem(BlockSource &,ItemInstance &);
		void spawnItem(BlockSource &,ItemInstance &);
		void tick(BlockSource &);
		void tick(BlockSource &);
		void ~ItemFrameBlockEntity();
		void ~ItemFrameBlockEntity();
		void ~ItemFrameBlockEntity();
		void ~ItemFrameBlockEntity();
};
