#pragma once
class LayoutComponent{
	public:
		LayoutComponent(std::shared_ptr<UIControl> &);
		LayoutComponent(std::shared_ptr<UIControl> &);
		LayoutComponent(std::shared_ptr<UIControl> &);
		void _clampOffsetDeltaToParentSize(UIControl const*);
		void _clampOffsetDeltaToParentSize(UIControl const*);
		void _isVariableIsSupported(LayoutVariableType);
		void _isVariableIsSupported(LayoutVariableType);
		void clone(std::shared_ptr<UIControl> &);
		void clone(std::shared_ptr<UIControl> &);
		void getAnchorFrom(void);
		void getAnchorFrom(void);
		void getAnchorTo(void);
		void getAnchorTo(void);
		void getContained(void);
		void getDraggable(void);
		void getDraggable(void);
		void getFollowsCursor(void);
		void getOffset(void);
		void getOffset(void);
		void getOffsetDelta(void);
		void getOffsetDelta(void);
		void getPositionMinusOffsetDelta(void);
		void getPositionMinusOffsetDelta(void);
		void getSize(void);
		void getSize(void);
		void getVariable(LayoutVariableType);
		void getVariable(LayoutVariableType);
		void initializeVariables(std::shared_ptr<LayoutVariables> &);
		void initializeVariables(std::shared_ptr<LayoutVariables> &);
		void isBeingDragged(void);
		void layout(std::initializer_list<LayoutVariableType>);
		void layout(std::initializer_list<LayoutVariableType>);
		void receive(VisualTree &,ScreenInputContext &,AnimationController &,ScreenEvent);
		void receive(VisualTree &,ScreenInputContext &,AnimationController &,ScreenEvent);
		void setAnchorFrom(ui::AnchorPoint);
		void setAnchorFrom(ui::AnchorPoint);
		void setAnchorTo(ui::AnchorPoint);
		void setAnchorTo(ui::AnchorPoint);
		void setContained(bool);
		void setContained(bool);
		void setDraggable(ui::Draggable);
		void setDraggable(ui::Draggable);
		void setFollowsCursor(bool);
		void setFollowsCursor(bool);
		void setOffset(ui::LayoutOffset const&);
		void setOffset(ui::LayoutOffset const&);
		void setOffsetDelta(glm::detail::tvec2<float> const&,UIControl const*);
		void setOffsetDelta(glm::detail::tvec2<float> const&,UIControl const*);
		void setSize(ui::LayoutOffset const&);
		void setSize(ui::LayoutOffset const&);
		void setVariableOverrideValue(LayoutVariableType,float);
		void setVariableOverrideValue(LayoutVariableType,float);
		void ~LayoutComponent();
		void ~LayoutComponent();
		void ~LayoutComponent();
		void ~LayoutComponent();
};
