#pragma once
class LeafBlock{
	public:
		LeafBlock(std::string const&,int);
		LeafBlock(std::string const&,int);
		void die(BlockSource &,BlockPos const&);
		void getColor(BlockSource &,BlockPos const&);
		void getColor(BlockSource &,BlockPos const&);
		void getMobToSpawn(BlockSource &,BlockPos const&);
		void getMobToSpawn(BlockSource &,BlockPos const&);
		void getRenderLayer(BlockSource &,BlockPos const&);
		void getRenderLayer(BlockSource &,BlockPos const&);
		void getResource(Random &,int,int);
		void getResource(Random &,int,int);
		void getResourceCount(Random &,int,int);
		void getResourceCount(Random &,int,int);
		void getSeasonsColor(BlockSource &,BlockPos const&,int,int);
		void getSeasonsColor(BlockSource &,BlockPos const&,int,int);
		void getSpawnResourcesAuxValue(uchar);
		void getSpawnResourcesAuxValue(uchar);
		void isDeepLeafBlock(BlockSource &,BlockPos const&);
		void isDeepLeafBlock(BlockSource &,BlockPos const&);
		void isSeasonTinted(BlockSource &,BlockPos const&);
		void isSeasonTinted(BlockSource &,BlockPos const&);
		void onGraphicsModeChanged(bool,bool,bool);
		void onGraphicsModeChanged(bool,bool,bool);
		void onRemove(BlockSource &,BlockPos const&);
		void onRemove(BlockSource &,BlockPos const&);
		void playerDestroy(Player *,BlockPos const&,int);
		void playerDestroy(Player *,BlockPos const&,int);
		void runDecay(BlockSource &,BlockPos const&,int);
		void runDecay(BlockSource &,BlockPos const&,int);
		void spawnResources(BlockSource &,BlockPos const&,int,float,int);
		void spawnResources(BlockSource &,BlockPos const&,int,float,int);
		void tick(BlockSource &,BlockPos const&,Random &);
		void tick(BlockSource &,BlockPos const&,Random &);
		void ~LeafBlock();
		void ~LeafBlock();
		void ~LeafBlock();
		void ~LeafBlock();
};
