#pragma once
class LeashFenceKnotEntity{
	public:
		LeashFenceKnotEntity(BlockSource &);
		LeashFenceKnotEntity(BlockSource &);
		LeashFenceKnotEntity(BlockSource &,BlockPos const&,int);
		LeashFenceKnotEntity(BlockSource &,BlockPos const&,int);
		void addAdditionalSaveData(CompoundTag &);
		void addAdditionalSaveData(CompoundTag &);
		void dropItem(void);
		void dropItem(void);
		void getEntityTypeId(void);
		void getEntityTypeId(void);
		void getEyeHeight(void);
		void getEyeHeight(void);
		void getHeight(void);
		void getHeight(void);
		void getShadowRadius(void);
		void getShadowRadius(void);
		void getWidth(void);
		void getWidth(void);
		void interactWithPlayer(Player &);
		void interactWithPlayer(Player &);
		void isPickable(void);
		void isPickable(void);
		void numberofAnimalsAttached(void);
		void numberofAnimalsAttached(void);
		void readAdditionalSaveData(CompoundTag const&);
		void readAdditionalSaveData(CompoundTag const&);
		void recalculateBoundingBox(void);
		void remove(void);
		void remove(void);
		void removeAnimals(Player *);
		void removeAnimals(Player *);
		void setDir(int);
		void setDir(int);
		void shouldRenderAtSqrDistance(double);
		void survives(void);
		void survives(void);
		void ~LeashFenceKnotEntity();
		void ~LeashFenceKnotEntity();
};
