#pragma once
class LocalPlayer{
	public:
		LocalPlayer(MinecraftClient *,Level &,User const&,GameType,RakNet::RakNetGUID const&,mce::UUID);
		LocalPlayer(MinecraftClient *,Level &,User const&,GameType,RakNet::RakNetGUID const&,mce::UUID);
		void _PostJumpFrameOfReferenceAdjustCheck(bool);
		void _RotationVec2Modulus(Vec2 &);
		void _calculateFlight(float,float,float);
		void _calculateFlight(float,float,float);
		void _checkMovementStatistiscs(Vec3 const&);
		void _checkMovementStatistiscs(Vec3 const&);
		void _crit(Entity &);
		void _crit(Entity &);
		void _init(void);
		void _init(void);
		void _input(void);
		void _modifyDeltaByHMDPosition(Vec3 &,float);
		void _modifyDeltaByHMDPosition(Vec3 &,float);
		void _setRideInputFor(Entity &);
		void _setRideInputFor(Entity &);
		void _updateArmorTypeHash(void);
		void _updateArmorTypeHash(void);
		void _updateAutoJump(float,float,float,float);
		void _updateAutoJump(float,float,float,float);
		void actuallyHurt(int,EntityDamageSource const*);
		void actuallyHurt(int,EntityDamageSource const*);
		void addAdditionalSaveData(CompoundTag &);
		void addAdditionalSaveData(CompoundTag &);
		void addItemCreative(ItemInstance const*);
		void addItemCreative(ItemInstance const*);
		void addRegionListener(LocalPlayer::RegionListener *);
		void addRegionListener(LocalPlayer::RegionListener *);
		void aiStep(void);
		void aiStep(void);
		void applyFinalFriction(float);
		void applyFinalFriction(float);
		void canStartSleepInBed(void);
		void canStartSleepInBed(void);
		void changeDimension(ChangeDimensionPacket &);
		void changeDimension(ChangeDimensionPacket &);
		void changeDimension(DimensionId);
		void changeDimension(DimensionId);
		void chat(std::string const&);
		void checkFallDamage(float,bool);
		void checkFallDamage(float,bool);
		void clearMovementState(void);
		void clearMovementState(void);
		void closeScreen(void);
		void closeScreen(void);
		void deleteContainerManager(void);
		void deleteContainerManager(void);
		void destroyRegion(void);
		void destroyRegion(void);
		void die(EntityDamageSource const&);
		void die(EntityDamageSource const&);
		void displayLocalizableMessage(std::string const&,std::vector<std::string,std::allocator<std::string>> const&);
		void displayLocalizableMessage(std::string const&,std::vector<std::string,std::allocator<std::string>> const&);
		void drop(ItemInstance const*,bool);
		void drop(ItemInstance const*,bool);
		void getBob(void);
		void getBob(void);
		void getBobOld(void);
		void getBobOld(void);
		void getControllingPlayer(void);
		void getControllingPlayer(void);
		void getFieldOfViewModifier(void);
		void getFieldOfViewModifier(void);
		void getGameModeString(void);
		void getHudContainerManagerModel(void);
		void getHudContainerManagerModel(void);
		void getInventoryMenu(void);
		void getInventoryMenu(void);
		void getJumpRidingScale(void);
		void getJumpRidingScale(void);
		void getLoadingState(void);
		void getLoadingState(void);
		void getMinecraftClient(void);
		void getMinecraftClient(void);
		void getOPortalEffectTime(void);
		void getOPortalEffectTime(void);
		void getPortalEffectTime(void);
		void getPortalEffectTime(void);
		void getPreloadingProgress(void);
		void getPreloadingProgress(void);
		void getTelemetry(void);
		void getTelemetry(void);
		void getViewBlockRadius(void);
		void getViewBlockRadius(void);
		void handleInsidePortal(BlockPos const&);
		void handleInsidePortal(BlockPos const&);
		void hurt(EntityDamageSource const&,int);
		void hurt(EntityDamageSource const&,int);
		void hurtTo(int);
		void hurtTo(int);
		void isAutoJumpEnabled(void);
		void isAutoJumpEnabled(void);
		void isFlying(void);
		void isFlying(void);
		void isInTrialMode(void);
		void isInTrialMode(void);
		void isLocalPlayer(void);
		void isLocalPlayer(void);
		void localPlayerRenderFrequencyMove(float);
		void localPlayerRenderFrequencyMove(float);
		void localPlayerTurn(Vec2 const&,bool);
		void localPlayerTurn(Vec2 const&,bool);
		void move(Vec3 const&);
		void move(Vec3 const&);
		void normalTick(void);
		void normalTick(void);
		void onDimensionChanged(void);
		void onDimensionChanged(void);
		void onGameEventNotification(ui::GameEventNotification);
		void onPrepChangeDimension(void);
		void onPrepChangeDimension(void);
		void openAnvil(BlockPos const&);
		void openAnvil(BlockPos const&);
		void openBrewingStand(int,BlockPos const&);
		void openBrewingStand(int,BlockPos const&);
		void openContainer(int,BlockPos const&);
		void openContainer(int,BlockPos const&);
		void openContainer(int,EntityUniqueID const&);
		void openContainer(int,EntityUniqueID const&);
		void openDispenser(int,BlockPos const&,bool);
		void openDispenser(int,BlockPos const&,bool);
		void openEnchanter(int,BlockPos const&);
		void openEnchanter(int,BlockPos const&);
		void openFurnace(int,BlockPos const&);
		void openFurnace(int,BlockPos const&);
		void openHopper(int,BlockPos const&);
		void openHopper(int,BlockPos const&);
		void openHopper(int,EntityUniqueID const&);
		void openHopper(int,EntityUniqueID const&);
		void openHorseInventory(int,EntityUniqueID const&);
		void openHorseInventory(int,EntityUniqueID const&);
		void openPortfolio(void);
		void openPortfolio(void);
		void openTextEdit(BlockEntity *);
		void openTextEdit(BlockEntity *);
		void outOfWorld(void);
		void outOfWorld(void);
		void pickBlockCreative(HitResult const&);
		void pickBlockCreative(HitResult const&);
		void readAdditionalSaveData(CompoundTag const&);
		void readAdditionalSaveData(CompoundTag const&);
		void refreshContainer(IContainerManager &,std::vector<ItemInstance,std::allocator<ItemInstance>> const&);
		void refreshContainer(IContainerManager &,std::vector<ItemInstance,std::allocator<ItemInstance>> const&);
		void registerFramewiseActionOrStop(void);
		void registerFramewiseActionOrStop(void);
		void removeRegionListener(LocalPlayer::RegionListener *);
		void removeRegionListener(LocalPlayer::RegionListener *);
		void requestChunkRadius(int);
		void requestChunkRadius(int);
		void resetLastHmdAngle(void);
		void resetLastHmdAngle(void);
		void resetPos(bool);
		void resetPos(bool);
		void respawn(void);
		void respawn(void);
		void rideTick(void);
		void rideTick(void);
		void sendGameSessionHeartBeat(bool);
		void sendInput(void);
		void sendPosition(void);
		void setArmor(ArmorSlot,ItemInstance const*);
		void setArmor(ArmorSlot,ItemInstance const*);
		void setContainerData(IContainerManager &,int,int);
		void setContainerData(IContainerManager &,int,int);
		void setHudContainerManagerModel(std::shared_ptr<HudContainerManagerModel>);
		void setOPortalEffectTime(float);
		void setPortalEffectTime(float);
		void setPos(Vec3 const&);
		void setPos(Vec3 const&);
		void setSneaking(bool);
		void setSneaking(bool);
		void setSprinting(bool);
		void setSprinting(bool);
		void slotChanged(IContainerManager &,int,ItemInstance const&,bool);
		void slotChanged(IContainerManager &,int,ItemInstance const&,bool);
		void startCrafting(BlockPos const&);
		void startCrafting(BlockPos const&);
		void startPaddling(Side);
		void startPaddling(Side);
		void startRiding(Entity &);
		void startRiding(Entity &);
		void startSleepInBed(BlockPos const&);
		void startSleepInBed(BlockPos const&);
		void stopLoading(void);
		void stopLoading(void);
		void stopPaddling(Side);
		void stopPaddling(Side);
		void stopRiding(bool,bool);
		void stopRiding(bool,bool);
		void stopSleepInBed(bool,bool);
		void stopSleepInBed(bool,bool);
		void swing(void);
		void swing(void);
		void tickWorld(Tick const&);
		void tickWorld(Tick const&);
		void travel(float,float);
		void travel(float,float);
		void updateAi(void);
		void updateAi(void);
		void ~LocalPlayer();
		void ~LocalPlayer();
		void ~LocalPlayer();
		void ~LocalPlayer();
};
