#pragma once
class Monster{
	public:
		Monster(BlockSource &);
		Monster(BlockSource &);
		void _getWalkTargetValue(BlockPos const&);
		void _getWalkTargetValue(BlockPos const&);
		void addAdditionalSaveData(CompoundTag &);
		void addAdditionalSaveData(CompoundTag &);
		void aiStep(void);
		void aiStep(void);
		void canSpawn(bool);
		void canSpawn(bool);
		void checkHurtTarget(Entity *,float);
		void checkHurtTarget(Entity *,float);
		void doHurtTarget(Entity *);
		void doHurtTarget(Entity *);
		void findAttackTarget(void);
		void findAttackTarget(void);
		void getAttackTime(void);
		void getAttackTime(void);
		void getExperienceReward(void);
		void getExperienceReward(void);
		void hurt(EntityDamageSource const&,int);
		void hurt(EntityDamageSource const&,int);
		void isDarkEnoughToSpawn(void);
		void isDarkEnoughToSpawn(void);
		void isSurfaceMob(void);
		void isSurfaceMob(void);
		void normalTick(void);
		void normalTick(void);
		void readAdditionalSaveData(CompoundTag const&);
		void readAdditionalSaveData(CompoundTag const&);
		void registerAttributes(void);
		void registerAttributes(void);
		void setNightly(void);
		void setNightly(void);
		void shouldDespawn(void);
		void shouldDespawn(void);
		void ~Monster();
		void ~Monster();
};
