#pragma once
class PathNavigation{
	public:
		PathNavigation(Mob &,Level *,float);
		PathNavigation(Mob &,Level *,float);
		PathNavigation(Mob &,Level *,float);
		void _canMoveDirectly(Vec3 const&,Vec3 const&,int,int,int);
		void _canMoveDirectly(Vec3 const&,Vec3 const&,int,int,int);
		void _canUpdatePath(void);
		void _canWalkAbove(int,int,int,int,int,int,Vec3 const&,float,float);
		void _canWalkAbove(int,int,int,int,int,int,Vec3 const&,float,float);
		void _canWalkOn(int,int,int,int,int,int,Vec3 const&,float,float);
		void _canWalkOn(int,int,int,int,int,int,Vec3 const&,float,float);
		void _getSurfaceY(void);
		void _getSurfaceY(void);
		void _getTempMobPos(void);
		void _isInLiquid(void);
		void _trimPathFromSun(void);
		void _trimPathFromSun(void);
		void _updatePath(void);
		void _updatePath(void);
		void canOpenDoors(void);
		void canOpenDoors(void);
		void canPassDoors(void);
		void createPath(Mob &);
		void createPath(Mob &);
		void createPath(Vec3 const&);
		void createPath(Vec3 const&);
		void getAvoidWater(void);
		void getAvoidWater(void);
		void getMaxDistance(void);
		void getMaxDistance(void);
		void getPath(void);
		void getPath(void);
		void isDone(void);
		void isDone(void);
		void moveTo(Mob &,float);
		void moveTo(Mob &,float);
		void moveTo(Vec3 const&,float);
		void moveTo(Vec3 const&,float);
		void moveTo(std::unique_ptr<Path,std::default_delete<Path>>,float);
		void moveTo(std::unique_ptr<Path,std::default_delete<Path>>,float);
		void setAvoidSun(bool);
		void setAvoidSun(bool);
		void setAvoidWater(bool);
		void setAvoidWater(bool);
		void setCanFloat(bool);
		void setCanFloat(bool);
		void setCanOpenDoors(bool);
		void setCanOpenDoors(bool);
		void setCanPassDoors(bool);
		void setCanPassDoors(bool);
		void setSpeed(float);
		void setSpeed(float);
		void stop(void);
		void stop(void);
		void tick(void);
		void tick(void);
		void ~PathNavigation();
		void ~PathNavigation();
		void ~PathNavigation();
		void ~PathNavigation();
};
