#pragma once
class PauseScreen{
	public:
		PauseScreen(MinecraftClient &,bool,bool);
		PauseScreen(MinecraftClient &,bool,bool);
		void _buttonClicked(Button &);
		void _buttonClicked(Button &);
		void _changeFocus(void);
		void _controllerDirectionChanged(int,StickDirection);
		void _controllerDirectionChanged(int,StickDirection);
		void _controllerDirectionHeld(int,StickDirection);
		void _controllerDirectionHeld(int,StickDirection);
		void _exportLevel(void);
		void _exportLevel(void);
		void _pointerPressed(int,int);
		void _pointerPressed(int,int);
		void _pointerReleased(int,int);
		void _pointerReleased(int,int);
		void _rebuildPlayerList(void);
		void _rebuildPlayerList(void);
		void _selectNextPlayer(void);
		void _selectNextPlayer(void);
		void _selectPlayer(int);
		void _selectPreviousPlayer(void);
		void getScreenName(void);
		void getScreenName(void);
		void handleBackEvent(bool);
		void handleBackEvent(bool);
		void handleButtonRelease(short);
		void handleButtonRelease(short);
		void init(void);
		void init(void);
		void isPauseScreen(void);
		void isPauseScreen(void);
		void onEntityAdded(Entity &);
		void onEntityAdded(Entity &);
		void onEntityRemoved(Entity &);
		void onEntityRemoved(Entity &);
		void render(int,int,float);
		void render(int,int,float);
		void renderGameBehind(void);
		void renderGameBehind(void);
		void setupPositions(void);
		void setupPositions(void);
		void tick(void);
		void tick(void);
		void ~PauseScreen();
		void ~PauseScreen();
		void ~PauseScreen();
		void ~PauseScreen();
};
