#pragma once
class ScreenView{
	public:
		ScreenView(NameRegistry &,KeyboardManager &,std::shared_ptr<ScreenController>,std::shared_ptr&<UIControl>,std::unique_ptr<UIControlFactory,std::default_delete<UIControlFactory>>);
		ScreenView(NameRegistry &,KeyboardManager &,std::shared_ptr<ScreenController>,std::shared_ptr&<UIControl>,std::unique_ptr<UIControlFactory,std::default_delete<UIControlFactory>>);
		void _adjustFocusedControlToScrollRegion(void);
		void _adjustFocusedControlToScrollRegion(void);
		void _adjustScrollToFocusedControl(std::shared_ptr<UIControl> &);
		void _adjustScrollToFocusedControl(std::shared_ptr<UIControl> &);
		void _advanceToNextLegacyTab(bool);
		void _advanceToNextLegacyTab(bool);
		void _advanceToNextTab(bool);
		void _advanceToNextToggleInNavigationTabGroup(bool);
		void _advanceToNextToggleInNavigationTabGroup(bool);
		void _bindData(void);
		void _bindData(void);
		void _checkIsTextEditControl(std::shared_ptr<UIControl> &);
		void _cycleLegacyTab(void);
		void _cycleLegacyTab(void);
		void _debugRenderControl(UIRenderContext &,std::shared_ptr<UIControl> const&);
		void _debugRenderControl(UIRenderContext &,std::shared_ptr<UIControl> const&);
		void _deselectControl(void);
		void _deselectControl(void);
		void _directionChanged(DirectionId,ui::CardinalDirection);
		void _directionHeld(DirectionId,ui::CardinalDirection);
		void _findModalDescendantControl(std::shared_ptr<UIControl> &);
		void _findModalDescendantControl(std::shared_ptr<UIControl> &);
		void _findModalRootControl(void);
		void _findModalRootControl(void);
		void _fireTextChangedEvent(bool);
		void _fireTextChangedEvent(bool);
		void _forwardEventToAnimationControls(ScreenEvent const&);
		void _forwardEventToAnimationControls(ScreenEvent const&);
		void _getControllerDirection(DirectionId);
		void _getJoystickScrollingDeltaTime(void);
		void _getScreenComponent(void);
		void _growRenderAABB(std::weak_ptr<UIControl>,RectangleArea &);
		void _growRenderAABB(std::weak_ptr<UIControl>,RectangleArea &);
		void _handleDirtyVisualTree(bool);
		void _handleDirtyVisualTree(bool);
		void _handlePointerLocation(glm::detail::tvec2<float> const&,bool);
		void _handlePointerLocation(glm::detail::tvec2<float> const&,bool);
		void _handleScreenViewRefresh(void);
		void _handleScreenViewRefresh(void);
		void _handleStickScrolling(DirectionId);
		void _handleStickScrolling(DirectionId);
		void _isValidControllerStick(DirectionId);
		void _passViewCommand(void);
		void _passViewCommand(void);
		void _populateAllControlCollections(bool);
		void _populateAllControlCollections(bool);
		void _prepResevedButtonUpLists(ScreenInputContext &);
		void _prepResevedButtonUpLists(ScreenInputContext &);
		void _processControllerDirection(DirectionId);
		void _processControllerDirection(DirectionId);
		void _processEvents(ScreenInputContext &);
		void _processEvents(ScreenInputContext &);
		void _renderBatches(UIRenderContext &,ScreenRenderBatch &,RectangleArea &);
		void _renderBatches(UIRenderContext &,ScreenRenderBatch &,RectangleArea &);
		void _resetDirection(void);
		void _selectControl(std::shared_ptr<UIControl> &);
		void _selectControl(std::shared_ptr<UIControl> &);
		void _selectNextFocusObject(ui::CardinalDirection);
		void _selectNextFocusObject(ui::CardinalDirection);
		void _sendAnimationEvents(void);
		void _sendPointerHeldEvents(void);
		void _sendPointerHeldEvents(void);
		void _setKeyboardHeight(float);
		void _setKeyboardHeight(float);
		void _setupControlFactoryCallbacks(void);
		void _setupControlFactoryCallbacks(void);
		void _shouldActivateFocus(void);
		void _updateFocusControl(bool);
		void _updateFocusControl(bool);
		void _updateKeyboardVisibility(void);
		void _updateKeyboardVisibility(void);
		void _updateSelectedControl(ScreenInputContext &,short,ButtonState);
		void _updateSelectedControl(ScreenInputContext &,short,ButtonState);
		void absorbsInput(void);
		void absorbsInput(void);
		void applyInput(float);
		void applyInput(float);
		void closeOnPlayerHurt(void);
		void closeOnPlayerHurt(void);
		void getController(void);
		void getController(void);
		void getFocusedControl(void);
		void getFocusedControl(void);
		void getHeight(void);
		void getHeight(void);
		void getRenderingAABB(void);
		void getRenderingAABB(void);
		void getScreenName(void);
		void getScreenName(void);
		void getSendTelemetry(void);
		void getSendTelemetry(void);
		void getTelemetryProperty(std::string &,std::string &);
		void getTelemetryProperty(std::string &,std::string &);
		void getWidth(void);
		void getWidth(void);
		void handleButtonEvent(short,ButtonState);
		void handleButtonEvent(short,ButtonState);
		void handleCaretLocation(int);
		void handleCaretLocation(int);
		void handleCommandEvent(VoiceCommand const&);
		void handleCommandEvent(VoiceCommand const&);
		void handleControlEvent(ScreenEvent);
		void handleControlEvent(ScreenEvent);
		void handleDictationEvent(void);
		void handleDictationEvent(void);
		void handleDirection(DirectionId,float,float);
		void handleDirection(DirectionId,float,float);
		void handleGazeGestureInput(short,float,float,float);
		void handleGazeGestureInput(short,float,float,float);
		void handleHoloInputModeChanged(HoloUIInputMode);
		void handleHoloInputModeChanged(HoloUIInputMode);
		void handleInputModeChanged(InputMode);
		void handleInputModeChanged(InputMode);
		void handleLicenseChanged(void);
		void handleLicenseChanged(void);
		void handlePointerLocation(glm::detail::tvec2<float> const&);
		void handlePointerLocation(glm::detail::tvec2<float> const&);
		void handleTextChar(std::string const&,bool);
		void handleTextChar(std::string const&,bool);
		void ignoreAsTop(void);
		void ignoreAsTop(void);
		void isDebugRendering(void);
		void isDebugRendering(void);
		void isModal(void);
		void isModal(void);
		void isShowingMenu(void);
		void isShowingMenu(void);
		void lowFreqRendering(void);
		void lowFreqRendering(void);
		void onFocusGained(void);
		void onFocusGained(void);
		void onFocusLost(void);
		void onFocusLost(void);
		void onGameEventNotification(ui::GameEventNotification);
		void onGameEventNotification(ui::GameEventNotification);
		void onInternetUpdate(void);
		void onInternetUpdate(void);
		void onSetKeyboardHeight(float);
		void onSetKeyboardHeight(float);
		void render(ScreenContext &);
		void render(ScreenContext &);
		void renderGameBehind(void);
		void renderGameBehind(void);
		void renderOnlyWhenTopMost(void);
		void renderOnlyWhenTopMost(void);
		void resize(void);
		void resize(void);
		void screenDrawsLast(void);
		void screenDrawsLast(void);
		void screenIsNotFlushable(void);
		void screenIsNotFlushable(void);
		void setAssociatedBlockPos(BlockPos const&);
		void setAssociatedBlockPos(BlockPos const&);
		void setDebugRendering(bool);
		void setDebugRendering(bool);
		void setSize(glm::detail::tvec2<float>);
		void setSize(glm::detail::tvec2<float>);
		void setTextboxText(std::string const&);
		void setTextboxText(std::string const&);
		void setupAndRender(UIScreenContext &);
		void setupAndRender(UIScreenContext &);
		void shouldStealMouse(void);
		void shouldStealMouse(void);
		void terminate(void);
		void terminate(void);
		void tick(int,int);
		void tick(int,int);
		void toGUICoordinate(int,int,int &,int &);
		void toGUICoordinate(int,int,int &,int &);
		void ~ScreenView();
		void ~ScreenView();
		void ~ScreenView();
		void ~ScreenView();
		void ~ScreenView();
};
