#pragma once
class ServerPlayer{
	public:
		void function<void ();
		void function<void ();
		void _nextContainerCounter(void);
		void _scanForNewEntities(void);
		void _scanForNewEntities(void);
		void _sendQueuedChunk(ServerPlayer::QueuedChunk const&);
		void _sendQueuedChunk(ServerPlayer::QueuedChunk const&);
		void _sendQueuedChunks(void);
		void _sendQueuedChunks(void);
		void _setContainerManager(IContainerManager *);
		void _setContainerManager(IContainerManager *);
		void _updateNearbyEntities(void);
		void _updateNearbyEntities(void);
		void aiStep(void);
		void aiStep(void);
		void calculateNewChunkRadius(void);
		void changeDimension(DimensionId);
		void changeDimension(DimensionId);
		void deleteContainerManager(void);
		void deleteContainerManager(void);
		void disconnect(void);
		void disconnect(void);
		void displayLocalizableMessage(std::string const&,std::vector<std::string,std::allocator<std::string>> const&);
		void displayLocalizableMessage(std::string const&,std::vector<std::string,std::allocator<std::string>> const&);
		void doDeleteContainerManager(void);
		void doDeleteContainerManager(void);
		void getRequestedChunkRadius(void);
		void hasResource(int);
		void hasResource(int);
		void hurtArmor(int);
		void hurtArmor(int);
		void isEntityRelevant(Entity const&);
		void isEntityRelevant(Entity const&);
		void isPositionRelevant(DimensionId,BlockPos const&);
		void isPositionRelevant(DimensionId,BlockPos const&);
		void knockback(Entity *,int,float,float);
		void knockback(Entity *,int,float,float);
		void normalTick(void);
		void normalTick(void);
		void onEffectAdded(MobEffectInstance &);
		void onEffectAdded(MobEffectInstance &);
		void onEffectRemoved(MobEffectInstance &);
		void onEffectRemoved(MobEffectInstance &);
		void onEffectUpdated(MobEffectInstance const&);
		void onEffectUpdated(MobEffectInstance const&);
		void openAnvil(BlockPos const&);
		void openAnvil(BlockPos const&);
		void openBrewingStand(int,BlockPos const&);
		void openBrewingStand(int,BlockPos const&);
		void openContainer(int,BlockPos const&);
		void openContainer(int,BlockPos const&);
		void openContainer(int,EntityUniqueID const&);
		void openContainer(int,EntityUniqueID const&);
		void openDispenser(int,BlockPos const&,bool);
		void openDispenser(int,BlockPos const&,bool);
		void openEnchanter(int,BlockPos const&);
		void openEnchanter(int,BlockPos const&);
		void openFurnace(int,BlockPos const&);
		void openFurnace(int,BlockPos const&);
		void openHopper(int,BlockPos const&);
		void openHopper(int,BlockPos const&);
		void openHopper(int,EntityUniqueID const&);
		void openHopper(int,EntityUniqueID const&);
		void openHorseInventory(int,EntityUniqueID const&);
		void openHorseInventory(int,EntityUniqueID const&);
		void openPortfolio(void);
		void openPortfolio(void);
		void push(Vec3 const&);
		void push(Vec3 const&);
		void queueChunk(LevelChunk &);
		void queueChunk(LevelChunk &);
		void refreshContainer(IContainerManager &,std::vector<ItemInstance,std::allocator<ItemInstance>> const&);
		void refreshContainer(IContainerManager &,std::vector<ItemInstance,std::allocator<ItemInstance>> const&);
		void sendMobEffectPackets(void);
		void sendMobEffectPackets(void);
		void setContainerData(IContainerManager &,int,int);
		void setContainerData(IContainerManager &,int,int);
		void setGlobalPermissions(GlobalPermissionsLevel);
		void setGlobalPermissions(GlobalPermissionsLevel);
		void setPermissions(UserPermissionsLevel);
		void setPermissions(UserPermissionsLevel);
		void setPlayerGameType(GameType);
		void setPlayerGameType(GameType);
		void setPlayerInput(float,float,bool,bool);
		void setPlayerInput(float,float,bool,bool);
		void setRequestedChunkRadius(int);
		void setRequestedChunkRadius(int);
		void slotChanged(IContainerManager &,int,ItemInstance const&,bool);
		void slotChanged(IContainerManager &,int,ItemInstance const&,bool);
		void stopSleepInBed(bool,bool);
		void stopSleepInBed(bool,bool);
		void tickWorld(Tick const&);
		void tickWorld(Tick const&);
		void ~ServerPlayer();
		void ~ServerPlayer();
		void ~ServerPlayer();
		void ~ServerPlayer();
};
