#pragma once
class Skeleton{
	public:
		Skeleton(BlockSource &);
		Skeleton(BlockSource &);
		void _getAmbientSound(void);
		void _getAmbientSound(void);
		void _getDeathSound(void);
		void _getDeathSound(void);
		void _getHurtSound(void);
		void _getHurtSound(void);
		void _playStepSound(BlockPos const&,int);
		void _playStepSound(BlockPos const&,int);
		void addAdditionalSaveData(CompoundTag &);
		void addAdditionalSaveData(CompoundTag &);
		void die(EntityDamageSource const&);
		void die(EntityDamageSource const&);
		void doHurtTarget(Entity *);
		void doHurtTarget(Entity *);
		void dropDeathLoot(int);
		void dropDeathLoot(int);
		void dropRareDeathLoot(void);
		void dropRareDeathLoot(void);
		void finalizeMobSpawn(void);
		void finalizeMobSpawn(void);
		void getDeathLoot(void);
		void getDeathLoot(void);
		void getDebugText(std::vector<std::string,std::allocator<std::string>> &);
		void getDebugText(std::vector<std::string,std::allocator<std::string>> &);
		void getEntityTypeId(void);
		void getEntityTypeId(void);
		void getRidingHeight(void);
		void getRidingHeight(void);
		void getSkeletonType(void);
		void getSkeletonType(void);
		void normalTick(void);
		void normalTick(void);
		void performRangedAttack(Mob &,float);
		void performRangedAttack(Mob &,float);
		void readAdditionalSaveData(CompoundTag const&);
		void readAdditionalSaveData(CompoundTag const&);
		void registerAttributes(void);
		void registerAttributes(void);
		void rideTick(void);
		void rideTick(void);
		void setSkeletonType(Skeleton::SkeletonType);
		void setSkeletonType(Skeleton::SkeletonType);
		void setTarget(Mob *);
		void setTarget(Mob *);
		void updateSkeletonParams(void);
		void updateSkeletonParams(void);
		void useNewAi(void);
		void useNewAi(void);
		void ~Skeleton();
		void ~Skeleton();
};
