#pragma once
class StringHash{
	public:
		StringHash<char [22]>(char [22] const&);
		StringHash<char [22]>(char [22] const&);
		StringHash<char [23]>(char [23] const&);
		StringHash<char [23]>(char [23] const&);
		StringHash<char [24]>(char [24] const&);
		StringHash<char [24]>(char [24] const&);
		StringHash<char [25]>(char [25] const&);
		StringHash<char [25]>(char [25] const&);
		StringHash<char [26]>(char [26] const&);
		StringHash<char [26]>(char [26] const&);
		StringHash<char [27]>(char [27] const&);
		StringHash<char [27]>(char [27] const&);
		StringHash<char [28]>(char [28] const&);
		StringHash<char [28]>(char [28] const&);
		StringHash<char [29]>(char [29] const&);
		StringHash<char [29]>(char [29] const&);
		StringHash<char [30]>(char [30] const&);
		StringHash<char [30]>(char [30] const&);
		StringHash<char [31]>(char [31] const&);
		StringHash<char [31]>(char [31] const&);
		StringHash<char [32]>(char [32] const&);
		StringHash<char [32]>(char [32] const&);
		StringHash<char [33]>(char [33] const&);
		StringHash<char [33]>(char [33] const&);
		StringHash<char [34]>(char [34] const&);
		StringHash<char [34]>(char [34] const&);
		StringHash<char [36]>(char [36] const&);
		StringHash<char [36]>(char [36] const&);
		StringHash<char [37]>(char [37] const&);
		StringHash<char [37]>(char [37] const&);
		StringHash<char [38]>(char [38] const&);
		StringHash<char [38]>(char [38] const&);
		StringHash<char [39]>(char [39] const&);
		StringHash<char [39]>(char [39] const&);
		StringHash<char [41]>(char [41] const&);
		StringHash<char [41]>(char [41] const&);
		StringHash<char [42]>(char [42] const&);
		StringHash<char [42]>(char [42] const&);
		StringHash<char [43]>(char [43] const&);
		StringHash<char [43]>(char [43] const&);
		StringHash<char [45]>(char [45] const&);
		StringHash<char [45]>(char [45] const&);
};
