#pragma once
class TextEditComponent{
	public:
		TextEditComponent(std::shared_ptr<UIControl> &);
		TextEditComponent(std::shared_ptr<UIControl> &);
		TextEditComponent(std::shared_ptr<UIControl> &);
		void _getText(void);
		void _getText(void);
		void _updatePropertyBags(void);
		void _updatePropertyBags(void);
		void clone(std::shared_ptr<UIControl> &);
		void clone(std::shared_ptr<UIControl> &);
		void deselectControl(void);
		void deselectControl(void);
		void getCollectionIndex(void);
		void getCollectionIndex(void);
		void getConstrainedToRect(void);
		void getFont(void);
		void getGridCollectionName(void);
		void getMaxLength(void);
		void getMaxLength(void);
		void getText(void);
		void getText(void);
		void getTextEditComponentId(void);
		void getTextEditComponentId(void);
		void getTextType(void);
		void handleTextCharEvent(VisualTree &,std::string const&,bool);
		void handleTextCharEvent(VisualTree &,std::string const&,bool);
		void isNumbersOnly(void);
		void isNumbersOnly(void);
		void receive(VisualTree &,ScreenInputContext &,AnimationController &,ScreenEvent);
		void receive(VisualTree &,ScreenInputContext &,AnimationController &,ScreenEvent);
		void selectControl(void);
		void selectControl(void);
		void setCaretPosition(int);
		void setCaretPosition(int);
		void setConstrainedToRect(bool);
		void setConstrainedToRect(bool);
		void setFont(Font *);
		void setFont(Font *);
		void setGridCollectionName(std::string const&);
		void setGridCollectionName(std::string const&);
		void setLabelControl(std::shared_ptr<UIControl> &);
		void setLabelControl(std::shared_ptr<UIControl> &);
		void setMaxLength(uint);
		void setMaxLength(uint);
		void setText(std::string const&);
		void setText(std::string const&);
		void setTextEditComponentId(short);
		void setTextEditComponentId(short);
		void setTextType(TextType);
		void setTextType(TextType);
		void updateCaretBlink(float);
		void updateCaretBlink(float);
		void ~TextEditComponent();
		void ~TextEditComponent();
		void ~TextEditComponent();
		void ~TextEditComponent();
};
