#pragma once
class AnvilScreen{
	public:
		AnvilScreen(MinecraftClient &,Player &,BlockPos const&);
		AnvilScreen(MinecraftClient &,Player &,BlockPos const&);
		void _buttonClicked(Button &);
		void _buttonClicked(Button &);
		void _canMoveToAnvil(int,ItemInstance const&);
		void _canMoveToAnvil(int,ItemInstance const&);
		void _controllerDirectionChanged(int,StickDirection);
		void _controllerDirectionChanged(int,StickDirection);
		void _controllerDirectionHeld(int,StickDirection);
		void _controllerDirectionHeld(int,StickDirection);
		void _drawSlotItemAt(Tessellator &,ItemInstance const&,int,int,bool);
		void _drawSlotItemAt(Tessellator &,ItemInstance const&,int,int,bool);
		void _entityCheck(void);
		void _entityCheck(void);
		void _handleAddItem(int,ItemInstance const&);
		void _handleAddItem(int,ItemInstance const&);
		void _handleBulkItemMovementRequest(Touch::InventoryPane &);
		void _handleBulkItemMovementRequest(Touch::InventoryPane &);
		void _handleRenderPane(Touch::InventoryPane &,Tessellator &,int,int,float);
		void _moveOver(ItemInstance const&,int);
		void _moveOver(ItemInstance const&,int);
		void _pointerPressed(int,int);
		void _pointerPressed(int,int);
		void _pointerReleased(int,int);
		void _pointerReleased(int,int);
		void _renderLabels(void);
		void _renderLabels(void);
		void _selectInDirection(StickDirection);
		void _sendSlotPacket(int,ItemInstance const&);
		void _sendSlotPacket(int,ItemInstance const&);
		void _setFuelIngredientSelectedBlock(StickDirection);
		void _setIfNotSet(bool &,bool);
		void _setupInventoryPane(void);
		void _setupInventoryPane(void);
		void _takeAndClearSlot(int);
		void _takeAndClearSlot(int);
		void _updateInventoryItems(void);
		void _updateInventoryItems(void);
		void addItem(Touch::InventoryPane &,int);
		void addItem(Touch::InventoryPane &,int);
		void getItems(Touch::InventoryPane const&);
		void getItems(Touch::InventoryPane const&);
		void getScreenName(void);
		void getScreenName(void);
		void handleButtonPress(short);
		void handleButtonRelease(short);
		void handleButtonRelease(short);
		void handleTextChar(std::string const&,bool);
		void handleTextChar(std::string const&,bool);
		void init(void);
		void init(void);
		void isAllowed(int);
		void isAllowed(int);
		void onSetKeyboardHeight(float);
		void onSetKeyboardHeight(float);
		void render(int,int,float);
		void render(int,int,float);
		void setTextboxText(std::string const&);
		void setTextboxText(std::string const&);
		void setupPositions(void);
		void setupPositions(void);
		void tick(void);
		void tick(void);
		void ~AnvilScreen();
		void ~AnvilScreen();
		void ~AnvilScreen();
		void ~AnvilScreen();
};
