#pragma once
class BasePressurePlateBlock{
	public:
		BasePressurePlateBlock(std::string const&,int,Material const&);
		BasePressurePlateBlock(std::string const&,int,Material const&);
		void checkIsPathable(Entity &,BlockPos const&,BlockPos const&);
		void checkIsPathable(Entity &,BlockPos const&,BlockPos const&);
		void checkPressed(BlockSource &,BlockPos const&,int,int);
		void checkPressed(BlockSource &,BlockPos const&,int,int);
		void entityInside(BlockSource &,BlockPos const&,Entity &);
		void entityInside(BlockSource &,BlockPos const&,Entity &);
		void getAABB(BlockSource &,BlockPos const&,AABB &,int,bool,int);
		void getAABB(BlockSource &,BlockPos const&,AABB &,int,bool,int);
		void getCollisionShape(AABB &,BlockSource &,BlockPos const&,Entity *);
		void getCollisionShape(AABB &,BlockSource &,BlockPos const&,Entity *);
		void getSensitiveAABB(BlockPos const&);
		void getSensitiveAABB(BlockPos const&);
		void getTickDelay(void);
		void getTickDelay(void);
		void getVariant(int);
		void getVariant(int);
		void getVisualShape(BlockSource &,BlockPos const&,AABB &,bool);
		void getVisualShape(BlockSource &,BlockPos const&,AABB &,bool);
		void getVisualShape(uchar,AABB &,bool);
		void getVisualShape(uchar,AABB &,bool);
		void isAttachedTo(BlockSource &,BlockPos const&,BlockPos&);
		void isAttachedTo(BlockSource &,BlockPos const&,BlockPos&);
		void isRedstoneBlock(void);
		void isRedstoneBlock(void);
		void mayPlace(BlockSource &,BlockPos const&);
		void mayPlace(BlockSource &,BlockPos const&);
		void neighborChanged(BlockSource &,BlockPos const&,BlockPos const&);
		void neighborChanged(BlockSource &,BlockPos const&,BlockPos const&);
		void onLoaded(BlockSource &,BlockPos const&);
		void onLoaded(BlockSource &,BlockPos const&);
		void onPlace(BlockSource &,BlockPos const&);
		void onPlace(BlockSource &,BlockPos const&);
		void tick(BlockSource &,BlockPos const&,Random &);
		void tick(BlockSource &,BlockPos const&,Random &);
		void ~BasePressurePlateBlock();
		void ~BasePressurePlateBlock();
		void ~BasePressurePlateBlock();
		void ~BasePressurePlateBlock();
};
