#pragma once
class Block{
	public:
		Block(std::string const&,int,Material const&);
		Block(std::string const&,int,Material const&);
		void SoundType(std::string const&,float,float);
		void SoundType(std::string const&,float,float);
		void SoundType(std::string const&,std::string const&,float,float);
		void SoundType(std::string const&,std::string const&,float,float);
		void SoundType(std::string const&,std::string const&,std::string const&,float,float);
		void SoundType(std::string const&,std::string const&,std::string const&,float,float);
		void getBreakSound(void);
		void getBreakSound(void);
		void getJumpSound(void);
		void getJumpSound(void);
		void getPitch(void);
		void getPitch(void);
		void getPlaceSound(void);
		void getPlaceSound(void);
		void getStepSound(void);
		void getStepSound(void);
		void getVolume(void);
		void getVolume(void);
		void ~SoundType();
		void addAABB(AABB const&,AABB const*,std::vector<AABB,std::allocator<AABB>> &);
		void addAABB(AABB const&,AABB const*,std::vector<AABB,std::allocator<AABB>> &);
		void addAABBs(BlockSource &,BlockPos const&,AABB const*,std::vector<AABB,std::allocator<AABB>> &);
		void addAABBs(BlockSource &,BlockPos const&,AABB const*,std::vector<AABB,std::allocator<AABB>> &);
		void addCollisionShapes(BlockSource &,BlockPos const&,AABB const*,std::vector<AABB,std::allocator<AABB>> &,Entity *);
		void addCollisionShapes(BlockSource &,BlockPos const&,AABB const*,std::vector<AABB,std::allocator<AABB>> &,Entity *);
		void addProperty(BlockProperty);
		void addProperty(BlockProperty);
		void animateTick(BlockSource &,BlockPos const&,Random &);
		void animateTick(BlockSource &,BlockPos const&,Random &);
		void asItemInstance(BlockSource &,BlockPos const&,int);
		void asItemInstance(BlockSource &,BlockPos const&,int);
		void attack(Player *,BlockPos const&);
		void attack(Player *,BlockPos const&);
		void buildDescriptionName(ItemInstance const&);
		void buildDescriptionName(ItemInstance const&);
		void calcGroundFriction(Mob &,BlockPos const&);
		void calcGroundFriction(Mob &,BlockPos const&);
		void calcVariant(BlockSource &,BlockPos const&,uchar);
		void calcVariant(BlockSource &,BlockPos const&,uchar);
		void canBeBuiltOver(BlockSource &,BlockPos const&);
		void canBeBuiltOver(BlockSource &,BlockPos const&);
		void canBeSilkTouched(void);
		void canBeSilkTouched(void);
		void canHaveExtraData(void);
		void canHaveExtraData(void);
		void canInstatick(void);
		void canInstatick(void);
		void canSlide(void);
		void canSlide(void);
		void canSurvive(BlockSource &,BlockPos const&);
		void canSurvive(BlockSource &,BlockPos const&);
		void checkIsPathable(Entity &,BlockPos const&,BlockPos const&);
		void checkIsPathable(Entity &,BlockPos const&,BlockPos const&);
		void clip(BlockSource &,BlockPos const&,Vec3 const&,Vec3 const&,bool,int);
		void clip(BlockSource &,BlockPos const&,Vec3 const&,Vec3 const&,bool,int);
		void destroy(BlockSource &,BlockPos const&,int,Entity *);
		void destroy(BlockSource &,BlockPos const&,int,Entity *);
		void detachesOnPistonMove(BlockSource &,BlockPos const&);
		void detachesOnPistonMove(BlockSource &,BlockPos const&);
		void dispense(BlockSource &,Container &,int,Vec3 const&,signed char);
		void dispense(BlockSource &,Container &,int,Vec3 const&,signed char);
		void entityInside(BlockSource &,BlockPos const&,Entity &);
		void entityInside(BlockSource &,BlockPos const&,Entity &);
		void getAABB(BlockSource &,BlockPos const&,AABB &,int,bool,int);
		void getAABB(BlockSource &,BlockPos const&,AABB &,int,bool,int);
		void getBlockEntityType(void);
		void getBlockEntityType(void);
		void getCollisionShape(AABB &,BlockSource &,BlockPos const&,Entity *);
		void getCollisionShape(AABB &,BlockSource &,BlockPos const&,Entity *);
		void getColor(BlockSource &,BlockPos const&);
		void getColor(BlockSource &,BlockPos const&);
		void getColor(BlockSource &,BlockPos const&,uchar);
		void getColor(BlockSource &,BlockPos const&,uchar);
		void getColor(int);
		void getColor(int);
		void getColorForParticle(BlockSource &,BlockPos const&,int);
		void getColorForParticle(BlockSource &,BlockPos const&,int);
		void getComparatorSignal(BlockSource &,BlockPos const&,signed char,int);
		void getComparatorSignal(BlockSource &,BlockPos const&,signed char,int);
		void getCreativeCategory(void);
		void getCreativeCategory(void);
		void getDebugText(std::vector<std::string,std::allocator<std::string>> &);
		void getDebugText(std::vector<std::string,std::allocator<std::string>> &);
		void getDescriptionId(void);
		void getDescriptionId(void);
		void getDestroyProgress(Player &);
		void getDestroyProgress(Player &);
		void getDestroySpeed(void);
		void getDestroySpeed(void);
		void getDirectSignal(BlockSource &,BlockPos const&,int);
		void getDirectSignal(BlockSource &,BlockPos const&,int);
		void getExperienceDrop(Random &);
		void getExperienceDrop(Random &);
		void getExplosionResistance(Entity *);
		void getExplosionResistance(Entity *);
		void getExplosionResistance(void);
		void getExplosionResistance(void);
		void getExtraRenderLayers(void);
		void getExtraRenderLayers(void);
		void getFriction(void);
		void getFriction(void);
		void getGravity(void);
		void getGravity(void);
		void getIconYOffset(void);
		void getIconYOffset(void);
		void getLightEmission(BlockID);
		void getLightEmission(BlockID);
		void getMapColor(FullBlock const&);
		void getMapColor(FullBlock const&);
		void getMapColor(void);
		void getMapColor(void);
		void getMappedFace(signed char,int);
		void getMappedFace(signed char,int);
		void getMaterial(void);
		void getMaterial(void);
		void getMobToSpawn(BlockSource &,BlockPos const&);
		void getMobToSpawn(BlockSource &,BlockPos const&);
		void getPlacementDataValue(Mob &,BlockPos const&,signed char,Vec3 const&,int);
		void getPlacementDataValue(Mob &,BlockPos const&,signed char,Vec3 const&,int);
		void getProperties(void);
		void getProperties(void);
		void getRedstoneProperty(BlockSource &,BlockPos const&);
		void getRedstoneProperty(BlockSource &,BlockPos const&);
		void getRenderLayer(BlockSource &,BlockPos const&);
		void getRenderLayer(BlockSource &,BlockPos const&);
		void getRenderLayer(void);
		void getRenderLayer(void);
		void getResource(Random &,int,int);
		void getResource(Random &,int,int);
		void getResourceCount(Random &,int,int);
		void getResourceCount(Random &,int,int);
		void getSecondPart(BlockSource &,BlockPos const&,BlockPos&);
		void getSecondPart(BlockSource &,BlockPos const&,BlockPos&);
		void getShadeBrightness(void);
		void getShadeBrightness(void);
		void getSilkTouchItemInstance(uchar);
		void getSilkTouchItemInstance(uchar);
		void getSoundType(void);
		void getSoundType(void);
		void getSpawnResourcesAuxValue(uchar);
		void getSpawnResourcesAuxValue(uchar);
		void getThickness(void);
		void getThickness(void);
		void getTypeToSpawn(BlockSource &,EntityType,BlockPos const&);
		void getTypeToSpawn(BlockSource &,EntityType,BlockPos const&);
		void getVariant(int);
		void getVariant(int);
		void getVisualShape(BlockSource &,BlockPos const&,AABB &,bool);
		void getVisualShape(BlockSource &,BlockPos const&,AABB &,bool);
		void getVisualShape(uchar,AABB &,bool);
		void getVisualShape(uchar,AABB &,bool);
		void handleEntityInside(BlockSource &,BlockPos const&,Entity *,Vec3 &);
		void handleEntityInside(BlockSource &,BlockPos const&,Entity *,Vec3 &);
		void handleRain(BlockSource &,BlockPos const&,float);
		void handleRain(BlockSource &,BlockPos const&,float);
		void hasBlockEntity(void);
		void hasBlockEntity(void);
		void hasComparatorSignal(void);
		void hasComparatorSignal(void);
		void hasProperty(BlockProperty);
		void hasProperty(BlockProperty);
		void init(void);
		void init(void);
		void initBlocks(void);
		void initBlocks(void);
		void isAlphaTested(void);
		void isAlphaTested(void);
		void isAttachedTo(BlockSource &,BlockPos const&,BlockPos&);
		void isAttachedTo(BlockSource &,BlockPos const&,BlockPos&);
		void isContainerBlock(void);
		void isContainerBlock(void);
		void isCraftingBlock(void);
		void isCraftingBlock(void);
		void isCropBlock(void);
		void isCropBlock(void);
		void isFenceBlock(void);
		void isFenceBlock(void);
		void isHeavy(void);
		void isHeavy(void);
		void isHurtableBlock(void);
		void isHurtableBlock(void);
		void isInteractiveBlock(void);
		void isInteractiveBlock(void);
		void isObstructingChests(BlockSource &,BlockPos const&);
		void isObstructingChests(BlockSource &,BlockPos const&);
		void isRailBlock(void);
		void isRailBlock(void);
		void isRedstoneAttachable(void);
		void isRedstoneAttachable(void);
		void isRedstoneBlock(void);
		void isRedstoneBlock(void);
		void isSeasonTinted(BlockSource &,BlockPos const&);
		void isSeasonTinted(BlockSource &,BlockPos const&);
		void isSignalSource(void);
		void isSignalSource(void);
		void isSolid(void);
		void isSolid(void);
		void isSolidBlockingBlock(void);
		void isSolidBlockingBlock(void);
		void isStairBlock(void);
		void isStairBlock(void);
		void isType(Block const*);
		void isType(Block const*);
		void isUnbreakable(void);
		void isWaterBlocking(void);
		void isWaterBlocking(void);
		void lookupByName(std::string const&,bool);
		void lookupByName(std::string const&,bool);
		void mayConsumeFertilizer(BlockSource &);
		void mayConsumeFertilizer(BlockSource &);
		void mayPick(BlockSource &,int,bool);
		void mayPick(BlockSource &,int,bool);
		void mayPick(void);
		void mayPick(void);
		void mayPlace(BlockSource &,BlockPos const&);
		void mayPlace(BlockSource &,BlockPos const&);
		void mayPlace(BlockSource &,BlockPos const&,signed char);
		void mayPlace(BlockSource &,BlockPos const&,signed char);
		void mayPlaceOn(Block const&);
		void mayPlaceOn(Block const&);
		void neighborChanged(BlockSource &,BlockPos const&,BlockPos const&);
		void neighborChanged(BlockSource &,BlockPos const&,BlockPos const&);
		void onExploded(BlockSource &,BlockPos const&,Entity *);
		void onExploded(BlockSource &,BlockPos const&,Entity *);
		void onFallOn(BlockSource &,BlockPos const&,Entity *,float);
		void onFallOn(BlockSource &,BlockPos const&,Entity *,float);
		void onFertilized(BlockSource &,BlockPos const&,Player *);
		void onFertilized(BlockSource &,BlockPos const&,Player *);
		void onGraphicsModeChanged(bool,bool,bool);
		void onGraphicsModeChanged(bool,bool,bool);
		void onLoaded(BlockSource &,BlockPos const&);
		void onLoaded(BlockSource &,BlockPos const&);
		void onMove(BlockSource &,BlockPos const&,BlockPos const&);
		void onMove(BlockSource &,BlockPos const&,BlockPos const&);
		void onPlace(BlockSource &,BlockPos const&);
		void onPlace(BlockSource &,BlockPos const&);
		void onRedstoneUpdate(BlockSource &,BlockPos const&,int,bool);
		void onRedstoneUpdate(BlockSource &,BlockPos const&,int,bool);
		void onRemove(BlockSource &,BlockPos const&);
		void onRemove(BlockSource &,BlockPos const&);
		void onStepOn(Entity &,BlockPos const&);
		void onStepOn(Entity &,BlockPos const&);
		void playerDestroy(Player *,BlockPos const&,int);
		void playerDestroy(Player *,BlockPos const&,int);
		void playerWillDestroy(Player &,BlockPos const&,int);
		void playerWillDestroy(Player &,BlockPos const&,int);
		void popResource(BlockSource &,BlockPos const&,ItemInstance const&);
		void popResource(BlockSource &,BlockPos const&,ItemInstance const&);
		void prepareRender(BlockSource &,BlockPos const&);
		void prepareRender(BlockSource &,BlockPos const&);
		void randomlyModifyPosition(BlockPos const&);
		void randomlyModifyPosition(BlockPos const&);
		void randomlyModifyPosition(BlockPos const&,int &);
		void randomlyModifyPosition(BlockPos const&,int &);
		void setCategory(CreativeItemCategory);
		void setDestroyTime(float);
		void setDestroyTime(float);
		void setExplodeable(float);
		void setExplodeable(float);
		void setFriction(float);
		void setFriction(float);
		void setLightBlock(Brightness);
		void setLightBlock(Brightness);
		void setLightEmission(float);
		void setLightEmission(float);
		void setMapColor(Color const&);
		void setMapColor(Color const&);
		void setNameId(std::string const&);
		void setNameId(std::string const&);
		void setSolid(bool);
		void setSolid(bool);
		void setSoundType(Block::SoundType const&);
		void setSoundType(Block::SoundType const&);
		void setTicking(bool);
		void setTicking(bool);
		void setVisualShape(AABB const&);
		void setVisualShape(AABB const&);
		void setVisualShape(Vec3 const&,Vec3 const&);
		void setVisualShape(Vec3 const&,Vec3 const&);
		void shouldRenderFace(BlockSource &,BlockPos const&,signed char,AABB const&);
		void shouldRenderFace(BlockSource &,BlockPos const&,signed char,AABB const&);
		void shouldStopFalling(Entity &);
		void shouldStopFalling(Entity &);
		void spawnBurnResources(BlockSource &,float,float,float);
		void spawnBurnResources(BlockSource &,float,float,float);
		void spawnResources(BlockSource &,BlockPos const&,int,float,int);
		void spawnResources(BlockSource &,BlockPos const&,int,float,int);
		void teardownBlocks(void);
		void tick(BlockSource &,BlockPos const&,Random &);
		void tick(BlockSource &,BlockPos const&,Random &);
		void transformToValidBlockId(BlockID);
		void transformToValidBlockId(BlockID,BlockPos const&);
		void transformToValidBlockId(BlockID,BlockPos const&);
		void triggerEvent(BlockSource &,BlockPos const&,int,int);
		void triggerEvent(BlockSource &,BlockPos const&,int,int);
		void tryToPlace(BlockSource &,BlockPos const&,uchar);
		void tryToPlace(BlockSource &,BlockPos const&,uchar);
		void updateEntityAfterFallOn(Entity &);
		void updateEntityAfterFallOn(Entity &);
		void use(Player &,BlockPos const&);
		void use(Player &,BlockPos const&);
		void waterSpreadCausesSpawn(void);
		void waterSpreadCausesSpawn(void);
		void ~Block();
		void ~Block();
		void ~Block();
		void ~Block();
		void ~Block();
};
