#pragma once
class BrewingStandScreen{
	public:
		BrewingStandScreen(MinecraftClient &,Player &,BlockPos const&);
		BrewingStandScreen(MinecraftClient &,Player &,BlockPos const&);
		void _buttonClicked(Button &);
		void _buttonClicked(Button &);
		void _canMoveToBrewingStand(int,ItemInstance const*);
		void _canMoveToBrewingStand(int,ItemInstance const*);
		void _clearItems(void);
		void _controllerDirectionChanged(int,StickDirection);
		void _controllerDirectionChanged(int,StickDirection);
		void _controllerDirectionHeld(int,StickDirection);
		void _controllerDirectionHeld(int,StickDirection);
		void _drawSlotItemAt(Tessellator &,ItemInstance const*,int,int,bool,bool);
		void _drawSlotItemAt(Tessellator &,ItemInstance const*,int,int,bool,bool);
		void _getBrewingStandEntity(void);
		void _handleAddItem(int,ItemInstance const*);
		void _handleAddItem(int,ItemInstance const*);
		void _handleBulkItemMovementRequest(Touch::InventoryPane &);
		void _handleBulkItemMovementRequest(Touch::InventoryPane &);
		void _handleRenderPane(Touch::InventoryPane &,Tessellator &,int,int,float);
		void _moveOver(ItemInstance const*,int);
		void _moveOver(ItemInstance const*,int);
		void _recheckRecipes(void);
		void _setSelectedBlock(StickDirection);
		void _setSelectedBlock(StickDirection);
		void _setupInventoryPane(void);
		void _setupInventoryPane(void);
		void _takeAndClearSlot(int);
		void _takeAndClearSlot(int);
		void _updateItems(void);
		void _updateItems(void);
		void _updateSelectedItemDesc(void);
		void _updateSelectedItemDesc(void);
		void addItem(Touch::InventoryPane &,int);
		void addItem(Touch::InventoryPane &,int);
		void getItems(Touch::InventoryPane const&);
		void getItems(Touch::InventoryPane const&);
		void getScreenName(void);
		void getScreenName(void);
		void handleButtonPress(short);
		void handleButtonPress(short);
		void handleButtonRelease(short);
		void handleButtonRelease(short);
		void handleScrollWheel(float);
		void handleScrollWheel(float);
		void init(void);
		void init(void);
		void isAllowed(int);
		void isAllowed(int);
		void onInternetUpdate(void);
		void onInternetUpdate(void);
		void render(int,int,float);
		void render(int,int,float);
		void renderGameBehind(void);
		void renderGameBehind(void);
		void setIfNotSet(bool &,bool);
		void setupPositions(void);
		void setupPositions(void);
		void tick(void);
		void tick(void);
		void ~BrewingStandScreen();
		void ~BrewingStandScreen();
		void ~BrewingStandScreen();
		void ~BrewingStandScreen();
};
