#pragma once
class BrewingStandBlockEntity{
	public:
		BrewingStandBlockEntity(BlockPos const&);
		BrewingStandBlockEntity(BlockPos const&);
		void brew(void);
		void brew(void);
		void canBrew(void);
		void canBrew(void);
		void canPullOutItem(int,int,ItemInstance *);
		void canPullOutItem(int,int,ItemInstance *);
		void canPushInItem(int,int,ItemInstance *);
		void canPushInItem(int,int,ItemInstance *);
		void getBrewTime(void);
		void getBrewTime(void);
		void getContainerSize(void);
		void getContainerSize(void);
		void getCustomName(void);
		void getFinished(void);
		void getIngredient(void);
		void getItem(int);
		void getItem(int);
		void getMaxStackSize(void);
		void getMaxStackSize(void);
		void getName(void);
		void getName(void);
		void getPotionSlotUsage(void);
		void isFinished(void);
		void isFinished(void);
		void isSlotEmpty(int);
		void isSlotEmpty(int);
		void load(CompoundTag const&);
		void load(CompoundTag const&);
		void onChanged(BlockSource &);
		void onChanged(BlockSource &);
		void onMove(void);
		void onMove(void);
		void removeItem(int,int);
		void removeItem(int,int);
		void resetFinished(void);
		void resetFinished(void);
		void save(CompoundTag &);
		void save(CompoundTag &);
		void setBrewTime(int);
		void setBrewTime(int);
		void setCustomName(std::string &);
		void setFinished(bool);
		void setIngredient(Item *);
		void setItem(int,ItemInstance *);
		void setItem(int,ItemInstance *);
		void startOpen(Player &);
		void startOpen(Player &);
		void stopOpen(Player &);
		void stopOpen(Player &);
		void tick(BlockSource &);
		void tick(BlockSource &);
		void ~BrewingStandBlockEntity();
		void ~BrewingStandBlockEntity();
		void ~BrewingStandBlockEntity();
		void ~BrewingStandBlockEntity();
};
