#pragma once
class ChatScreen{
	public:
		ChatScreen(MinecraftClient &,bool);
		ChatScreen(MinecraftClient &,bool);
		void _buttonClicked(Button &);
		void _buttonClicked(Button &);
		void _closeWindow(void);
		void _drawChatMessages(int);
		void _getKeyboardHeight(void);
		void _guiMessagesUpdated(void);
		void _guiMessagesUpdated(void);
		void _hideKeyboard(void);
		void _isKeyboardActive(void);
		void _renderSendMessageButton(void);
		void _sendChatMessage(void);
		void _sendChatMessage(void);
		void _showKeyboard(void);
		void _updateButtons(void);
		void _updateButtons(void);
		void _updateGuiMessages(void);
		void closeOnPlayerHurt(void);
		void closeOnPlayerHurt(void);
		void getScreenName(void);
		void getScreenName(void);
		void handleBackEvent(bool);
		void handleBackEvent(bool);
		void handleButtonPress(short);
		void handleButtonPress(short);
		void handleCaretLocation(int);
		void handleCaretLocation(int);
		void handleTextChar(std::string const&,bool);
		void handleTextChar(std::string const&,bool);
		void init(void);
		void init(void);
		void onFocusGained(void);
		void onFocusGained(void);
		void onFocusLost(void);
		void onFocusLost(void);
		void render(int,int,float);
		void render(int,int,float);
		void renderGameBehind(void);
		void renderGameBehind(void);
		void setTextboxText(std::string const&);
		void setTextboxText(std::string const&);
		void setupPositions(void);
		void setupPositions(void);
		void tick(void);
		void tick(void);
		void ~ChatScreen();
		void ~ChatScreen();
		void ~ChatScreen();
		void ~ChatScreen();
};
