#pragma once
class ClientNetworkHandler{
	public:
		ClientNetworkHandler(NetworkHandler &,PacketSender &,PrivateKeyManager &,MinecraftClient &);
		ClientNetworkHandler(NetworkHandler &,PacketSender &,PrivateKeyManager &,MinecraftClient &);
		ClientNetworkHandler(NetworkHandler &,PacketSender &,PrivateKeyManager &,MinecraftClient &,Level &);
		ClientNetworkHandler(NetworkHandler &,PacketSender &,PrivateKeyManager &,MinecraftClient &,Level &);
		void allowIncomingPacketId(RakNet::RakNetGUID const&,int);
		void allowIncomingPacketId(RakNet::RakNetGUID const&,int);
		void handle(RakNet::RakNetGUID const&,AddItemPacket *);
		void handle(RakNet::RakNetGUID const&,AddItemPacket *);
		void handle(RakNet::RakNetGUID const&,ChunkRadiusUpdatedPacket *);
		void handle(RakNet::RakNetGUID const&,ChunkRadiusUpdatedPacket *);
		void handle(RakNet::RakNetGUID const&,ClientboundMapItemDataPacket *);
		void handle(RakNet::RakNetGUID const&,ClientboundMapItemDataPacket *);
		void handle(RakNet::RakNetGUID const&,CraftingDataPacket *);
		void handle(RakNet::RakNetGUID const&,CraftingDataPacket *);
		void handle(RakNet::RakNetGUID const&,EntityEventPacket *);
		void handle(RakNet::RakNetGUID const&,EntityEventPacket *);
		void handle(RakNet::RakNetGUID const&,LevelEventPacket *);
		void handle(RakNet::RakNetGUID const&,LevelEventPacket *);
		void handle(RakNet::RakNetGUID const&,PlayStatusPacket *);
		void handle(RakNet::RakNetGUID const&,PlayStatusPacket *);
		void handle(RakNet::RakNetGUID const&,ReplaceSelectedItemPacket *);
		void handle(RakNet::RakNetGUID const&,ReplaceSelectedItemPacket *);
		void handle(RakNet::RakNetGUID const&,RespawnPacket *);
		void handle(RakNet::RakNetGUID const&,RespawnPacket *);
		void handle(RakNet::RakNetGUID const&,ServerToClientHandshakePacket const*);
		void handle(RakNet::RakNetGUID const&,ServerToClientHandshakePacket const*);
		void handle(RakNet::RakNetGUID const&,SetPlayerGameTypePacket *);
		void handle(RakNet::RakNetGUID const&,SetPlayerGameTypePacket *);
		void handle(RakNet::RakNetGUID const&,TakeItemEntityPacket *);
		void handle(RakNet::RakNetGUID const&,TakeItemEntityPacket *);
		void handle(RakNet::RakNetGUID const&,TelemetryEventPacket *);
		void handle(RakNet::RakNetGUID const&,TelemetryEventPacket *);
		void handle(RakNet::RakNetGUID const&,TextPacket *);
		void handle(RakNet::RakNetGUID const&,TextPacket *);
		void handle(RakNet::RakNetGUID const&,UpdateAttributesPacket *);
		void handle(RakNet::RakNetGUID const&,UpdateAttributesPacket *);
		void handle(RakNet::RakNetGUID const&,UseItemPacket *);
		void handle(RakNet::RakNetGUID const&,UseItemPacket *);
		void onDisconnect(RakNet::RakNetGUID const&,std::string const&);
		void onDisconnect(RakNet::RakNetGUID const&,std::string const&);
		void ~ClientNetworkHandler();
		void ~ClientNetworkHandler();
		void ~ClientNetworkHandler();
		void ~ClientNetworkHandler();
};
