#pragma once
class ComparatorCapacitor{
	public:
		ComparatorCapacitor(void);
		ComparatorCapacitor(void);
		void GetRearStrength(void);
		void GetSideStrength(void);
		void addSource(CircuitSceneGraph &,CircuitTrackingInfo const&,int &,bool &);
		void addSource(CircuitSceneGraph &,CircuitTrackingInfo const&,int &,bool &);
		void allowConnection(CircuitSceneGraph &,CircuitTrackingInfo const&,bool &);
		void allowConnection(CircuitSceneGraph &,CircuitTrackingInfo const&,bool &);
		void cacheValues(CircuitSystem &,BlockPos const&);
		void cacheValues(CircuitSystem &,BlockPos const&);
		void canConsumerPower(void);
		void canConsumerPower(void);
		void clearAnalogStrength(signed char);
		void clearAnalogStrength(signed char);
		void consumePowerAnyDirection(void);
		void consumePowerAnyDirection(void);
		void evaluate(CircuitSystem &,BlockPos const&);
		void evaluate(CircuitSystem &,BlockPos const&);
		void getInstanceType(void);
		void getInstanceType(void);
		void getOldStrength(void);
		void getOldStrength(void);
		void getPoweroutDirection(void);
		void getPoweroutDirection(void);
		void isSubtractMode(void);
		void isSubtractMode(void);
		void removeSource(BlockPos const&,BaseCircuitComponent const*);
		void removeSource(BlockPos const&,BaseCircuitComponent const*);
		void setAnalogStrength(int,signed char);
		void setAnalogStrength(int,signed char);
		void setMode(ComparatorCapacitor::Mode);
		void setMode(ComparatorCapacitor::Mode);
		void updateDependencies(CircuitSceneGraph &,BlockPos const&);
		void updateDependencies(CircuitSceneGraph &,BlockPos const&);
		void ~ComparatorCapacitor();
		void ~ComparatorCapacitor();
		void ~ComparatorCapacitor();
		void ~ComparatorCapacitor();
};
