#pragma once
class Container{
	public:
		Container(ContainerType);
		Container(ContainerType);
		Container(ContainerType,std::string const&,bool);
		Container(ContainerType,std::string const&,bool);
		void addAdditionalSaveData(CompoundTag &);
		void addAdditionalSaveData(CompoundTag &);
		void addItem(ItemInstance *);
		void addItem(ItemInstance *);
		void addItemToFirstEmptySlot(ItemInstance *);
		void addItemToFirstEmptySlot(ItemInstance *);
		void addListener(ContainerListener *);
		void addListener(ContainerListener *);
		void canPullOutItem(int,int,ItemInstance *);
		void canPullOutItem(int,int,ItemInstance *);
		void canPushInItem(int,int,ItemInstance *);
		void canPushInItem(int,int,ItemInstance *);
		void dropContents(BlockSource &,Vec3 const&);
		void dropContents(BlockSource &,Vec3 const&);
		void getContainerType(void);
		void getContainerType(void);
		void getItemCount(int);
		void getItemCount(int);
		void getRandomEmptySlot(Random &);
		void getRandomEmptySlot(Random &);
		void getRedstoneSignalFromContainer(void);
		void getRedstoneSignalFromContainer(void);
		void getSlotCopies(void);
		void getSlotCopies(void);
		void getSlots(void);
		void getSlots(void);
		void hasCustomName(void);
		void hasCustomName(void);
		void readAdditionalSaveData(CompoundTag const&);
		void readAdditionalSaveData(CompoundTag const&);
		void removeListener(ContainerListener *);
		void removeListener(ContainerListener *);
		void setContainerChanged(int);
		void setContainerChanged(int);
		void setContainerMoved(void);
		void setContainerMoved(void);
		void setCustomName(std::string const&);
		void setCustomName(std::string const&);
		void ~Container();
		void ~Container();
		void ~Container();
		void ~Container();
};
