#pragma once
class ExternalServer{
	public:
		ExternalServer(ExternalServer const&);
		ExternalServer(ExternalServer const&);
		ExternalServer(int,std::string const&,std::string const&,int);
		ExternalServer(int,std::string const&,std::string const&,int);
		ExternalServer(void);
		ExternalServer(void);
		void getAddress(void);
		void getAddress(void);
		void getIP(void);
		void getId(void);
		void getId(void);
		void getMaxPlayers(void);
		void getMaxPlayers(void);
		void getName(void);
		void getName(void);
		void getPlayers(void);
		void getPlayers(void);
		void getPort(void);
		void getPort(void);
		void getProtocol(void);
		void getTitle(void);
		void getTitle(void);
		void getVersion(void);
		void getVersion(void);
		void isValidIp(std::string const&);
		void resolve(void);
		void resolve(void);
		void setAddress(std::string const&);
		void setMaxPlayers(int);
		void setMaxPlayers(int);
		void setName(std::string const&);
		void setPlayers(int);
		void setPlayers(int);
		void setPort(int);
		void setProtocol(int);
		void setProtocol(int);
		void setTitle(std::string const&);
		void setTitle(std::string const&);
		void setVersion(std::string const&);
		void setVersion(std::string const&);
		void ~ExternalServer();
		void ~ExternalServer();
};
