#pragma once
class ExternalFileLevelStorageSource{
	public:
		ExternalFileLevelStorageSource(std::string const&);
		ExternalFileLevelStorageSource(std::string const&);
		void _getFullPath(std::string const&);
		void _getFullPath(std::string const&);
		void _getFullPath(std::string const&);
		void addLevelSummaryIfExists(std::vector<LevelSummary,std::allocator<LevelSummary>> &,std::string const&);
		void addLevelSummaryIfExists(std::vector<LevelSummary,std::allocator<LevelSummary>> &,std::string const&);
		void clearAll(void);
		void clearAll(void);
		void convertLevel(std::string const&,ProgressListener *);
		void convertLevel(std::string const&,ProgressListener *);
		void copyLevelFromFilePath(std::string const&);
		void copyLevelFromFilePath(std::string const&);
		void createLevelStorage(std::string const&);
		void createLevelStorage(std::string const&);
		void deleteLevel(std::string const&);
		void deleteLevel(std::string const&);
		void getBasePath(void);
		void getBasePath(void);
		void getLevelData(std::string const&);
		void getLevelData(std::string const&);
		void getLevelList(std::vector<LevelSummary,std::allocator<LevelSummary>> &);
		void getLevelList(std::vector<LevelSummary,std::allocator<LevelSummary>> &);
		void getName(void);
		void getName(void);
		void isConvertible(std::string const&);
		void isConvertible(std::string const&);
		void isNewLevelIdAcceptable(std::string const&);
		void isNewLevelIdAcceptable(std::string const&);
		void renameLevel(std::string const&,std::string const&);
		void renameLevel(std::string const&,std::string const&);
		void requiresConversion(std::string const&);
		void requiresConversion(std::string const&);
		void setLevelData(std::string const&,LevelData const&);
		void setLevelData(std::string const&,LevelData const&);
		void ~ExternalFileLevelStorageSource();
		void ~ExternalFileLevelStorageSource();
		void ~ExternalFileLevelStorageSource();
		void ~ExternalFileLevelStorageSource();
};
