#pragma once
class FurnaceScreen{
	public:
		FurnaceScreen(MinecraftClient &,Player &,BlockPos const&);
		FurnaceScreen(MinecraftClient &,Player &,BlockPos const&);
		void _buttonClicked(Button &);
		void _buttonClicked(Button &);
		void _canMoveToFurnace(int,ItemInstance const*);
		void _canMoveToFurnace(int,ItemInstance const*);
		void _clearItems(void);
		void _controllerDirectionChanged(int,StickDirection);
		void _controllerDirectionChanged(int,StickDirection);
		void _controllerDirectionHeld(int,StickDirection);
		void _controllerDirectionHeld(int,StickDirection);
		void _drawSlotItemAt(Tessellator &,ItemInstance const*,int,int,bool);
		void _drawSlotItemAt(Tessellator &,ItemInstance const*,int,int,bool);
		void _entityCheck(void);
		void _entityCheck(void);
		void _getFurnaceEntity(void);
		void _handleAddItem(int,ItemInstance const&);
		void _handleAddItem(int,ItemInstance const&);
		void _handleBulkItemMovementRequest(Touch::InventoryPane &);
		void _handleBulkItemMovementRequest(Touch::InventoryPane &);
		void _handleRenderPane(Touch::InventoryPane &,Tessellator &,int,int,float);
		void _moveOver(ItemInstance const&,int);
		void _moveOver(ItemInstance const&,int);
		void _recheckRecipes(void);
		void _recheckRecipes(void);
		void _selectInDirection(StickDirection);
		void _setFuelIngredientSelectedBlock(StickDirection);
		void _setIfNotSet(bool &,bool);
		void _setupInventoryPane(void);
		void _setupInventoryPane(void);
		void _takeAndClearSlot(int);
		void _takeAndClearSlot(int);
		void _updateItems(void);
		void _updateItems(void);
		void _updateResult(ItemInstance const*);
		void _updateResult(ItemInstance const*);
		void addItem(Touch::InventoryPane &,int);
		void addItem(Touch::InventoryPane &,int);
		void getItems(Touch::InventoryPane const&);
		void getItems(Touch::InventoryPane const&);
		void getScreenName(void);
		void getScreenName(void);
		void grantCraftedXp(Player &,ItemInstance const*,int);
		void grantCraftedXp(Player &,ItemInstance const*,int);
		void handleButtonPress(short);
		void handleButtonRelease(short);
		void handleButtonRelease(short);
		void handleScrollWheel(float);
		void handleScrollWheel(float);
		void init(void);
		void init(void);
		void isAllowed(int);
		void isAllowed(int);
		void onInternetUpdate(void);
		void onInternetUpdate(void);
		void render(int,int,float);
		void render(int,int,float);
		void renderGameBehind(void);
		void renderGameBehind(void);
		void setupPositions(void);
		void setupPositions(void);
		void tick(void);
		void tick(void);
		void ~FurnaceScreen();
		void ~FurnaceScreen();
		void ~FurnaceScreen();
		void ~FurnaceScreen();
};
