#pragma once
class GridComponent{
	public:
		GridComponent(std::shared_ptr<UIControl> &);
		GridComponent(std::shared_ptr<UIControl> &);
		void _assignStaticGridItemIndexes(void);
		void _assignStaticGridItemIndexes(void);
		void _createGridItemAt(UIControlFactory &,std::shared_ptr<UIControl> &,int);
		void _createGridItemAt(UIControlFactory &,std::shared_ptr<UIControl> &,int);
		void clone(std::shared_ptr<UIControl> &);
		void clone(std::shared_ptr<UIControl> &);
		void getCollectionName(void);
		void getCollectionName(void);
		void getGridDimensionBinding(void);
		void getGridDimensionBinding(void);
		void getGridDimensions(void);
		void getGridDimensions(void);
		void getGridItemTemplate(void);
		void getGridItemTemplate(void);
		void getGridItemTemplateSize(void);
		void getGridRescalingType(void);
		void getGridRescalingType(void);
		void getItemBoundingBox(void);
		void getMaximumGridItems(void);
		void getMaximumGridItems(void);
		void getNeedsRescaling(void);
		void getNeedsRescaling(void);
		void isDynamic(void);
		void isDynamic(void);
		void onNotifyChildAdded(void);
		void onNotifyChildAdded(void);
		void onNotifyChildRemoved(void);
		void onNotifyChildRemoved(void);
		void reassignGridPositions(void);
		void reassignGridPositions(void);
		void refreshGridItems(UIControlFactory &);
		void refreshGridItems(UIControlFactory &);
		void setCollectionName(std::string const&);
		void setCollectionName(std::string const&);
		void setGridDimensionBinding(std::string const&);
		void setGridDimensionBinding(std::string const&);
		void setGridDimensions(glm::detail::tvec2<int> const&);
		void setGridDimensions(glm::detail::tvec2<int> const&);
		void setGridItemTemplate(std::shared_ptr<UIControl> &);
		void setGridItemTemplate(std::shared_ptr<UIControl> &);
		void setGridRescalingType(ui::OrientationType const&);
		void setGridRescalingType(ui::OrientationType const&);
		void setMaximumGridItems(int);
		void setMaximumGridItems(int);
		void ~GridComponent();
		void ~GridComponent();
		void ~GridComponent();
		void ~GridComponent();
};
