#pragma once
class GuiElementContainer{
	public:
		GuiElementContainer(bool,bool,int,int,int,int);
		GuiElementContainer(bool,bool,int,int,int,int);
		GuiElementContainer(bool,bool,int,int,int,int);
		void addChild(std::shared_ptr<GuiElement>);
		void addChild(std::shared_ptr<GuiElement>);
		void backPressed(MinecraftClient *,bool);
		void backPressed(MinecraftClient *,bool);
		void clearAll(void);
		void clearAll(void);
		void focusedMouseClicked(MinecraftClient *,int,int);
		void focusedMouseClicked(MinecraftClient *,int,int);
		void focusedMouseReleased(MinecraftClient *,int,int);
		void focusedMouseReleased(MinecraftClient *,int,int);
		void getChildren(void);
		void getChildren(void);
		void getChildren(void);
		void getChildren(void);
		void handleButtonPress(MinecraftClient *,short);
		void handleButtonPress(MinecraftClient *,short);
		void handleButtonRelease(MinecraftClient *,short);
		void handleButtonRelease(MinecraftClient *,short);
		void handleCaretLocation(int);
		void handleCaretLocation(int);
		void handleTextChar(MinecraftClient *,std::string const&,bool);
		void handleTextChar(MinecraftClient *,std::string const&,bool);
		void hasChildren(void);
		void hasChildren(void);
		void pointerPressed(MinecraftClient *,int,int);
		void pointerPressed(MinecraftClient *,int,int);
		void pointerReleased(MinecraftClient *,int,int);
		void pointerReleased(MinecraftClient *,int,int);
		void removeChild(std::shared_ptr<GuiElement>);
		void removeChild(std::shared_ptr<GuiElement>);
		void render(MinecraftClient *,int,int);
		void render(MinecraftClient *,int,int);
		void setKeyboardHeight(MinecraftClient *,float,Vec2 const&);
		void setKeyboardHeight(MinecraftClient *,float,Vec2 const&);
		void setTextboxText(std::string const&);
		void setTextboxText(std::string const&);
		void setupPositions(void);
		void setupPositions(void);
		void suppressOtherGUI(void);
		void suppressOtherGUI(void);
		void tick(MinecraftClient *);
		void tick(MinecraftClient *);
		void topRender(MinecraftClient *,int,int);
		void topRender(MinecraftClient *,int,int);
		void ~GuiElementContainer();
		void ~GuiElementContainer();
		void ~GuiElementContainer();
		void ~GuiElementContainer();
};
