#pragma once
class HellDimension{
	public:
		HellDimension(Level &);
		HellDimension(Level &);
		void getFogColor(float);
		void getFogColor(float);
		void getFogDistanceScale(void);
		void getFogDistanceScale(void);
		void getName(void);
		void getName(void);
		void getTimeOfDay(int,float);
		void getTimeOfDay(int,float);
		void init(void);
		void init(void);
		void isFoggyAt(int,int);
		void isFoggyAt(int,int);
		void isNaturalDimension(void);
		void isNaturalDimension(void);
		void isValidSpawn(int,int);
		void isValidSpawn(int,int);
		void mayRespawn(void);
		void mayRespawn(void);
		void updateLightRamp(void);
		void updateLightRamp(void);
		void ~HellDimension();
		void ~HellDimension();
		void ~HellDimension();
		void ~HellDimension();
};
