#pragma once
class IronGolem{
	public:
		IronGolem(BlockSource &);
		IronGolem(BlockSource &);
		void _getDeathSound(void);
		void _getDeathSound(void);
		void _getHurtSound(void);
		void _getHurtSound(void);
		void _playStepSound(BlockPos const&,int);
		void _playStepSound(BlockPos const&,int);
		void _serverAiMobStep(void);
		void _serverAiMobStep(void);
		void addAdditionalSaveData(CompoundTag &);
		void addAdditionalSaveData(CompoundTag &);
		void aiStep(void);
		void aiStep(void);
		void canAttack(Mob *,bool);
		void canAttack(Mob *,bool);
		void die(EntityDamageSource const&);
		void die(EntityDamageSource const&);
		void doHurtTarget(Entity *);
		void doHurtTarget(Entity *);
		void dropDeathLoot(int);
		void dropDeathLoot(int);
		void getAttackAnimationTick(void);
		void getAttackAnimationTick(void);
		void getEntityTypeId(void);
		void getEntityTypeId(void);
		void getOfferFlowerTick(void);
		void getOfferFlowerTick(void);
		void getShadowRadius(void);
		void getShadowRadius(void);
		void getVillage(void);
		void getVillage(void);
		void handleEntityEvent(EntityEvent,int);
		void handleEntityEvent(EntityEvent,int);
		void isPlayerCreated(void);
		void isPlayerCreated(void);
		void offerFlower(bool);
		void offerFlower(bool);
		void push(Entity &,bool);
		void push(Entity &,bool);
		void readAdditionalSaveData(CompoundTag const&);
		void readAdditionalSaveData(CompoundTag const&);
		void registerAttributes(void);
		void registerAttributes(void);
		void setPlayerCreated(bool);
		void setPlayerCreated(bool);
		void useNewAi(void);
		void useNewAi(void);
		void ~IronGolem();
		void ~IronGolem();
		void ~IronGolem();
		void ~IronGolem();
};
