#pragma once
class LevelRenderer{
	public:
		LevelRenderer(MinecraftClient *,std::shared_ptr<TextureAtlas>);
		LevelRenderer(MinecraftClient *,std::shared_ptr<TextureAtlas>);
		void _IsRealityModeAndInFrontOfAperture(Vec3);
		void _addMaxXEndcapMesh(Vec3 &,Vec3 &,Vec3 &);
		void _addMaxXEndcapMesh(Vec3 &,Vec3 &,Vec3 &);
		void _addMaxZEndcapMesh(Vec3 &,Vec3 &,Vec3 &);
		void _addMaxZEndcapMesh(Vec3 &,Vec3 &,Vec3 &);
		void _addMinXEndcapMesh(Vec3 &,Vec3 &,Vec3 &);
		void _addMinXEndcapMesh(Vec3 &,Vec3 &,Vec3 &);
		void _addMinZEndcapMesh(Vec3 &,Vec3 &,Vec3 &);
		void _addMinZEndcapMesh(Vec3 &,Vec3 &,Vec3 &);
		void _advancedCutawayVisibilityCulling(Vec3 const&,bool);
		void _advancedCutawayVisibilityCulling(Vec3 const&,bool);
		void _advancedVisibilityCulling(Vec3 const&,bool,ScreenCuller *);
		void _advancedVisibilityCulling(Vec3 const&,bool,ScreenCuller *);
		void _affectsTessellation(int);
		void _blockCanHaveOverlay(Block const&);
		void _buildImmediate(RenderChunk &);
		void _buildImmediate(RenderChunk &);
		void _buildShadowOverlay(void);
		void _buildShadowOverlay(void);
		void _buildShadowVolume(void);
		void _buildShadowVolume(void);
		void _buildSkyMesh(void);
		void _buildSkyMesh(void);
		void _buildStarsMesh(void);
		void _buildStarsMesh(void);
		void _buildSunAndMoonMeshes(void);
		void _buildSunAndMoonMeshes(void);
		void _buildSunAndMoonQuad(bool,int);
		void _checkAndRenderRedHitFlashForVR(float);
		void _checkPosForOneToOneClip(Vec3 const&);
		void _chooseOverlayMaterial(BlockRenderLayer);
		void _computeCutawayBounds(void);
		void _computeCutawayBounds(void);
		void _computeEyePositions(void);
		void _computeEyePositions(void);
		void _cullerIsVisible(AABB const&);
		void _cullerIsVisible(AABB const&);
		void _cutawayVisibilityCulling(Vec3 const&,bool);
		void _cutawayVisibilityCulling(Vec3 const&,bool);
		void _finishBuildingChunk(RenderChunk &);
		void _finishBuildingChunk(RenderChunk &);
		void _finishSortingChunkFaces(RenderChunk &);
		void _frustumVisibilityCulling(Vec3 const&,bool,bool);
		void _frustumVisibilityCulling(Vec3 const&,bool,bool);
		void _getBlockRenderer(void);
		void _getBlockRenderer(void);
		void _getCameraDeltaToUpdateArea(void);
		void _getOrCreateChunkAt(BlockPos const&,bool);
		void _getOrCreateChunkAt(BlockPos const&,bool);
		void _getProjectionAspectRatio(void);
		void _initResources(void);
		void _initResources(void);
		void _queueChunk(RenderChunk &,float,bool);
		void _queueChunk(RenderChunk &,float,bool);
		void _queueRenderEntitiesClient(BlockSource &,ChunkPos const&,float);
		void _queueRenderEntitiesClient(BlockSource &,ChunkPos const&,float);
		void _queueRenderEntitiesServer(BlockSource &,ChunkPos const&,float);
		void _queueRenderEntitiesServer(BlockSource &,ChunkPos const&,float);
		void _recalculateRenderDistance(void);
		void _recalculateRenderDistance(void);
		void _recreateTessellators(void);
		void _recreateTessellators(void);
		void _renderBlockEntityShadow(BlockEntity const&,float);
		void _renderBlockOverlay(BlockSource &,float,Block *,BlockPos const&);
		void _renderBlockOverlay(BlockSource &,float,Block *,BlockPos const&);
		void _renderChunkQueue(std::vector<RenderChunk *,std::allocator<RenderChunk *>> const&,TerrainLayer,bool);
		void _renderChunkQueue(std::vector<RenderChunk *,std::allocator<RenderChunk *>> const&,TerrainLayer,bool);
		void _renderCracksOverlay(BlockSource &,Block &,BlockPos const&,float);
		void _renderCracksOverlay(BlockSource &,Block &,BlockPos const&,float);
		void _renderEntityShadow(Entity const&,float);
		void _renderEntityShadow(Entity const&,float);
		void _renderShadow(float,Vec3 const&,float);
		void _renderShadow(float,Vec3 const&,float);
		void _renderStars(float);
		void _renderStars(float);
		void _renderStencilShadowOverlayCube(float);
		void _renderStencilShadowOverlayCube(float);
		void _renderSunOrMoon(float,bool);
		void _renderSunOrMoon(float,bool);
		void _renderWaterHoles(float);
		void _renderWaterHoles(float);
		void _scheduleChunkBuild(Boxed<RenderChunk> &,bool);
		void _scheduleChunkBuild(Boxed<RenderChunk> &,bool);
		void _scheduleChunkSort(Boxed<RenderChunk> &);
		void _scheduleChunkSort(Boxed<RenderChunk> &);
		void _setDirty(BlockPos const&,BlockPos const&,bool,bool);
		void _setDirty(BlockPos const&,BlockPos const&,bool,bool);
		void _setDirty(BlockPos const&,bool,bool);
		void _setDirty(Pos const&,bool,bool);
		void _setupFog(Entity const&,int,float);
		void _setupFog(Entity const&,int,float);
		void _skyDarkeningFactor(void);
		void _tryRebuild(Boxed<RenderChunk> &);
		void _tryRebuild(Boxed<RenderChunk> &);
		void _updateColumnVisibility(BlockPos const&);
		void _updateColumnVisibility(BlockPos const&);
		void _updateEndCapMesh(void);
		void _updateEndCapMesh(void);
		void addParticle(ParticleType,Vec3 const&,Vec3 const&,int);
		void addParticle(ParticleType,Vec3 const&,Vec3 const&,int);
		void allChanged(void);
		void allChanged(void);
		void bobHurt(Matrix &,float);
		void bobHurt(Matrix &,float);
		void bobView(Matrix &,float);
		void bobView(Matrix &,float);
		void buildUnitCube(void);
		void buildUnitCube(void);
		void computeCameraPos(float);
		void computeCameraPos(float);
		void gatherStats1(void);
		void getAmbientBrightness(void);
		void getAmbientBrightness(void);
		void getCameraPosFromEntity(float,Entity const&);
		void getCameraPosFromEntity(float,Entity const&);
		void getCutawayBounds(Vec3 &,Vec3 &);
		void getCutawayBounds(Vec3 &,Vec3 &);
		void getFogBrightness(float);
		void getFov(float,bool);
		void getFov(float,bool);
		void getNightVisionScale(Mob const&,float);
		void getNightVisionScale(Mob const&,float);
		void initializeEndcapLookupTexture(bool);
		void initializeEndcapLookupTexture(bool);
		void isAABBVisible(AABB const&);
		void isAABBVisible(AABB const&);
		void isBlockVisible(BlockPos const&);
		void levelEvent(LevelEvent,Vec3 const&,int);
		void levelEvent(LevelEvent,Vec3 const&,int);
		void moveCameraToPlayer(Matrix &,float);
		void moveCameraToPlayer(Matrix &,float);
		void onAppResumed(void);
		void onAppResumed(void);
		void onAppSuspended(void);
		void onAppSuspended(void);
		void onAreaChanged(BlockSource &,BlockPos const&,BlockPos const&);
		void onAreaChanged(BlockSource &,BlockPos const&,BlockPos const&);
		void onBlockChanged(BlockSource &,BlockPos const&,FullBlock,FullBlock,int);
		void onBlockChanged(BlockSource &,BlockPos const&,FullBlock,FullBlock,int);
		void onBrightnessChanged(BlockSource &,BlockPos const&);
		void onBrightnessChanged(BlockSource &,BlockPos const&);
		void onLowMemory(void);
		void onLowMemory(void);
		void onNewChunkFor(Player &,LevelChunk &);
		void onNewChunkFor(Player &,LevelChunk &);
		void onStereoOptionChanged(void);
		void onStereoOptionChanged(void);
		void onViewRadiusChanged(bool);
		void onViewRadiusChanged(bool);
		void playSound(Entity const&,EntityLocation,std::string const&,float,float);
		void playSound(Entity const&,EntityLocation,std::string const&,float,float);
		void playSound(std::string const&,Vec3 const&,float,float);
		void playSound(std::string const&,Vec3 const&,float,float);
		void renderChunks(TerrainLayer,float,bool);
		void renderClouds(float);
		void renderClouds(float);
		void renderCracks(BlockSource &,BlockPos const&,float,float);
		void renderCracks(BlockSource &,BlockPos const&,float,float);
		void renderEndCaps(void);
		void renderEndCaps(void);
		void renderEntities(float);
		void renderEntities(float);
		void renderHitSelect(BlockSource &,BlockPos const&,float,bool);
		void renderHitSelect(BlockSource &,BlockPos const&,float,bool);
		void renderLevel(Entity &,FrustumCuller &,FrustumCuller &,float,float);
		void renderLevel(Entity &,FrustumCuller &,FrustumCuller &,float,float);
		void renderNameTags(float);
		void renderNameTags(float);
		void renderShadows(std::multimap<EntityRendererId,Entity *,std::less<EntityRendererId>,std::allocator<std::pair<EntityRendererId const,Entity *>>> const&,std::vector<BlockEntity *,std::allocator<BlockEntity *>> const&,float);
		void renderShadows(std::multimap<EntityRendererId,Entity *,std::less<EntityRendererId>,std::allocator<std::pair<EntityRendererId const,Entity *>>> const&,std::vector<BlockEntity *,std::allocator<BlockEntity *>> const&,float);
		void renderSky(Entity &,float);
		void renderSky(Entity &,float);
		void renderWeather(float);
		void setDestroyProgress(BlockPos const&,float);
		void setDestroyProgress(BlockPos const&,float);
		void setDimension(Dimension *,bool,bool);
		void setDimension(Dimension *,bool,bool);
		void setLevel(Level *);
		void setLevel(Level *);
		void setupCamera(float,int);
		void setupCamera(float,int);
		void setupClearColor(float);
		void setupClearColor(float);
		void startFrame(FrustumCuller &,FrustumCuller &,float,float);
		void startFrame(FrustumCuller &,FrustumCuller &,float,float);
		void takePicture(TextureData &,Entity *,Entity *,bool,std::string const&);
		void takePicture(TextureData &,Entity *,Entity *,bool,std::string const&);
		void tick(void);
		void tick(void);
		void tickFov(void);
		void tickRain(void);
		void tickRain(void);
		void updateChunksFaceSortState(BlockPos const&,BlockPos const&,Vec3 const&);
		void updateChunksFaceSortState(BlockPos const&,BlockPos const&,Vec3 const&);
		void updateFarChunksDistance(void);
		void updateFarChunksDistance(void);
		void updateViewArea(Entity &,float);
		void updateViewArea(Entity &,float);
		void ~LevelRenderer();
		void ~LevelRenderer();
		void ~LevelRenderer();
		void ~LevelRenderer();
};
