#pragma once
class MinecraftInputHandler{
	public:
		MinecraftInputHandler(MinecraftClient &);
		MinecraftInputHandler(MinecraftClient &);
		void _interactWithEntity(void);
		void _interactWithEntity(void);
		void _interactWithItem(void);
		void _loadVoiceMappings(std::vector<VoiceCommandData,std::allocator<VoiceCommandData>> &);
		void _loadVoiceMappings(std::vector<VoiceCommandData,std::allocator<VoiceCommandData>> &);
		void _registerButtonMappings(void);
		void _registerInputHandlers(void);
		void _registerInputHandlers(void);
		void _registerMenuButton(std::string const&,bool);
		void _registerMenuButton(std::string const&,bool);
		void _registerRemappingNames(void);
		void _registerRemappingNames(void);
		void _registerVoiceMappings(void);
		void _registerVoiceMappings(void);
		void allowInteract(void);
		void allowInteract(void);
		void allowPicking(void);
		void allowPicking(void);
		void canInteract(void);
		void canInteract(void);
		void clearInputDeviceQueues(void);
		void clearInputDeviceQueues(void);
		void getBindingFactory(void);
		void getBindingFactory(void);
		void getBoatExitText(void);
		void getCurrentInputMapping(void);
		void getCurrentInputMapping(void);
		void getCurrentInputMode(void);
		void getCurrentInputMode(void);
		void getCursorPos(float &,float &);
		void getCursorPos(float &,float &);
		void getHoloUIInputMode(void);
		void getHoloUIInputMode(void);
		void getInputEventQueue(void);
		void getInteractText(void);
		void getLastGameMode(void);
		void getLastHoloUIMode(void);
		void getMoveTurnInput(void);
		void getMoveTurnInput(void);
		void getNameId(std::string const&);
		void getNameId(std::string const&);
		void getNameRegistry(void);
		void getNameRegistry(void);
		void hasMobEffects(void);
		void hasToast(void);
		void isCreativeMode(void);
		void isMoving(void);
		void isMoving(void);
		void isMovingForward(void);
		void isSneaking(void);
		void onConfigChanged(Config const&);
		void onConfigChanged(Config const&);
		void onMobEffectsChanged(MobEffectsLayout const&);
		void onMobEffectsChanged(MobEffectsLayout const&);
		void onToastChanged(RectangleArea const&);
		void onToastChanged(RectangleArea const&);
		void popInputMapping(void);
		void popInputMapping(void);
		void pushGamepadMappingMode(void);
		void pushGamepadMappingMode(void);
		void pushInputMapping(bool);
		void pushInputMapping(bool);
		void render(void);
		void render(void);
		void resetPlayerMovement(void);
		void resetPlayerMovement(void);
		void resetPlayerState(void);
		void resetPlayerState(void);
		void setSuspendInput(bool);
		void setSuspendInput(bool);
		void showBoatExit(void);
		void showBoatExit(void);
		void showJumpButton(void);
		void tick(void);
		void tick(void);
		void updateHoloUIInputMode(HoloUIInputMode);
		void updateHoloUIInputMode(HoloUIInputMode);
		void updateInputMode(GamePlayInputMode);
		void updateInputMode(GamePlayInputMode);
		void updateInteractActiveState(bool);
		void updateInteractActiveState(bool);
		void updatePlayerState(Player const&);
		void updatePlayerState(Player const&);
		void useFreeformPickDirection(void);
		void useFreeformPickDirection(void);
		void ~MinecraftInputHandler();
		void ~MinecraftInputHandler();
		void ~MinecraftInputHandler();
		void ~MinecraftInputHandler();
};
