#pragma once
class Minecraft{
	public:
		Minecraft(GameCallbacks &,SkinInfoFactory &,Vibration &,SoundPlayer &,Whitelist const&,std::string const&,std::chrono::duration<long long,std::ratio<1ll,1ll>>);
		Minecraft(GameCallbacks &,SkinInfoFactory &,Vibration &,SoundPlayer &,Whitelist const&,std::string const&,std::chrono::duration<long long,std::ratio<1ll,1ll>>);
		void activateWhitelist(void);
		void createGameMode(GameType,Level &);
		void createGameMode(GameType,Level &);
		void createLevel(std::string const&,std::string const&,LevelSettings const&);
		void createLevel(std::string const&,std::string const&,LevelSettings const&);
		void disconnectClient(RakNet::RakNetGUID const&,std::string const&);
		void disconnectClient(RakNet::RakNetGUID const&,std::string const&);
		void getCommandParser(void);
		void getCommandParser(void);
		void getGameMode(void);
		void getGameMode(void);
		void getLevel(void);
		void getLevel(void);
		void getLevelSource(void);
		void getLevelSource(void);
		void getNetEventCallback(void);
		void getNetEventCallback(void);
		void getNetworkHandler(void);
		void getNetworkHandler(void);
		void getNetworkStatistics(void);
		void getNetworkStatistics(void);
		void getPacketSender(void);
		void getPacketSender(void);
		void getServerLocator(void);
		void getServerLocator(void);
		void getServerName(void);
		void getServerName(void);
		void getServerNetworkHandler(void);
		void getServerNetworkHandler(void);
		void getTimer(void);
		void getTimer(void);
		void getUser(void);
		void getUser(void);
		void hostMultiplayer(std::unique_ptr<Level,std::default_delete<Level>>,std::unique_ptr<GameMode,std::default_delete<GameMode>>,Player *,std::unique_ptr<NetEventCallback,std::default_delete<NetEventCallback>>,int,bool,bool,std::string,int,int,int);
		void hostMultiplayer(std::unique_ptr<Level,std::default_delete<Level>>,std::unique_ptr<GameMode,std::default_delete<GameMode>>,Player *,std::unique_ptr<NetEventCallback,std::default_delete<NetEventCallback>>,int,bool,bool,std::string,int,int,int);
		void init(std::string const&,bool);
		void init(std::string const&,bool);
		void initAsDedicatedServer(void);
		void initAsDedicatedServer(void);
		void isInitialized(void);
		void isModded(void);
		void isModded(void);
		void isOnlineClient(void);
		void isOnlineClient(void);
		void onClientStartedLevel(std::unique_ptr<Level,std::default_delete<Level>>);
		void onClientStartedLevel(std::unique_ptr<Level,std::default_delete<Level>>);
		void resetGameSession(void);
		void restartMultiplayerHost(int,int,int);
		void restartMultiplayerHost(int,int,int);
		void setGameModeReal(GameType);
		void setGameModeReal(GameType);
		void setLeaveGame(void);
		void setupServerCommands(void);
		void startClientGame(std::unique_ptr<NetEventCallback,std::default_delete<NetEventCallback>>);
		void startClientGame(std::unique_ptr<NetEventCallback,std::default_delete<NetEventCallback>>);
		void stopGame(void);
		void stopGame(void);
		void teardown(void);
		void teardown(void);
		void tick(int,int);
		void tick(int,int);
		void update(void);
		void update(void);
		void validateLevel(std::string const&,std::string const&,LevelSettings const&);
		void validateLevel(std::string const&,std::string const&,LevelSettings const&);
		void ~Minecraft();
		void ~Minecraft();
};
