#pragma once
class Mob{
	public:
		Mob(BlockSource &);
		Mob(BlockSource &);
		Mob(Level &);
		Mob(Level &);
		void _addSpeedBonus(mce::UUID const&,std::string const&,float);
		void _addSpeedBonus(mce::UUID const&,std::string const&,float);
		void _applyRidingRotationLimits(void);
		void _applyRidingRotationLimits(void);
		void _ctor(void);
		void _ctor(void);
		void _doSprintParticleEffect(void);
		void _doSprintParticleEffect(void);
		void _getAmbientSound(void);
		void _getAmbientSound(void);
		void _getDeathSound(void);
		void _getDeathSound(void);
		void _getHurtSound(void);
		void _getHurtSound(void);
		void _getSoundVolume(void);
		void _getSoundVolume(void);
		void _init(void);
		void _init(void);
		void _isPersistent(void);
		void _isPersistent(void);
		void _pickUpItem(ItemEntity &);
		void _pickUpItem(ItemEntity &);
		void _playStepSound(BlockPos const&,int);
		void _playStepSound(BlockPos const&,int);
		void _removeSpeedBonus(mce::UUID const&);
		void _removeSpeedBonus(mce::UUID const&);
		void _removeWhenFarAway(void);
		void _removeWhenFarAway(void);
		void _sendDirtyMobData(void);
		void _sendDirtyMobData(void);
		void _serverAiMobStep(void);
		void _serverAiMobStep(void);
		void _updateSprintingState(void);
		void actuallyHurt(int,EntityDamageSource const*);
		void actuallyHurt(int,EntityDamageSource const*);
		void addAdditionalSaveData(CompoundTag &);
		void addAdditionalSaveData(CompoundTag &);
		void addEffect(MobEffectInstance const&);
		void addEffect(MobEffectInstance const&);
		void aiStep(void);
		void aiStep(void);
		void animateHurt(void);
		void animateHurt(void);
		void applyFinalFriction(float);
		void applyFinalFriction(float);
		void ate(void);
		void ate(void);
		void baseTick(void);
		void baseTick(void);
		void buildDebugInfo(std::string &);
		void buildDebugInfo(std::string &);
		void calcMoveRelativeSpeed(Mob::TravelType);
		void calcMoveRelativeSpeed(Mob::TravelType);
		void canAddRider(Entity &);
		void canAddRider(Entity &);
		void canAttack(Mob*,bool);
		void canAttack(Mob*,bool);
		void canBeAffected(MobEffectInstance const&);
		void canBeAffected(MobEffectInstance const&);
		void canBeControlledByRider(void);
		void canBeControlledByRider(void);
		void canInteractWith(Player &);
		void canInteractWith(Player &);
		void canPickickUpLoot(void);
		void canPickickUpLoot(void);
		void canSee(Entity const&);
		void canSee(Entity const&);
		void canSpawn(bool);
		void canSpawn(bool);
		void causeFallDamage(float);
		void causeFallDamage(float);
		void checkDespawn(Mob*);
		void checkDespawn(void);
		void checkDespawn(void);
		void die(EntityDamageSource const&);
		void die(EntityDamageSource const&);
		void doFireHurt(int);
		void doFireHurt(int);
		void doHurtTarget(Entity *);
		void doHurtTarget(Entity *);
		void drop(ItemInstance const*,bool);
		void drop(ItemInstance const*,bool);
		void dropAllArmor(void);
		void dropAllArmor(void);
		void dropAllGear(int);
		void dropAllGear(int);
		void dropDeathLoot(int);
		void dropDeathLoot(int);
		void dropHeldItem(void);
		void dropHeldItem(void);
		void dropRareDeathLoot(void);
		void dropRareDeathLoot(void);
		void feedMob(int);
		void feedMob(int);
		void finalizeMobSpawn(void);
		void finalizeMobSpawn(void);
		void getActiveEffectCount(void);
		void getActiveEffectCount(void);
		void getAllArmor(void);
		void getAllArmor(void);
		void getAllArmor(void);
		void getAllArmor(void);
		void getAllEffects(void);
		void getAllEffects(void);
		void getAmbientSoundInterval(void);
		void getAmbientSoundInterval(void);
		void getArmor(ArmorSlot);
		void getArmor(ArmorSlot);
		void getArmorCoverPercentage(void);
		void getArmorCoverPercentage(void);
		void getArmorTypeHash(void);
		void getArmorTypeHash(void);
		void getArmorValue(void);
		void getArmorValue(void);
		void getAttackAnim(float);
		void getAttackAnim(float);
		void getAttribute(Attribute const&);
		void getAttribute(Attribute const&);
		void getAttributes(void);
		void getAttributes(void);
		void getCarriedItem(void);
		void getCarriedItem(void);
		void getCurrentSwingDuration(void);
		void getCurrentSwingDuration(void);
		void getDamageAfterArmorAbsorb(EntityDamageSource const&,int);
		void getDamageAfterArmorAbsorb(EntityDamageSource const&,int);
		void getDamageAfterMagicAbsorb(EntityDamageSource const&,int);
		void getDamageAfterMagicAbsorb(EntityDamageSource const&,int);
		void getDeathLoot(void);
		void getDeathLoot(void);
		void getEffect(MobEffect const&);
		void getEffect(MobEffect const&);
		void getEquipmentCount(void);
		void getEquipmentCount(void);
		void getExperienceReward(void);
		void getExperienceReward(void);
		void getHeadHeight(void);
		void getHeadHeight(void);
		void getHealth(void);
		void getHealth(void);
		void getInteractText(Player &);
		void getInteractText(Player &);
		void getItemInHandIcon(ItemInstance const*,int);
		void getItemInHandIcon(ItemInstance const*,int);
		void getItemUseDuration(void);
		void getItemUseDuration(void);
		void getJumpControl(void);
		void getJumpControl(void);
		void getJumpPower(void);
		void getJumpPower(void);
		void getLastHurtByMob(void);
		void getLastHurtByMob(void);
		void getLastHurtByPlayer(void);
		void getLastHurtByPlayer(void);
		void getLastHurtMob(void);
		void getLastHurtMob(void);
		void getLastHurtMobTimestamp(void);
		void getLastHurtMobTimestamp(void);
		void getLookControl(void);
		void getLookControl(void);
		void getLootCount(int,int);
		void getLootCount(int,int);
		void getMaxHeadXRot(void);
		void getMaxHeadXRot(void);
		void getMaxHealth(void);
		void getMaxHealth(void);
		void getMeleeKnockbackBonus(void);
		void getMeleeKnockbackBonus(void);
		void getMeleeWeaponDamageBonus(Mob*);
		void getMeleeWeaponDamageBonus(Mob*);
		void getMoveControl(void);
		void getMoveControl(void);
		void getMutableAttribute(Attribute const&);
		void getMutableAttribute(Attribute const&);
		void getNavigation(void);
		void getNavigation(void);
		void getSensing(void);
		void getSensing(void);
		void getSpeed(void);
		void getSpeed(void);
		void getTarget(void);
		void getTarget(void);
		void getTravelType(void);
		void getTravelType(void);
		void getVoicePitch(void);
		void getVoicePitch(void);
		void getXxa(void);
		void getXxa(void);
		void getYHeadRot(void);
		void getYHeadRot(void);
		void getYya(void);
		void getYya(void);
		void handleEntityEvent(EntityEvent,int);
		void handleEntityEvent(EntityEvent,int);
		void hasAnyEffects(void);
		void hasAnyEffects(void);
		void hasAttributeBuff(AttributeBuffType);
		void hasEffect(MobEffect const&);
		void hasEffect(MobEffect const&);
		void heal(int);
		void heal(int);
		void healEffects(int);
		void healEffects(int);
		void hurt(EntityDamageSource const&,int);
		void hurt(EntityDamageSource const&,int);
		void hurtArmor(int);
		void hurtArmor(int);
		void hurtEffects(EntityDamageSource const&,int);
		void hurtEffects(EntityDamageSource const&,int);
		void incrementArrowCount(int);
		void incrementArrowCount(int);
		void interactWithPlayer(Player &);
		void interactWithPlayer(Player &);
		void isAlive(void);
		void isAlive(void);
		void isAlliedTo(Mob*);
		void isAlliedTo(Mob*);
		void isBaby(void);
		void isBaby(void);
		void isImmobile(void);
		void isImmobile(void);
		void isInvertedHealAndHarm(void);
		void isInvertedHealAndHarm(void);
		void isLookingAtAnEntity(void);
		void isLookingAtAnEntity(void);
		void isPickable(void);
		void isPickable(void);
		void isPushable(void);
		void isPushable(void);
		void isShootable(void);
		void isShootable(void);
		void isSleeping(void);
		void isSleeping(void);
		void isSneaking(void);
		void isSneaking(void);
		void isSprinting(void);
		void isSprinting(void);
		void jumpFromGround(void);
		void jumpFromGround(void);
		void knockback(Entity *,int,float,float);
		void knockback(Entity *,int,float,float);
		void lerpTo(Vec3 const&,Vec2 const&,int);
		void lerpTo(Vec3 const&,Vec2 const&,int);
		void loadArmor(ListTag const*);
		void lookAt(Entity *,float,float);
		void lookAt(Entity *,float,float);
		void newServerAiStep(void);
		void newServerAiStep(void);
		void normalTick(void);
		void normalTick(void);
		void onEffectAdded(MobEffectInstance &);
		void onEffectAdded(MobEffectInstance &);
		void onEffectRemoved(MobEffectInstance &);
		void onEffectRemoved(MobEffectInstance &);
		void onEffectUpdated(MobEffectInstance const&);
		void onEffectUpdated(MobEffectInstance const&);
		void onLadder(bool);
		void onLadder(bool);
		void outOfWorld(void);
		void outOfWorld(void);
		void performRangedAttack(Mob&,float);
		void performRangedAttack(Mob&,float);
		void playAmbientSound(void);
		void playAmbientSound(void);
		void playerTouch(Player &);
		void playerTouch(Player &);
		void postInit(void);
		void postInit(void);
		void pushEntities(void);
		void pushEntities(void);
		void readAdditionalSaveData(CompoundTag const&);
		void readAdditionalSaveData(CompoundTag const&);
		void reallyDrop(std::unique_ptr<ItemEntity,std::default_delete<ItemEntity>>);
		void registerAttributes(void);
		void registerAttributes(void);
		void removeAllEffects(void);
		void removeAllEffects(void);
		void removeEffect(int);
		void removeEffect(int);
		void removeEffectNoUpdate(int);
		void removeEffectParticles(void);
		void resetAttributes(void);
		void resetAttributes(void);
		void resolveDeathLoot(int);
		void resolveDeathLoot(int);
		void rideTick(void);
		void rideTick(void);
		void saveArmor(void);
		void saveArmor(void);
		void sendInventory(void);
		void sendInventory(void);
		void serializationSetHealth(int);
		void serializationSetHealth(int);
		void setArmor(ArmorSlot,ItemInstance const*);
		void setArmor(ArmorSlot,ItemInstance const*);
		void setCanPickUpLoot(bool);
		void setCanPickUpLoot(bool);
		void setCarriedItem(ItemInstance const&);
		void setCarriedItem(ItemInstance const&);
		void setInvisible(bool);
		void setInvisible(bool);
		void setJumpVelRedux(bool);
		void setJumpVelRedux(bool);
		void setJumping(bool);
		void setJumping(bool);
		void setLastHurtByMob(Mob*);
		void setLastHurtByMob(Mob*);
		void setLastHurtByPlayer(Player *);
		void setLastHurtByPlayer(Player *);
		void setLastHurtMob(Entity *);
		void setLastHurtMob(Entity *);
		void setOnFire(int);
		void setOnFire(int);
		void setPersistent(void);
		void setPersistent(void);
		void setRiderLockedBodyRot(float);
		void setRiderLockedBodyRot(float);
		void setRiderRotLimit(float);
		void setRiderRotLimit(float);
		void setSneaking(bool);
		void setSneaking(bool);
		void setSpeed(float);
		void setSpeed(float);
		void setSprinting(bool);
		void setSprinting(bool);
		void setSurfaceMob(bool);
		void setSurfaceMob(bool);
		void setTarget(Mob*);
		void setTarget(Mob*);
		void setYHeadRot(float);
		void setYHeadRot(float);
		void setYya(float);
		void setYya(float);
		void shouldDespawn(void);
		void shouldDespawn(void);
		void spawnAnim(void);
		void spawnAnim(void);
		void spawnEatParticles(ItemInstance const&,int);
		void spawnEatParticles(ItemInstance const&,int);
		void stopRiding(bool,bool);
		void stopRiding(bool,bool);
		void swing(void);
		void swing(void);
		void teleportTo(Vec3 const&);
		void teleportTo(Vec3 const&);
		void tickAttributes(void);
		void tickEffects(void);
		void tickEffects(void);
		void tickLeash(void);
		void tickLeash(void);
		void travel(float,float);
		void travel(float,float);
		void updateAi(void);
		void updateAi(void);
		void updateAttackAnim(void);
		void updateAttackAnim(void);
		void updateInvisibilityStatus(void);
		void updateInvisibilityStatus(void);
		void updateMobId(EntityUniqueID &);
		void updateWalkAnim(void);
		void updateWalkAnim(void);
		void useNewAi(void);
		void useNewAi(void);
		void ~Mob();
		void ~Mob();
		void ~Mob();
		void ~Mob();
};
