#pragma once
class Ocelot{
	public:
		Ocelot(BlockSource &);
		Ocelot(BlockSource &);
		Ocelot(BlockSource &);
		void _getAmbientSound(void);
		void _getAmbientSound(void);
		void _getDeathSound(void);
		void _getDeathSound(void);
		void _getHurtSound(void);
		void _getHurtSound(void);
		void _removeWhenFarAway(void);
		void _removeWhenFarAway(void);
		void _serverAiMobStep(void);
		void _serverAiMobStep(void);
		void addAdditionalSaveData(CompoundTag &);
		void addAdditionalSaveData(CompoundTag &);
		void canAddRider(Entity &);
		void canAddRider(Entity &);
		void canInteractWith(Player &);
		void canInteractWith(Player &);
		void canMate(Animal const&);
		void canMate(Animal const&);
		void causeFallDamage(float);
		void causeFallDamage(float);
		void createBreedOffspring(Animal &);
		void createBreedOffspring(Animal &);
		void doHurtTarget(Entity *);
		void doHurtTarget(Entity *);
		void finalizeMobSpawn(void);
		void finalizeMobSpawn(void);
		void getBaseSpeed(void);
		void getBaseSpeed(void);
		void getCatType(void);
		void getCatType(void);
		void getEntityTypeId(void);
		void getEntityTypeId(void);
		void getInteractText(Player &);
		void getInteractText(Player &);
		void getRideHeight(void);
		void getRideHeight(void);
		void hurt(EntityDamageSource const&,int);
		void hurt(EntityDamageSource const&,int);
		void interactWithPlayer(Player &);
		void interactWithPlayer(Player &);
		void isFood(ItemInstance const&);
		void isFood(ItemInstance const&);
		void postProcessOffspring(Animal &,Animal &);
		void postProcessOffspring(Animal &,Animal &);
		void readAdditionalSaveData(CompoundTag const&);
		void readAdditionalSaveData(CompoundTag const&);
		void registerAttributes(void);
		void registerAttributes(void);
		void setCatType(CatType);
		void setOwner(EntityUniqueID);
		void setOwner(EntityUniqueID);
		void useNewAi(void);
		void useNewAi(void);
		void ~Ocelot();
		void ~Ocelot();
};
