#pragma once
class PathfinderMob{
	public:
		PathfinderMob(BlockSource &);
		PathfinderMob(BlockSource &);
		void _getWalkTargetValue(BlockPos const&);
		void _getWalkTargetValue(BlockPos const&);
		void addAdditionalSaveData(CompoundTag &);
		void addAdditionalSaveData(CompoundTag &);
		void canSpawn(bool);
		void canSpawn(bool);
		void checkCantSeeTarget(Entity *,float);
		void checkCantSeeTarget(Entity *,float);
		void checkHurtTarget(Entity *,float);
		void checkHurtTarget(Entity *,float);
		void clearRestriction(void);
		void clearRestriction(void);
		void findAttackTarget(void);
		void findAttackTarget(void);
		void findRandomStrollLocation(void);
		void findRandomStrollLocation(void);
		void getAttackTarget(void);
		void getAttackTarget(void);
		void getNoActionTime(void);
		void getNoActionTime(void);
		void getRestrictCenter(void);
		void getRestrictCenter(void);
		void getRestrictRadius(void);
		void getRestrictRadius(void);
		void getTempted(void);
		void getTempted(void);
		void hasRestriction(void);
		void hasRestriction(void);
		void isPathFinding(void);
		void isPathFinding(void);
		void isWithinRestriction(BlockPos const&);
		void isWithinRestriction(BlockPos const&);
		void isWithinRestriction(void);
		void isWithinRestriction(void);
		void readAdditionalSaveData(CompoundTag const&);
		void readAdditionalSaveData(CompoundTag const&);
		void restrictTo(BlockPos const&,float);
		void restrictTo(BlockPos const&,float);
		void setAttackTarget(Entity *);
		void setAttackTarget(Entity *);
		void setTempted(bool);
		void setTempted(bool);
		void shouldHoldGround(void);
		void shouldHoldGround(void);
		void tickLeash(void);
		void tickLeash(void);
		void updateAi(void);
		void updateAi(void);
		void ~PathfinderMob();
		void ~PathfinderMob();
		void ~PathfinderMob();
		void ~PathfinderMob();
};
