#pragma once
class SpriteComponent{
	public:
		SpriteComponent(std::shared_ptr<UIControl> &);
		SpriteComponent(std::shared_ptr<UIControl> &);
		SpriteComponent(std::shared_ptr<UIControl> &);
		void _debugPixelSizeCheck(void);
		void _drawClipped(UIRenderContext &,glm::detail::tvec2<float> const&,glm::detail::tvec2<float> const&,glm::detail::tvec2<float> const&,glm::detail::tvec2<float> const&);
		void _drawClipped(UIRenderContext &,glm::detail::tvec2<float> const&,glm::detail::tvec2<float> const&,glm::detail::tvec2<float> const&,glm::detail::tvec2<float> const&);
		void _drawTiled(UIRenderContext &,glm::detail::tvec2<float> const&,glm::detail::tvec2<float> const&,glm::detail::tvec2<float> const&,glm::detail::tvec2<float> const&);
		void _drawTiled(UIRenderContext &,glm::detail::tvec2<float> const&,glm::detail::tvec2<float> const&,glm::detail::tvec2<float> const&,glm::detail::tvec2<float> const&);
		void clone(std::shared_ptr<UIControl> &);
		void clone(std::shared_ptr<UIControl> &);
		void getAlpha(void);
		void getAlpha(void);
		void getClipDirection(void);
		void getClipRatio(void);
		void getClipRatio(void);
		void getColor(void);
		void getColor(void);
		void getMaterialName(void);
		void getMaterialName(void);
		void getNineSliceSize(void);
		void getResourceLocation(void);
		void getResourceLocation(void);
		void getTexture(void);
		void getTexture(void);
		void getTextureSource(void);
		void getTextureSource(void);
		void getTiled(void);
		void getUV(void);
		void getUVSize(void);
		void getZipFolder(void);
		void getZipFolder(void);
		void render(UIRenderContext &);
		void render(UIRenderContext &);
		void setAlpha(float);
		void setAlpha(float);
		void setClipDirection(ui::ClipDirection const&);
		void setClipDirection(ui::ClipDirection const&);
		void setClipPixelPerfect(bool);
		void setClipPixelPerfect(bool);
		void setClipRatio(float);
		void setClipRatio(float);
		void setColor(Color const&);
		void setColor(Color const&);
		void setGrayScaleMaterial(void);
		void setGrayScaleMaterial(void);
		void setKeepRatio(bool);
		void setKeepRatio(bool);
		void setNineSliceSize(ui::SliceSize const&);
		void setNineSliceSize(ui::SliceSize const&);
		void setPixelPerfect(bool);
		void setPixelPerfect(bool);
		void setResourceLocation(ResourceLocation const&);
		void setResourceLocation(ResourceLocation const&);
		void setTextureSource(ui::TextureSource);
		void setTextureSource(ui::TextureSource);
		void setTiled(bool);
		void setTiled(bool);
		void setUV(glm::detail::tvec2<float> const&);
		void setUV(glm::detail::tvec2<float> const&);
		void setUVSize(glm::detail::tvec2<float> const&);
		void setUVSize(glm::detail::tvec2<float> const&);
		void setZipFolder(std::string);
		void setZipFolder(std::string);
		void ~SpriteComponent();
		void ~SpriteComponent();
		void ~SpriteComponent();
		void ~SpriteComponent();
};
