#pragma once
class UIControlFactory{
	public:
		UIControlFactory(UIDefRepository const&,Json::Value &,NameRegistry &,UISoundPlayer const&,Font *);
		UIControlFactory(UIDefRepository const&,Json::Value &,NameRegistry &,UISoundPlayer const&,Font *);
		void _addAnimToComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _addAnimToComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _createButton(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createButton(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createCustom(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createCustom(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createEditBox(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createEditBox(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createFactory(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createFactory(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createFromResolvedDef(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _createFromResolvedDef(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _createGrid(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createGrid(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createImage(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createImage(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createInputPanel(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createInputPanel(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createLabel(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createLabel(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createPanel(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createPanel(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createScreen(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createScreen(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createScrollTrack(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createScrollTrack(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createScrollView(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createScrollView(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createScrollbarBox(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createScrollbarBox(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createSlider(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createSlider(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createSliderBox(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createSliderBox(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createSliderRenderer(UIResolvedDef const&);
		void _createSliderRenderer(UIResolvedDef const&);
		void _createStackPanel(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createStackPanel(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createTab(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createTab(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createToggle(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _createToggle(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _getControlBreadthFirst(std::shared_ptr<UIControl> &,std::string);
		void _populateAnimations(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateAnimations(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateButtonComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateButtonComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateControl(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateControl(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateCustomRenderComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateCustomRenderComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateDataBindingComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateDataBindingComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateDebugRendererComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateDebugRendererComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateFactoryComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateFactoryComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateFocusComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateFocusComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateGestureComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateGestureComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateGridComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateGridComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateGridItemComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateGridItemComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateInputComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateInputComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateLayoutComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateLayoutComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateScreenComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateScreenComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateScrollViewComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateScrollViewComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateScrollbarBoxComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateScrollbarComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateSliderBoxComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateSliderComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateSliderComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateSliderGroupManagerComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateSliderGroupManagerComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateSoundComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateSoundComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateSpriteComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateSpriteComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateStackPanelComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateStackPanelComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateTabComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateTabComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateTextComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateTextComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateTextEditComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateTextEditComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateToggleComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateToggleComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateToggleGroupManagerComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _populateToggleGroupManagerComponent(UIResolvedDef const&,std::shared_ptr<UIControl> &);
		void _postCreate(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _postCreate(std::shared_ptr<UIControl> &,UIResolvedDef const&);
		void _postCreateGrid(std::shared_ptr<UIControl> &);
		void _resolveAnimatedProperty<Color>(UIResolvedDef const&,std::shared_ptr<UIControl> &,std::string const&);
		void _resolveAnimatedProperty<Color>(UIResolvedDef const&,std::shared_ptr<UIControl> &,std::string const&);
		void _resolveAnimatedProperty<float>(UIResolvedDef const&,std::shared_ptr<UIControl> &,std::string const&);
		void _resolveAnimatedProperty<float>(UIResolvedDef const&,std::shared_ptr<UIControl> &,std::string const&);
		void tvec2<float>>(UIResolvedDef const&,std::shared_ptr<UIControl> &,std::string const&);
		void tvec2<float>>(UIResolvedDef const&,std::shared_ptr<UIControl> &,std::string const&);
		void LayoutOffset>(UIResolvedDef const&,std::shared_ptr<UIControl> &,std::string const&);
		void LayoutOffset>(UIResolvedDef const&,std::shared_ptr<UIControl> &,std::string const&);
		void _setName(std::shared_ptr<UIControl> &,UIResolvedDef const&,std::string const&);
		void addAnimRefToControl(std::shared_ptr<UIControl> &,std::string const&);
		void addAnimRefToControl(std::shared_ptr<UIControl> &,std::string const&);
		void createControlTree(std::shared_ptr<UIControl> const&,std::shared_ptr<UIControl>&);
		void createControlTree(std::shared_ptr<UIControl> const&,std::shared_ptr<UIControl>&);
		void createControlTree(std::string const&,std::shared_ptr<UIControl>);
		void createControlTree(std::string const&,std::shared_ptr<UIControl>);
		void ~UIControlFactory();
		void ~UIControlFactory();
};
