#pragma once
class Weather{
	public:
		Weather(Dimension &);
		Weather(Dimension &);
		void _prepareWeather(void);
		void calcRainCycleTime(void);
		void calcRainDuration(void);
		void calcSnowBlockDepth(BlockSource &,BlockPos const&,int);
		void calcSnowBlockDepth(BlockSource &,BlockPos const&,int);
		void canPlaceTopSnow(BlockSource &,BlockPos const&,bool,bool,int *);
		void canPlaceTopSnow(BlockSource &,BlockPos const&,bool,bool,int *);
		void getFogLevel(void);
		void getFogLevel(void);
		void getLightningLevel(float);
		void getLightningLevel(float);
		void getRainLevel(float);
		void getRainLevel(float);
		void getSkyFlashTime(void);
		void getSkyFlashTime(void);
		void isLightning(void);
		void isLightning(void);
		void isRaining(void);
		void isRaining(void);
		void isRainingAt(BlockSource &,BlockPos const&);
		void isRainingAt(BlockSource &,BlockPos const&);
		void isSnowingAt(BlockSource &,BlockPos const&);
		void isSnowingAt(BlockSource &,BlockPos const&);
		void levelEvent(LevelEvent,Vec3 const&,int);
		void levelEvent(LevelEvent,Vec3 const&,int);
		void rebuildTopSnowToDepth(BlockSource &,BlockPos const&,int);
		void rebuildTopSnowToDepth(BlockSource &,BlockPos const&,int);
		void serverTick(void);
		void serverTick(void);
		void setFogLevel(float);
		void setFogLevel(float);
		void setLightningLevel(float);
		void setRainLevel(float);
		void setSkyFlashTime(int);
		void setSkyFlashTime(int);
		void stop(void);
		void stop(void);
		void tick(void);
		void tick(void);
		void tryToPlaceTopSnow(BlockSource &,BlockPos const&,bool,bool);
		void tryToPlaceTopSnow(BlockSource &,BlockPos const&,bool,bool);
		void ~Weather();
		void ~Weather();
		void ~Weather();
		void ~Weather();
};
