#pragma once
class Zombie{
	public:
		Zombie(BlockSource &);
		Zombie(BlockSource &);
		Zombie(BlockSource &);
		void _getAmbientSound(void);
		void _getAmbientSound(void);
		void _getDeathSound(void);
		void _getDeathSound(void);
		void _getHurtSound(void);
		void _getHurtSound(void);
		void _internalSetSize(float);
		void _playStepSound(BlockPos const&,int);
		void _playStepSound(BlockPos const&,int);
		void _updateSize(bool);
		void addAdditionalSaveData(CompoundTag &);
		void addAdditionalSaveData(CompoundTag &);
		void canAddRider(Entity &);
		void canAddRider(Entity &);
		void determineStartingGear(void);
		void determineStartingGear(void);
		void die(EntityDamageSource const&);
		void die(EntityDamageSource const&);
		void doHurtTarget(Entity *);
		void doHurtTarget(Entity *);
		void dropRareDeathLoot(void);
		void dropRareDeathLoot(void);
		void finalizeMobSpawn(void);
		void finalizeMobSpawn(void);
		void getArmorValue(void);
		void getArmorValue(void);
		void getBabyProbability(void);
		void getBabyProbability(void);
		void getDeathLoot(void);
		void getDeathLoot(void);
		void getEntityTypeId(void);
		void getEntityTypeId(void);
		void getExperienceReward(void);
		void getExperienceReward(void);
		void getRidingHeight(void);
		void getRidingHeight(void);
		void getZombieType(void);
		void isBaby(void);
		void isBaby(void);
		void normalTick(void);
		void normalTick(void);
		void positionRider(Entity &);
		void positionRider(Entity &);
		void postInit(void);
		void postInit(void);
		void readAdditionalSaveData(CompoundTag const&);
		void readAdditionalSaveData(CompoundTag const&);
		void registerAttributes(void);
		void registerAttributes(void);
		void setBaby(bool);
		void setBaby(bool);
		void setSize(float,float);
		void setSize(float,float);
		void setZombieType(Zombie::ZombieType);
		void setZombieType(Zombie::ZombieType);
		void updateZombieParams(void);
		void updateZombieParams(void);
		void useNewAi(void);
		void useNewAi(void);
		void ~Zombie();
		void ~Zombie();
};
